import { Icons } from "../assets/icons.mu.js";
import { DemoGroupService, DemoVM } from "./demo-group-service.mjs";
import { DemoPlatformIcons } from "./demo-platform-icons.mu.js";
import { DemoStorageStore } from "./demo-storage-store.mjs";
import { AnimationsModule } from "./groups/animations.module.mu.js";
import { ControlsModule } from "./groups/controls.module.mu.js";
import { DemosModule } from "./groups/demos.module.mu.js";
import { PatternsModule } from "./groups/patterns.module.mu.js";
import { ShapeLibraryModule } from "./groups/shape-library.module.mu.js";
import { StylesModule } from "./groups/styles.module.mu.js";
import { DataTemplate, TextBlock } from "@pragmatic-tech-ai/mural/basic";
import { DiagramStorageKey } from "@pragmatic-tech-ai/mural/framework/diagram/diagram-document.js";
import { ListBox } from "@pragmatic-tech-ai/mural/framework/list/list-box.js";
import { EditorShell } from "@pragmatic-tech-ai/mural/framework/shell/editor-shell.js";
import { ContentHostService } from "@pragmatic-tech-ai/mural/framework/shell/services/content-host-service.js";
import { Material, MaterialLight } from "@pragmatic-tech-ai/mural/resources/material";
import { Application, DataContextBinding, NameScope, ServiceProvider, Thickness } from "@pragmatic-tech-ai/mural/runtime";

export const app = (() => {
    const _app0 = new Application();
    _app0.initialize({ theme: Material, scheme: MaterialLight });
    _app0.Services.register(ServiceProvider.tokenFor(DiagramStorageKey), (p) => new DemoStorageStore(p), 'singleton');
    _app0.Services.register(ServiceProvider.tokenFor(ContentHostService), (p) => new ContentHostService(p), 'singleton');
    _app0.Modules.Add(AnimationsModule);
    _app0.Modules.Add(ControlsModule);
    _app0.Modules.Add(DemosModule);
    _app0.Modules.Add(PatternsModule);
    _app0.Modules.Add(StylesModule);
    _app0.Modules.Add(ShapeLibraryModule);
    const _rd1 = _app0.Resources;
    for (const [_k, _v] of DemoPlatformIcons.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of Icons.Clone().Entries()) _rd1.Set(_k, _v);
    const _tmpl2 = new DataTemplate((_data) => {
        const _listBox3 = new ListBox();
        _listBox3.set_property_value(ListBox.ItemsSourceKey, DataContextBinding(_listBox3, "Items"));
        _listBox3.set_property_value(ListBox.SelectedItemKey, DataContextBinding(_listBox3, "SelectedItem"));
        return _listBox3;
    }, DemoGroupService);
    _rd1.Set(DemoGroupService, _tmpl2);
    const _tmpl4 = new DataTemplate((_data) => {
        const _textBlock5 = new TextBlock();
        _textBlock5.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock5, "Label"));
        _textBlock5.set_property_value(TextBlock.MarginKey, new Thickness(4, 3, 4, 3));
        return _textBlock5;
    }, DemoVM);
    _rd1.Set(DemoVM, _tmpl4);
    const _editorShell6 = new EditorShell();
    _editorShell6.SetNameScope(new NameScope());
    _rd1.Root = _editorShell6;
    return _app0;
})();
