import { Icons } from "../assets/icons.mu.js";
import { AnimationDeclarativeDemo } from "../demos/animation-declarative/animation-declarative.mu.js";
import { AnimationNamedDemo } from "../demos/animation-named/animation-named.mu.js";
import { AnimationTriggersDemo } from "../demos/animation-triggers/animation-triggers.mu.js";
import { AnimationDemo } from "../demos/animation/animation.mu.js";
import { BadgeDemo } from "../demos/badge/badge.mu.js";
import { BannerDemo } from "../demos/banner/banner.mu.js";
import { BottomAppBarDemo } from "../demos/bottom-app-bar/bottom-app-bar.mu.js";
import { BottomSheetDemo } from "../demos/bottom-sheet/bottom-sheet.mu.js";
import { BouncingBallDemo } from "../demos/bouncing-ball/bouncing-ball.mu.js";
import { ButtonGroupDemo } from "../demos/button-group/button-group.mu.js";
import { CardDemo } from "../demos/card/card.mu.js";
import { CarouselDemo } from "../demos/carousel/carousel.mu.js";
import { ColorPickerDemo } from "../demos/color-picker/color-picker.mu.js";
import { CommandsDemo } from "../demos/commands/commands.mu.js";
import { ContextMenuDemo } from "../demos/context-menu/context-menu.mu.js";
import { CounterDemo } from "../demos/counter/counter.mu.js";
import { DashboardDemo } from "../demos/dashboard/dashboard.mu.js";
import { DatePickerDemo } from "../demos/date-picker/date-picker.mu.js";
import { DiagramDemo } from "../demos/diagram/diagram.mu.js";
import { DialogDemo } from "../demos/dialog/dialog.mu.js";
import { DragDropExtendedDemo } from "../demos/drag-drop-extended/drag-drop-extended.mu.js";
import { DragDropDemo } from "../demos/drag-drop/drag-drop.mu.js";
import { DrawerDemo } from "../demos/drawer/drawer.mu.js";
import { FabMenuDemo } from "../demos/fab-menu/fab-menu.mu.js";
import { FabDemo } from "../demos/fab/fab.mu.js";
import { FillEditorDemo } from "../demos/fill-editor/fill-editor.mu.js";
import { HitTestDemo } from "../demos/hit-test/hit-test.mu.js";
import { IconButtonDemo } from "../demos/icon-button/icon-button.mu.js";
import { ListBoxDemo } from "../demos/list-box/list-box.mu.js";
import { LoadingIndicatorDemo } from "../demos/loading-indicator/loading-indicator.mu.js";
import { MenuDemo } from "../demos/menu/menu.mu.js";
import { NavigationRailDemo } from "../demos/navigation-rail/navigation-rail.mu.js";
import { PenEditorDemo } from "../demos/pen-editor/pen-editor.mu.js";
import { PropertyGridDemo } from "../demos/property-grid/property-grid.mu.js";
import { RibbonDemo } from "../demos/ribbon/ribbon.mu.js";
import { RichTextBlockDemo } from "../demos/rich-text-block/rich-text-block.mu.js";
import { RichTextEditorDemo } from "../demos/rich-text-editor/rich-text-editor.mu.js";
import { SegmentedButtonDemo } from "../demos/segmented-button/segmented-button.mu.js";
import { ShapesDemo } from "../demos/shapes/shapes.mu.js";
import { SideSheetDemo } from "../demos/side-sheet/side-sheet.mu.js";
import { SliderDemo } from "../demos/slider/slider.mu.js";
import { SpinEditDemo } from "../demos/spin-edit/spin-edit.mu.js";
import { SplitButtonDemo } from "../demos/split-button/split-button.mu.js";
import { SplitterDemo } from "../demos/splitter/splitter.mu.js";
import { StatusBarDemo } from "../demos/status-bar/status-bar.mu.js";
import { TextBoxDemo } from "../demos/text-box/text-box.mu.js";
import { TextFormatDemo } from "../demos/text-format/text-format.mu.js";
import { TextOnPathDemo } from "../demos/text-on-path/text-on-path.mu.js";
import { TimePickerDemo } from "../demos/time-picker/time-picker.mu.js";
import { ToggleButtonDemo } from "../demos/toggle-button/toggle-button.mu.js";
import { ToolBarDemo } from "../demos/tool-bar/tool-bar.mu.js";
import { TopAppBarDemo } from "../demos/top-app-bar/top-app-bar.mu.js";
import { TreeViewDemo } from "../demos/tree-view/tree-view.mu.js";
import { WordToolboxDemo } from "../demos/word-toolbox/word-toolbox.mu.js";
import { DemoVM } from "./demo-group-services.mjs";
import { DemoPlatformIcons } from "./demo-platform-icons.mu.js";
import { DemoPlatformModule } from "./demo-platform.module.mu.js";
import { DemoStorageStore } from "./demo-storage-store.mjs";
import { DataTemplate, TextBlock } from "@pragmatic-tech-ai/mural/basic";
import { DiagramStorageKey } from "@pragmatic-tech-ai/mural/framework/diagram/diagram-document.js";
import { EditorShell } from "@pragmatic-tech-ai/mural/framework/shell/editor-shell.js";
import { Material, MaterialLight } from "@pragmatic-tech-ai/mural/resources/material";
import { Application, DataContextBinding, NameScope, ServiceProvider, Thickness } from "@pragmatic-tech-ai/mural/runtime";

export const app = (() => {
    const _app0 = new Application();
    _app0.initialize({ theme: Material, scheme: MaterialLight });
    _app0.Services.register(ServiceProvider.tokenFor(DiagramStorageKey), (p) => new DemoStorageStore(p), 'singleton');
    _app0.Modules.Add(DemoPlatformModule);
    const _rd1 = _app0.Resources;
    for (const [_k, _v] of DemoPlatformIcons.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of AnimationDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of AnimationDeclarativeDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of AnimationNamedDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of AnimationTriggersDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of BadgeDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of BannerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of BottomAppBarDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of BottomSheetDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of BouncingBallDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of LoadingIndicatorDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SideSheetDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DatePickerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TimePickerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of CarouselDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ButtonGroupDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of CardDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DialogDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ColorPickerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of CommandsDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ContextMenuDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of CounterDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DashboardDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DiagramDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of Icons.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DragDropDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DragDropExtendedDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DrawerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of FabDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of FabMenuDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of FillEditorDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of IconButtonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ListBoxDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of MenuDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of NavigationRailDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of PenEditorDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of RibbonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of RichTextEditorDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of RichTextBlockDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of HitTestDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SegmentedButtonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ShapesDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SliderDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SpinEditDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SplitButtonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SplitterDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of StatusBarDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TextBoxDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TextFormatDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TextOnPathDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ToggleButtonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ToolBarDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TopAppBarDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TreeViewDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of WordToolboxDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of PropertyGridDemo.Clone().Entries()) _rd1.Set(_k, _v);
    const _tmpl2 = new DataTemplate((_data) => {
        const _textBlock3 = new TextBlock();
        _textBlock3.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock3, "Label"));
        _textBlock3.set_property_value(TextBlock.MarginKey, new Thickness(4, 3, 4, 3));
        return _textBlock3;
    }, DemoVM);
    _rd1.Set(DemoVM, _tmpl2);
    const _editorShell4 = new EditorShell();
    _editorShell4.SetNameScope(new NameScope());
    _rd1.Root = _editorShell4;
    return _app0;
})();
