import { RichTextEditorVM } from "./rich-text-editor-vm.mjs";
import { Bold, Border, DataTemplate, Dock, DockPanel, FlowDocument, Italic, Line, List, ListItem, ListMarkerStyle, Orientation, Paragraph, RichTextBox, Run, StackPanel, TextBlock, TextWrapping, Underline } from "@pragmatic-tech-ai/mural/basic";
import { Button, ButtonVariant } from "@pragmatic-tech-ai/mural/framework/buttons/button.js";
import { DynamicResource, NameScope, ResourceDictionary, Thickness, VerticalAlignment } from "@pragmatic-tech-ai/mural/runtime";
import { FontStyle, FontWeight, Pen, TextDecorations } from "@pragmatic-tech-ai/mural/visual-engine";


const _gate_RichTextEditorDemo = Symbol("RichTextEditorDemo.ctor");
export class RichTextEditorDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_RichTextEditorDemo) {
            throw new Error("RichTextEditorDemo is private — use RichTextEditorDemo.Clone()");
        }
    }
    static Clone() {
        const t = new RichTextEditorDemo(_gate_RichTextEditorDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            let _button1, _button2, _button3, _button4, _button5, _richTextBox6;
            const _border7 = new Border();
            _border7.SetNameScope(new NameScope());
            _border7.set_property_value(Border.FillKey, DynamicResource(_border7, "Surface"));
            const _dockPanel8 = new DockPanel();
            const _border9 = new Border();
            _border9.set_property_value(DockPanel.DockKey, Dock.Top);
            _border9.set_property_value(Border.FillKey, DynamicResource(_border9, "Primary"));
            _border9.set_property_value(Border.PaddingKey, new Thickness(20, 14, 20, 14));
            const _stackPanel10 = new StackPanel();
            _stackPanel10.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, "Rich text editor");
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock11.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock11.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock11, "OnPrimary"));
            _stackPanel10.AddChild(_textBlock11);
            const _textBlock12 = new TextBlock();
            _textBlock12.set_property_value(TextBlock.TextKey, "Click in, select text, and format with the toolbar or Ctrl+B / Ctrl+I / Ctrl+U. Enter splits a paragraph; Tab / Shift+Tab indent and outdent list items.");
            _textBlock12.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock12.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock12, "OnPrimary"));
            _textBlock12.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock12.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _stackPanel10.AddChild(_textBlock12);
            _border9.SetChild(_stackPanel10);
            _dockPanel8.AddChild(_border9);
            const _border13 = new Border();
            _border13.set_property_value(DockPanel.DockKey, Dock.Top);
            _border13.set_property_value(Border.FillKey, DynamicResource(_border13, "SurfaceContainerLow"));
            _border13.set_property_value(Border.PaddingKey, new Thickness(16, 8, 16, 8));
            const _stackPanel14 = new StackPanel();
            _stackPanel14.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _button1 = new Button();
            _button1.Name = "BoldBtn";
            _button1.set_property_value(Button.VariantKey, ButtonVariant.Tonal);
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, "B");
            _textBlock15.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock15.set_property_value(TextBlock.FontSizeKey, 15);
            _button1.Content = _textBlock15;
            _stackPanel14.AddChild(_button1);
            _button2 = new Button();
            _button2.Name = "ItalicBtn";
            _button2.set_property_value(Button.VariantKey, ButtonVariant.Tonal);
            _button2.set_property_value(Button.MarginKey, new Thickness(6, 0, 0, 0));
            const _textBlock16 = new TextBlock();
            _textBlock16.set_property_value(TextBlock.TextKey, "I");
            _textBlock16.set_property_value(TextBlock.FontStyleKey, FontStyle.Italic);
            _textBlock16.set_property_value(TextBlock.FontSizeKey, 15);
            _button2.Content = _textBlock16;
            _stackPanel14.AddChild(_button2);
            _button3 = new Button();
            _button3.Name = "UnderlineBtn";
            _button3.set_property_value(Button.VariantKey, ButtonVariant.Tonal);
            _button3.set_property_value(Button.MarginKey, new Thickness(6, 0, 0, 0));
            const _textBlock17 = new TextBlock();
            _textBlock17.set_property_value(TextBlock.TextKey, "U");
            _textBlock17.set_property_value(TextBlock.TextDecorationsKey, TextDecorations.Underline);
            _textBlock17.set_property_value(TextBlock.FontSizeKey, 15);
            _button3.Content = _textBlock17;
            _stackPanel14.AddChild(_button3);
            _button4 = new Button();
            _button4.Name = "IndentBtn";
            _button4.set_property_value(Button.VariantKey, ButtonVariant.Outlined);
            _button4.set_property_value(Button.MarginKey, new Thickness(16, 0, 0, 0));
            const _textBlock18 = new TextBlock();
            _textBlock18.set_property_value(TextBlock.TextKey, "Indent");
            _button4.Content = _textBlock18;
            _stackPanel14.AddChild(_button4);
            _button5 = new Button();
            _button5.Name = "OutdentBtn";
            _button5.set_property_value(Button.VariantKey, ButtonVariant.Outlined);
            _button5.set_property_value(Button.MarginKey, new Thickness(6, 0, 0, 0));
            const _textBlock19 = new TextBlock();
            _textBlock19.set_property_value(TextBlock.TextKey, "Outdent");
            _button5.Content = _textBlock19;
            _stackPanel14.AddChild(_button5);
            _border13.SetChild(_stackPanel14);
            _dockPanel8.AddChild(_border13);
            const _line20 = new Line();
            _line20.set_property_value(DockPanel.DockKey, Dock.Top);
            _line20.set_property_value(Line.OrientationKey, Orientation.Horizontal);
            _line20.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line20, "OutlineVariant"), 1));
            _dockPanel8.AddChild(_line20);
            const _border21 = new Border();
            _border21.set_property_value(Border.PaddingKey, new Thickness(28, 24, 28, 24));
            _richTextBox6 = new RichTextBox();
            _richTextBox6.Name = "Editor";
            _richTextBox6.set_property_value(RichTextBox.VerticalAlignmentKey, VerticalAlignment.Top);
            _richTextBox6.set_property_value(RichTextBox.FontSizeKey, 15);
            const _flowDocument22 = new FlowDocument();
            const _paragraph23 = new Paragraph();
            const _run24 = new Run("Rich text editing in ");
            _paragraph23.AddChild(_run24);
            const _bold25 = new Bold();
            const _run26 = new Run("@pragmatic-tech-ai/mural");
            _bold25.AddChild(_run26);
            _paragraph23.AddChild(_bold25);
            const _run27 = new Run(".");
            _paragraph23.AddChild(_run27);
            _flowDocument22.AddChild(_paragraph23);
            const _paragraph28 = new Paragraph();
            const _run29 = new Run("Select any text and toggle ");
            _paragraph28.AddChild(_run29);
            const _bold30 = new Bold();
            const _run31 = new Run("bold");
            _bold30.AddChild(_run31);
            _paragraph28.AddChild(_bold30);
            const _run32 = new Run(", ");
            _paragraph28.AddChild(_run32);
            const _italic33 = new Italic();
            const _run34 = new Run("italic");
            _italic33.AddChild(_run34);
            _paragraph28.AddChild(_italic33);
            const _run35 = new Run(", or ");
            _paragraph28.AddChild(_run35);
            const _underline36 = new Underline();
            const _run37 = new Run("underline");
            _underline36.AddChild(_run37);
            _paragraph28.AddChild(_underline36);
            const _run38 = new Run(". Press Enter to start a new paragraph, and keep typing to edit.");
            _paragraph28.AddChild(_run38);
            _flowDocument22.AddChild(_paragraph28);
            const _list39 = new List();
            _list39.set_property_value(List.MarkerStyleKey, ListMarkerStyle.Disc);
            const _listItem40 = new ListItem();
            const _paragraph41 = new Paragraph();
            const _run42 = new Run("A bulleted list item");
            _paragraph41.AddChild(_run42);
            _listItem40.AddChild(_paragraph41);
            _list39.AddChild(_listItem40);
            const _listItem43 = new ListItem();
            const _paragraph44 = new Paragraph();
            const _run45 = new Run("Put the caret here and press Tab to nest it, Shift+Tab to outdent");
            _paragraph44.AddChild(_run45);
            _listItem43.AddChild(_paragraph44);
            _list39.AddChild(_listItem43);
            _flowDocument22.AddChild(_list39);
            const _list46 = new List();
            _list46.set_property_value(List.MarkerStyleKey, ListMarkerStyle.Decimal);
            const _listItem47 = new ListItem();
            const _paragraph48 = new Paragraph();
            const _run49 = new Run("An ordered item");
            _paragraph48.AddChild(_run49);
            _listItem47.AddChild(_paragraph48);
            _list46.AddChild(_listItem47);
            const _listItem50 = new ListItem();
            const _paragraph51 = new Paragraph();
            const _run52 = new Run("Another ordered item");
            _paragraph51.AddChild(_run52);
            _listItem50.AddChild(_paragraph51);
            _list46.AddChild(_listItem50);
            _flowDocument22.AddChild(_list46);
            _richTextBox6.Document = _flowDocument22;
            _border21.SetChild(_richTextBox6);
            _dockPanel8.AddChild(_border21);
            _border7.SetChild(_dockPanel8);
            return _border7;
        }, RichTextEditorVM);
        t.Set(RichTextEditorVM, _tmpl0);
        return t;
    }
}
