import { BadgeDemo } from "../../demos/badge/badge.mu.js";
import { BannerDemo } from "../../demos/banner/banner.mu.js";
import { BottomAppBarDemo } from "../../demos/bottom-app-bar/bottom-app-bar.mu.js";
import { BottomSheetDemo } from "../../demos/bottom-sheet/bottom-sheet.mu.js";
import { ButtonGroupDemo } from "../../demos/button-group/button-group.mu.js";
import { CardDemo } from "../../demos/card/card.mu.js";
import { CarouselDemo } from "../../demos/carousel/carousel.mu.js";
import { ContextMenuDemo } from "../../demos/context-menu/context-menu.mu.js";
import { DatePickerDemo } from "../../demos/date-picker/date-picker.mu.js";
import { DialogDemo } from "../../demos/dialog/dialog.mu.js";
import { DrawerDemo } from "../../demos/drawer/drawer.mu.js";
import { FabMenuDemo } from "../../demos/fab-menu/fab-menu.mu.js";
import { FabDemo } from "../../demos/fab/fab.mu.js";
import { IconButtonDemo } from "../../demos/icon-button/icon-button.mu.js";
import { ListBoxDemo } from "../../demos/list-box/list-box.mu.js";
import { LoadingIndicatorDemo } from "../../demos/loading-indicator/loading-indicator.mu.js";
import { MenuDemo } from "../../demos/menu/menu.mu.js";
import { NavigationRailDemo } from "../../demos/navigation-rail/navigation-rail.mu.js";
import { PropertyGridDemo } from "../../demos/property-grid/property-grid.mu.js";
import { SegmentedButtonDemo } from "../../demos/segmented-button/segmented-button.mu.js";
import { SideSheetDemo } from "../../demos/side-sheet/side-sheet.mu.js";
import { SliderDemo } from "../../demos/slider/slider.mu.js";
import { SpinEditDemo } from "../../demos/spin-edit/spin-edit.mu.js";
import { SplitButtonDemo } from "../../demos/split-button/split-button.mu.js";
import { SplitterDemo } from "../../demos/splitter/splitter.mu.js";
import { StatusBarDemo } from "../../demos/status-bar/status-bar.mu.js";
import { TextBoxDemo } from "../../demos/text-box/text-box.mu.js";
import { TimePickerDemo } from "../../demos/time-picker/time-picker.mu.js";
import { ToggleButtonDemo } from "../../demos/toggle-button/toggle-button.mu.js";
import { ToolBarDemo } from "../../demos/tool-bar/tool-bar.mu.js";
import { TopAppBarDemo } from "../../demos/top-app-bar/top-app-bar.mu.js";
import { TreeViewDemo } from "../../demos/tree-view/tree-view.mu.js";
import { ControlsService } from "./controls-service.mjs";
import { Capability, ShellModule } from "@pragmatic-tech-ai/mural/framework/shell/module.js";
import { DynamicResource, ServiceProvider } from "@pragmatic-tech-ai/mural/runtime";

export const ControlsModule = (() => {
    const _shellModule0 = new ShellModule();
    _shellModule0.set_property_value(ShellModule.NameKey, "Controls");
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(ControlsService), (p) => new ControlsService(p), 'singleton');
    const _rd1 = _shellModule0.Resources;
    for (const [_k, _v] of BadgeDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of BannerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of BottomAppBarDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of BottomSheetDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ButtonGroupDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of CardDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of CarouselDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ContextMenuDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DatePickerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DialogDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DrawerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of FabDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of FabMenuDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of IconButtonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ListBoxDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of LoadingIndicatorDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of MenuDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of NavigationRailDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of PropertyGridDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SegmentedButtonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SideSheetDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SliderDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SpinEditDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SplitButtonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of SplitterDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of StatusBarDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TextBoxDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TimePickerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ToggleButtonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ToolBarDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TopAppBarDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TreeViewDemo.Clone().Entries()) _rd1.Set(_k, _v);
    const _capability2 = new Capability();
    _capability2.set_property_value(Capability.NameKey, "Controls");
    _capability2.set_property_value(Capability.IconKey, DynamicResource(_capability2, "ControlsIcon"));
    _capability2.set_property_value(Capability.ServiceKeyKey, ControlsService);
    _shellModule0.AddChild(_capability2);
    return _shellModule0;
})();
