import { BouncingBallDemo } from "../../demos/bouncing-ball/bouncing-ball.mu.js";
import { ColorPickerDemo } from "../../demos/color-picker/color-picker.mu.js";
import { CommandsDemo } from "../../demos/commands/commands.mu.js";
import { DiagramDemo } from "../../demos/diagram/diagram.mu.js";
import { DragDropExtendedDemo } from "../../demos/drag-drop-extended/drag-drop-extended.mu.js";
import { DragDropDemo } from "../../demos/drag-drop/drag-drop.mu.js";
import { FillEditorDemo } from "../../demos/fill-editor/fill-editor.mu.js";
import { HitTestDemo } from "../../demos/hit-test/hit-test.mu.js";
import { PenEditorDemo } from "../../demos/pen-editor/pen-editor.mu.js";
import { RibbonDemo } from "../../demos/ribbon/ribbon.mu.js";
import { RichTextBlockDemo } from "../../demos/rich-text-block/rich-text-block.mu.js";
import { RichTextEditorDemo } from "../../demos/rich-text-editor/rich-text-editor.mu.js";
import { TextFormatDemo } from "../../demos/text-format/text-format.mu.js";
import { TextOnPathDemo } from "../../demos/text-on-path/text-on-path.mu.js";
import { WordToolboxDemo } from "../../demos/word-toolbox/word-toolbox.mu.js";
import { DemosService } from "./demos-service.mjs";
import { Capability, ShellModule } from "@pragmatic-tech-ai/mural/framework/shell/module.js";
import { DynamicResource, ServiceProvider } from "@pragmatic-tech-ai/mural/runtime";

export const DemosModule = (() => {
    const _shellModule0 = new ShellModule();
    _shellModule0.set_property_value(ShellModule.NameKey, "Demos");
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(DemosService), (p) => new DemosService(p), 'singleton');
    const _rd1 = _shellModule0.Resources;
    for (const [_k, _v] of BouncingBallDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of ColorPickerDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of CommandsDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DiagramDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DragDropDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of DragDropExtendedDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of FillEditorDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of HitTestDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of PenEditorDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of RibbonDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of RichTextBlockDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of RichTextEditorDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TextFormatDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of TextOnPathDemo.Clone().Entries()) _rd1.Set(_k, _v);
    for (const [_k, _v] of WordToolboxDemo.Clone().Entries()) _rd1.Set(_k, _v);
    const _capability2 = new Capability();
    _capability2.set_property_value(Capability.NameKey, "Demos");
    _capability2.set_property_value(Capability.IconKey, DynamicResource(_capability2, "DemosIcon"));
    _capability2.set_property_value(Capability.ServiceKeyKey, DemosService);
    _shellModule0.AddChild(_capability2);
    return _shellModule0;
})();
