import { TextOnPathVM } from "./text-on-path-vm.mjs";
import { Border, Canvas, DataTemplate, Dock, DockPanel, Line, Orientation, Slider, StackPanel, TextBlock, TextBox, TextWrapping } from "@pragmatic-tech-ai/mural/basic";
import { ColorPicker } from "@pragmatic-tech-ai/mural/framework";
import { Button } from "@pragmatic-tech-ai/mural/framework/buttons/button.js";
import { ComboBox } from "@pragmatic-tech-ai/mural/framework/list/combo-box.js";
import { DataContextBinding, DynamicResource, NameScope, ResourceDictionary, Thickness } from "@pragmatic-tech-ai/mural/runtime";
import { FontFamily, FontManager, FontSourceKind, FontWeight, Pen } from "@pragmatic-tech-ai/mural/visual-engine";


const _gate_TextOnPathDemo = Symbol("TextOnPathDemo.ctor");
export class TextOnPathDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_TextOnPathDemo) {
            throw new Error("TextOnPathDemo is private — use TextOnPathDemo.Clone()");
        }
    }
    static Clone() {
        const t = new TextOnPathDemo(_gate_TextOnPathDemo);
        FontManager.Current.Register("Roboto", { kind: FontSourceKind.Url, url: new URL("https://cdn.jsdelivr.net/gh/opentypejs/opentype.js@master/test/fonts/Roboto-Black.ttf", import.meta.url).href });
        t.Set("Roboto", new FontFamily("Roboto"));
        const _tmpl0 = new DataTemplate((_data) => {
            let _canvas1;
            const _border2 = new Border();
            _border2.SetNameScope(new NameScope());
            _border2.set_property_value(Border.FillKey, DynamicResource(_border2, "Surface"));
            const _dockPanel3 = new DockPanel();
            const _border4 = new Border();
            _border4.set_property_value(DockPanel.DockKey, Dock.Top);
            _border4.set_property_value(Border.FillKey, DynamicResource(_border4, "Primary"));
            _border4.set_property_value(Border.PaddingKey, new Thickness(20, 14, 20, 14));
            const _stackPanel5 = new StackPanel();
            _stackPanel5.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "Text on a path");
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock6.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock6.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock6, "OnPrimary"));
            _stackPanel5.AddChild(_textBlock6);
            const _textBlock7 = new TextBlock();
            _textBlock7.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock7, "Status"));
            _textBlock7.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock7.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock7, "OnPrimary"));
            _textBlock7.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _stackPanel5.AddChild(_textBlock7);
            _border4.SetChild(_stackPanel5);
            _dockPanel3.AddChild(_border4);
            const _textBlock8 = new TextBlock();
            _textBlock8.set_property_value(DockPanel.DockKey, Dock.Bottom);
            _textBlock8.set_property_value(TextBlock.MarginKey, new Thickness(20, 8, 20, 16));
            _textBlock8.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock8.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock8, "OnSurfaceVariant"));
            _textBlock8.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock8.set_property_value(TextBlock.TextKey, "Each path is flattened to a polyline, then arclength-sampled so every glyph lands at the right tangent. The picker switches the underlying PathGeometry; the text input updates the rendered run; the slider scales the glyph outlines.");
            _dockPanel3.AddChild(_textBlock8);
            const _border9 = new Border();
            _border9.set_property_value(DockPanel.DockKey, Dock.Top);
            _border9.set_property_value(Border.PaddingKey, new Thickness(20, 12, 20, 12));
            const _stackPanel10 = new StackPanel();
            _stackPanel10.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _stackPanel11 = new StackPanel();
            _stackPanel11.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel11.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock12 = new TextBlock();
            _textBlock12.set_property_value(TextBlock.TextKey, "Text");
            _textBlock12.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock12.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock12.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock12, "OnSurface"));
            _textBlock12.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel11.AddChild(_textBlock12);
            const _textBox13 = new TextBox();
            _textBox13.set_property_value(TextBox.WidthKey, 320);
            _textBox13.set_property_value(TextBox.TextKey, DataContextBinding(_textBox13, "Text"));
            _stackPanel11.AddChild(_textBox13);
            _stackPanel10.AddChild(_stackPanel11);
            const _stackPanel14 = new StackPanel();
            _stackPanel14.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel14.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, "Path");
            _textBlock15.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock15.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock15.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock15, "OnSurface"));
            _textBlock15.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel14.AddChild(_textBlock15);
            const _comboBox16 = new ComboBox();
            _comboBox16.set_property_value(ComboBox.WidthKey, 220);
            _comboBox16.set_property_value(ComboBox.ItemsKey, DataContextBinding(_comboBox16, "Paths"));
            _comboBox16.set_property_value(ComboBox.SelectedItemKey, DataContextBinding(_comboBox16, "SelectedPathOption"));
            _comboBox16.set_property_value(ComboBox.DisplayMemberPathKey, "Label");
            _stackPanel14.AddChild(_comboBox16);
            _stackPanel10.AddChild(_stackPanel14);
            const _stackPanel17 = new StackPanel();
            _stackPanel17.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel17.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock18 = new TextBlock();
            _textBlock18.set_property_value(TextBlock.TextKey, "Font size");
            _textBlock18.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock18.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock18.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock18, "OnSurface"));
            _textBlock18.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel17.AddChild(_textBlock18);
            const _slider19 = new Slider();
            _slider19.set_property_value(Slider.WidthKey, 180);
            _slider19.set_property_value(Slider.MinimumKey, 10);
            _slider19.set_property_value(Slider.MaximumKey, 72);
            _slider19.set_property_value(Slider.ValueKey, DataContextBinding(_slider19, "FontSize"));
            _slider19.set_property_value(Slider.SmallChangeKey, 1);
            _slider19.set_property_value(Slider.LargeChangeKey, 4);
            _stackPanel17.AddChild(_slider19);
            _stackPanel10.AddChild(_stackPanel17);
            const _stackPanel20 = new StackPanel();
            _stackPanel20.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel20.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "Side offset");
            _textBlock21.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock21.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock21.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock21, "OnSurface"));
            _textBlock21.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel20.AddChild(_textBlock21);
            const _slider22 = new Slider();
            _slider22.set_property_value(Slider.WidthKey, 180);
            _slider22.set_property_value(Slider.MinimumKey, -50);
            _slider22.set_property_value(Slider.MaximumKey, 50);
            _slider22.set_property_value(Slider.ValueKey, DataContextBinding(_slider22, "SideOffset"));
            _slider22.set_property_value(Slider.SmallChangeKey, 1);
            _slider22.set_property_value(Slider.LargeChangeKey, 5);
            _stackPanel20.AddChild(_slider22);
            _stackPanel10.AddChild(_stackPanel20);
            const _stackPanel23 = new StackPanel();
            _stackPanel23.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel23.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 24, 0));
            const _textBlock24 = new TextBlock();
            _textBlock24.set_property_value(TextBlock.TextKey, "Show");
            _textBlock24.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock24.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock24.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock24, "OnSurface"));
            _textBlock24.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel23.AddChild(_textBlock24);
            const _stackPanel25 = new StackPanel();
            _stackPanel25.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _button26 = new Button();
            _button26.set_property_value(Button.MarginKey, new Thickness(0, 0, 8, 0));
            _button26.set_property_value(Button.CommandKey, DataContextBinding(_button26, "TogglePathCommand"));
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, "Path");
            _button26.Content = _textBlock27;
            _stackPanel25.AddChild(_button26);
            const _button28 = new Button();
            _button28.set_property_value(Button.CommandKey, DataContextBinding(_button28, "ToggleGlyphsCommand"));
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, "Glyphs");
            _button28.Content = _textBlock29;
            _stackPanel25.AddChild(_button28);
            _stackPanel23.AddChild(_stackPanel25);
            _stackPanel10.AddChild(_stackPanel23);
            const _stackPanel30 = new StackPanel();
            _stackPanel30.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel30.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 16, 0));
            const _textBlock31 = new TextBlock();
            _textBlock31.set_property_value(TextBlock.TextKey, "Path colour");
            _textBlock31.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock31.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock31.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock31, "OnSurface"));
            _textBlock31.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel30.AddChild(_textBlock31);
            const _colorPicker32 = new ColorPicker();
            _colorPicker32.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker32, "PathColorHex"));
            _stackPanel30.AddChild(_colorPicker32);
            _stackPanel10.AddChild(_stackPanel30);
            const _stackPanel33 = new StackPanel();
            _stackPanel33.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock34 = new TextBlock();
            _textBlock34.set_property_value(TextBlock.TextKey, "Glyph colour");
            _textBlock34.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock34.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock34.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock34, "OnSurface"));
            _textBlock34.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 4));
            _stackPanel33.AddChild(_textBlock34);
            const _colorPicker35 = new ColorPicker();
            _colorPicker35.set_property_value(ColorPicker.ColorHexKey, DataContextBinding(_colorPicker35, "GlyphColorHex"));
            _stackPanel33.AddChild(_colorPicker35);
            _stackPanel10.AddChild(_stackPanel33);
            _border9.SetChild(_stackPanel10);
            _dockPanel3.AddChild(_border9);
            const _line36 = new Line();
            _line36.set_property_value(DockPanel.DockKey, Dock.Top);
            _line36.set_property_value(Line.OrientationKey, Orientation.Horizontal);
            _line36.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line36, "OutlineVariant"), 1));
            _dockPanel3.AddChild(_line36);
            const _border37 = new Border();
            _border37.set_property_value(Border.FillKey, DynamicResource(_border37, "SurfaceContainerLow"));
            _border37.set_property_value(Border.PaddingKey, new Thickness(20, 20, 20, 20));
            const _border38 = new Border();
            _border38.set_property_value(Border.FillKey, DynamicResource(_border38, "Surface"));
            _border38.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            _border38.set_property_value(Border.PaddingKey, new Thickness(0));
            _canvas1 = new Canvas();
            _canvas1.Name = "surface";
            _canvas1.set_property_value(Canvas.WidthKey, 700);
            _canvas1.set_property_value(Canvas.HeightKey, 440);
            _border38.SetChild(_canvas1);
            _border37.SetChild(_border38);
            _dockPanel3.AddChild(_border37);
            _border2.SetChild(_dockPanel3);
            return _border2;
        }, TextOnPathVM);
        t.Set(TextOnPathVM, _tmpl0);
        return t;
    }
}
