// word-list.mjs — small bundled vocabulary the word-toolbox demo
// draws from. 100 distinct toolbox words (left palette) + a ~2k
// listbox seed (right pane).
//
// The toolbox words are short, easy-to-recognise nouns; visually
// they read well as square tiles. The listbox seed is generated by
// picking from a deterministic word pool with a small fixed-seed
// PRNG so the rendered grid is stable across page reloads — useful
// for hot-reload testing during demo development and for taking
// matched screenshots.

export const TOOLBOX_WORDS: string[] = [
    'apple', 'arrow', 'atlas', 'badge', 'balloon', 'basket', 'beach', 'beaver',
    'bell', 'berry', 'bird', 'block', 'blossom', 'bottle', 'branch', 'breeze',
    'bridge', 'bubble', 'bucket', 'butter', 'cactus', 'candle', 'canvas',
    'castle', 'chair', 'cherry', 'cloud', 'clover', 'comet', 'compass', 'coral',
    'cosmos', 'cotton', 'crane', 'crystal', 'cypress', 'daisy', 'desert',
    'dragon', 'dunes', 'eagle', 'ember', 'fable', 'falcon', 'feather', 'fjord',
    'forest', 'fossil', 'galaxy', 'garden', 'glacier', 'glow', 'grain',
    'harbor', 'harvest', 'horizon', 'island', 'jasmine', 'kettle', 'lantern',
    'lark', 'lichen', 'lilac', 'maple', 'marble', 'meadow', 'melody', 'mirror',
    'moss', 'nectar', 'nest', 'orchard', 'otter', 'pebble', 'pine', 'pollen',
    'prairie', 'quartz', 'quill', 'raven', 'ribbon', 'river', 'rosemary',
    'sapling', 'shadow', 'shell', 'silver', 'sparrow', 'spruce', 'starling',
    'sunrise', 'thicket', 'thistle', 'tide', 'tulip', 'twig', 'valley',
    'vortex', 'willow', 'zephyr',
];

// Deterministic small LCG so we get a stable shuffle without
// depending on Math.random's per-page state. The constants are the
// classic Numerical-Recipes ones; we only need cheap uniform-ish
// indices, not statistical quality.
function lcg(seed: number): () => number
{
    let s = seed >>> 0;
    return () => {
        s = (Math.imul(s, 1664525) + 1013904223) >>> 0;
        return s;
    };
}

// Build a listbox seed: `count` words, drawn from the same pool as
// the toolbox plus a small suffix pool so the listbox shows variety.
// Each entry is a {Word} object so VM-side property reads stay
// consistent whether an entry came from the seed or was dragged in
// from the toolbox.
export interface ListBoxSeedEntry { Word: string; }

export function buildListBoxSeed(count: number): ListBoxSeedEntry[]
{
    const pool = TOOLBOX_WORDS;
    const rng = lcg(0xc0ffee);
    const out: ListBoxSeedEntry[] = new Array(count);
    for (let i = 0; i < count; i++)
    {
        const w = pool[rng() % pool.length];
        out[i] = { Word: w };
    }
    return out;
}
