import { PenEditorDemoVM } from "./pen-editor-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Ellipse, Line, Orientation, StackPanel, TextBlock } from "@pragmatic-tech-ai/mural/basic";
import { PenEditor } from "@pragmatic-tech-ai/mural/framework";
import { DataContextBinding, DynamicResource, NameScope, ResourceDictionary, Thickness } from "@pragmatic-tech-ai/mural/runtime";
import { FontWeight, Pen } from "@pragmatic-tech-ai/mural/visual-engine";


const _gate_PenEditorDemo = Symbol("PenEditorDemo.ctor");
export class PenEditorDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_PenEditorDemo) {
            throw new Error("PenEditorDemo is private — use PenEditorDemo.Clone()");
        }
    }
    static Clone() {
        const t = new PenEditorDemo(_gate_PenEditorDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.SetNameScope(new NameScope());
            _border1.set_property_value(Border.FillKey, DynamicResource(_border1, "Surface"));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.FillKey, DynamicResource(_border3, "Primary"));
            _border3.set_property_value(Border.PaddingKey, new Thickness(20, 14, 20, 14));
            const _stackPanel4 = new StackPanel();
            _stackPanel4.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock5 = new TextBlock();
            _textBlock5.set_property_value(TextBlock.TextKey, "PowerPoint-style Pen editor");
            _textBlock5.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock5.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock5.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock5, "OnPrimary"));
            _stackPanel4.AddChild(_textBlock5);
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "Inline panel: brush + thickness + dash + cap + join + miter. Edits push live onto the preview Pen.");
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock6.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock6, "OnPrimary"));
            _textBlock6.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _stackPanel4.AddChild(_textBlock6);
            _border3.SetChild(_stackPanel4);
            _dockPanel2.AddChild(_border3);
            const _line7 = new Line();
            _line7.set_property_value(DockPanel.DockKey, Dock.Bottom);
            _line7.set_property_value(Line.OrientationKey, Orientation.Horizontal);
            _line7.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line7, "OutlineVariant"), 1));
            _dockPanel2.AddChild(_line7);
            const _border8 = new Border();
            _border8.set_property_value(DockPanel.DockKey, Dock.Bottom);
            _border8.set_property_value(Border.FillKey, DynamicResource(_border8, "SurfaceContainerLow"));
            _border8.set_property_value(Border.PaddingKey, new Thickness(20, 10, 20, 10));
            const _stackPanel9 = new StackPanel();
            _stackPanel9.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _textBlock10 = new TextBlock();
            _textBlock10.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock10, "BrushSummary"));
            _textBlock10.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock10.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock10, "OnSurfaceVariant"));
            _textBlock10.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 16, 0));
            _stackPanel9.AddChild(_textBlock10);
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock11, "ThicknessReadout"));
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock11.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock11, "OnSurfaceVariant"));
            _textBlock11.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 16, 0));
            _stackPanel9.AddChild(_textBlock11);
            const _textBlock12 = new TextBlock();
            _textBlock12.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock12, "DashReadout"));
            _textBlock12.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock12.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock12, "OnSurfaceVariant"));
            _textBlock12.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 16, 0));
            _stackPanel9.AddChild(_textBlock12);
            const _textBlock13 = new TextBlock();
            _textBlock13.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock13, "CapReadout"));
            _textBlock13.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock13.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock13, "OnSurfaceVariant"));
            _textBlock13.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 16, 0));
            _stackPanel9.AddChild(_textBlock13);
            const _textBlock14 = new TextBlock();
            _textBlock14.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock14, "JoinReadout"));
            _textBlock14.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock14.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock14, "OnSurfaceVariant"));
            _textBlock14.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 16, 0));
            _stackPanel9.AddChild(_textBlock14);
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock15, "MiterReadout"));
            _textBlock15.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock15.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock15, "OnSurfaceVariant"));
            _stackPanel9.AddChild(_textBlock15);
            _border8.SetChild(_stackPanel9);
            _dockPanel2.AddChild(_border8);
            const _border16 = new Border();
            _border16.set_property_value(Border.FillKey, DynamicResource(_border16, "SurfaceContainerLowest"));
            _border16.set_property_value(Border.PaddingKey, new Thickness(20, 20, 20, 20));
            const _stackPanel17 = new StackPanel();
            _stackPanel17.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _border18 = new Border();
            _border18.set_property_value(Border.WidthKey, 320);
            _border18.set_property_value(Border.PaddingKey, new Thickness(16, 16, 16, 16));
            _border18.set_property_value(Border.FillKey, DynamicResource(_border18, "SurfaceContainerLow"));
            _border18.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            _border18.set_property_value(Border.CornerRadiusKey, 8);
            _border18.set_property_value(Border.MarginKey, new Thickness(0, 0, 20, 0));
            const _stackPanel19 = new StackPanel();
            _stackPanel19.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            const _textBlock20 = new TextBlock();
            _textBlock20.set_property_value(TextBlock.TextKey, "Pen");
            _textBlock20.set_property_value(TextBlock.FontSizeKey, 14);
            _textBlock20.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock20.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock20, "OnSurface"));
            _textBlock20.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 12));
            _stackPanel19.AddChild(_textBlock20);
            const _penEditor21 = new PenEditor();
            _penEditor21.set_property_value(PenEditor.PenKey, DataContextBinding(_penEditor21, "Pen"));
            _stackPanel19.AddChild(_penEditor21);
            _border18.SetChild(_stackPanel19);
            _stackPanel17.AddChild(_border18);
            const _border22 = new Border();
            _border22.set_property_value(Border.WidthKey, 520);
            _border22.set_property_value(Border.HeightKey, 420);
            _border22.set_property_value(Border.PaddingKey, new Thickness(20));
            _border22.set_property_value(Border.FillKey, DynamicResource(_border22, "SurfaceContainer"));
            _border22.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            _border22.set_property_value(Border.CornerRadiusKey, 8);
            const _ellipse23 = new Ellipse();
            _ellipse23.set_property_value(Ellipse.WidthKey, 480);
            _ellipse23.set_property_value(Ellipse.HeightKey, 380);
            _ellipse23.set_property_value(Ellipse.StrokeKey, DataContextBinding(_ellipse23, "Pen"));
            _border22.SetChild(_ellipse23);
            _stackPanel17.AddChild(_border22);
            _border16.SetChild(_stackPanel17);
            _dockPanel2.AddChild(_border16);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, PenEditorDemoVM);
        t.Set(PenEditorDemoVM, _tmpl0);
        return t;
    }
}
