import { CommandsVM, EllipseFigure, NoteFigure, RectFigure } from "./commands-vm.mjs";
import { Border, Canvas, DataTemplate, Dock, DockPanel, ItemsPanelTemplate, Line, Orientation, Shape, StackPanel, TargetedSetter, TemplateDataTrigger, TextBlock, UniformGrid } from "@pragmatic-tech-ai/mural/basic";
import { Diagram } from "@pragmatic-tech-ai/mural/framework/diagram/diagram.js";
import { SelectionMode } from "@pragmatic-tech-ai/mural/framework/list/list-box.js";
import { MenuButton, MenuItem, MenuSeparator, Ribbon, RibbonButton, RibbonContextualGroup, RibbonGroup, RibbonSmallButtonColumn, RibbonTab, ToolBar, ToolBarButton, ToolBarSeparator, ToolBarSplitButton } from "@pragmatic-tech-ai/mural/framework/surface.js";
import { Checkbox } from "@pragmatic-tech-ai/mural/framework/toggles/checkbox.js";
import { Color, DataContextBinding, DynamicResource, ElementNameBinding, HorizontalAlignment, PropertyTrigger, ResourceDictionary, Setter, SetterFactory, Style, Thickness, VerticalAlignment, Visibility } from "@pragmatic-tech-ai/mural/runtime";
import { FontWeight, LineSegment, PathFigure, PathGeometry, Pen, Point, QuadraticBezierSegment, SolidColorBrush } from "@pragmatic-tech-ai/mural/visual-engine";


const _gate_CommandsDemo = Symbol("CommandsDemo.ctor");
export class CommandsDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_CommandsDemo) {
            throw new Error("CommandsDemo is private — use CommandsDemo.Clone()");
        }
    }
    static Clone() {
        const t = new CommandsDemo(_gate_CommandsDemo);
        t.Set("save", new PathGeometry([new PathFigure(new Point(680, -840), [new LineSegment(new Point(840, -680)), new LineSegment(new Point(840, -200)), new QuadraticBezierSegment(new Point(840, -167), new Point(816.5, -143.5)), new QuadraticBezierSegment(new Point(793, -120), new Point(760, -120)), new LineSegment(new Point(760, -120)), new LineSegment(new Point(200, -120)), new QuadraticBezierSegment(new Point(167, -120), new Point(143.5, -143.5)), new QuadraticBezierSegment(new Point(120, -167), new Point(120, -200)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(120, -760)), new QuadraticBezierSegment(new Point(120, -793), new Point(143.5, -816.5)), new QuadraticBezierSegment(new Point(167, -840), new Point(200, -840)), new LineSegment(new Point(200, -840)), new LineSegment(new Point(680, -840))], true), new PathFigure(new Point(760, -200), [new LineSegment(new Point(760, -646)), new LineSegment(new Point(646, -760)), new LineSegment(new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new LineSegment(new Point(200, -760)), new LineSegment(new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new LineSegment(new Point(200, -200)), new LineSegment(new Point(760, -200)), new QuadraticBezierSegment(new Point(760, -200), new Point(760, -200)), new QuadraticBezierSegment(new Point(760, -200), new Point(760, -200)), new LineSegment(new Point(760, -200))], true), new PathFigure(new Point(480, -240), [new QuadraticBezierSegment(new Point(530, -240), new Point(565, -275)), new QuadraticBezierSegment(new Point(600, -310), new Point(600, -360)), new QuadraticBezierSegment(new Point(600, -410), new Point(565, -445)), new QuadraticBezierSegment(new Point(530, -480), new Point(480, -480)), new QuadraticBezierSegment(new Point(430, -480), new Point(395, -445)), new QuadraticBezierSegment(new Point(360, -410), new Point(360, -360)), new QuadraticBezierSegment(new Point(360, -310), new Point(395, -275)), new QuadraticBezierSegment(new Point(430, -240), new Point(480, -240))], true), new PathFigure(new Point(240, -720), [new LineSegment(new Point(240, -560)), new LineSegment(new Point(600, -560)), new LineSegment(new Point(600, -720)), new LineSegment(new Point(240, -720))], true), new PathFigure(new Point(200, -760), [new LineSegment(new Point(200, -646)), new LineSegment(new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new LineSegment(new Point(200, -200)), new LineSegment(new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new LineSegment(new Point(200, -200)), new LineSegment(new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new LineSegment(new Point(200, -760)), new LineSegment(new Point(200, -760))], true)]));
        t.Set("content_cut", new PathGeometry([new PathFigure(new Point(880, -120), [new LineSegment(new Point(760, -120)), new LineSegment(new Point(480, -400)), new LineSegment(new Point(386, -306)), new QuadraticBezierSegment(new Point(394, -291), new Point(397, -274)), new QuadraticBezierSegment(new Point(400, -257), new Point(400, -240)), new LineSegment(new Point(400, -240)), new QuadraticBezierSegment(new Point(400, -174), new Point(353, -127)), new QuadraticBezierSegment(new Point(306, -80), new Point(240, -80)), new LineSegment(new Point(240, -80)), new QuadraticBezierSegment(new Point(174, -80), new Point(127, -127)), new QuadraticBezierSegment(new Point(80, -174), new Point(80, -240)), new QuadraticBezierSegment(new Point(80, -306), new Point(127, -353)), new QuadraticBezierSegment(new Point(174, -400), new Point(240, -400)), new LineSegment(new Point(240, -400)), new QuadraticBezierSegment(new Point(257, -400), new Point(274, -397)), new QuadraticBezierSegment(new Point(291, -394), new Point(306, -386)), new LineSegment(new Point(306, -386)), new LineSegment(new Point(400, -480)), new LineSegment(new Point(306, -574)), new QuadraticBezierSegment(new Point(291, -566), new Point(274, -563)), new QuadraticBezierSegment(new Point(257, -560), new Point(240, -560)), new LineSegment(new Point(240, -560)), new QuadraticBezierSegment(new Point(174, -560), new Point(127, -607)), new QuadraticBezierSegment(new Point(80, -654), new Point(80, -720)), new QuadraticBezierSegment(new Point(80, -786), new Point(127, -833)), new QuadraticBezierSegment(new Point(174, -880), new Point(240, -880)), new QuadraticBezierSegment(new Point(306, -880), new Point(353, -833)), new QuadraticBezierSegment(new Point(400, -786), new Point(400, -720)), new LineSegment(new Point(400, -720)), new QuadraticBezierSegment(new Point(400, -703), new Point(397, -686)), new QuadraticBezierSegment(new Point(394, -669), new Point(386, -654)), new LineSegment(new Point(386, -654)), new LineSegment(new Point(880, -160)), new LineSegment(new Point(880, -120))], true), new PathFigure(new Point(880, -800), [new LineSegment(new Point(600, -520)), new LineSegment(new Point(520, -600)), new LineSegment(new Point(760, -840)), new LineSegment(new Point(880, -840)), new LineSegment(new Point(880, -800))], true), new PathFigure(new Point(240, -640), [new QuadraticBezierSegment(new Point(273, -640), new Point(296.5, -663.5)), new QuadraticBezierSegment(new Point(320, -687), new Point(320, -720)), new QuadraticBezierSegment(new Point(320, -753), new Point(296.5, -776.5)), new QuadraticBezierSegment(new Point(273, -800), new Point(240, -800)), new QuadraticBezierSegment(new Point(207, -800), new Point(183.5, -776.5)), new QuadraticBezierSegment(new Point(160, -753), new Point(160, -720)), new QuadraticBezierSegment(new Point(160, -687), new Point(183.5, -663.5)), new QuadraticBezierSegment(new Point(207, -640), new Point(240, -640))], true), new PathFigure(new Point(480, -460), [new QuadraticBezierSegment(new Point(488, -460), new Point(494, -466)), new QuadraticBezierSegment(new Point(500, -472), new Point(500, -480)), new QuadraticBezierSegment(new Point(500, -488), new Point(494, -494)), new QuadraticBezierSegment(new Point(488, -500), new Point(480, -500)), new QuadraticBezierSegment(new Point(472, -500), new Point(466, -494)), new QuadraticBezierSegment(new Point(460, -488), new Point(460, -480)), new QuadraticBezierSegment(new Point(460, -472), new Point(466, -466)), new QuadraticBezierSegment(new Point(472, -460), new Point(480, -460))], true), new PathFigure(new Point(240, -160), [new QuadraticBezierSegment(new Point(273, -160), new Point(296.5, -183.5)), new QuadraticBezierSegment(new Point(320, -207), new Point(320, -240)), new QuadraticBezierSegment(new Point(320, -273), new Point(296.5, -296.5)), new QuadraticBezierSegment(new Point(273, -320), new Point(240, -320)), new QuadraticBezierSegment(new Point(207, -320), new Point(183.5, -296.5)), new QuadraticBezierSegment(new Point(160, -273), new Point(160, -240)), new QuadraticBezierSegment(new Point(160, -207), new Point(183.5, -183.5)), new QuadraticBezierSegment(new Point(207, -160), new Point(240, -160))], true)]));
        t.Set("content_copy", new PathGeometry([new PathFigure(new Point(720, -240), [new LineSegment(new Point(360, -240)), new QuadraticBezierSegment(new Point(327, -240), new Point(303.5, -263.5)), new QuadraticBezierSegment(new Point(280, -287), new Point(280, -320)), new LineSegment(new Point(280, -320)), new LineSegment(new Point(280, -800)), new QuadraticBezierSegment(new Point(280, -833), new Point(303.5, -856.5)), new QuadraticBezierSegment(new Point(327, -880), new Point(360, -880)), new LineSegment(new Point(360, -880)), new LineSegment(new Point(720, -880)), new QuadraticBezierSegment(new Point(753, -880), new Point(776.5, -856.5)), new QuadraticBezierSegment(new Point(800, -833), new Point(800, -800)), new LineSegment(new Point(800, -800)), new LineSegment(new Point(800, -320)), new QuadraticBezierSegment(new Point(800, -287), new Point(776.5, -263.5)), new QuadraticBezierSegment(new Point(753, -240), new Point(720, -240)), new LineSegment(new Point(720, -240))], true), new PathFigure(new Point(360, -320), [new LineSegment(new Point(360, -320)), new LineSegment(new Point(720, -320)), new QuadraticBezierSegment(new Point(720, -320), new Point(720, -320)), new QuadraticBezierSegment(new Point(720, -320), new Point(720, -320)), new LineSegment(new Point(720, -320)), new LineSegment(new Point(720, -800)), new QuadraticBezierSegment(new Point(720, -800), new Point(720, -800)), new QuadraticBezierSegment(new Point(720, -800), new Point(720, -800)), new LineSegment(new Point(720, -800)), new LineSegment(new Point(360, -800)), new QuadraticBezierSegment(new Point(360, -800), new Point(360, -800)), new QuadraticBezierSegment(new Point(360, -800), new Point(360, -800)), new LineSegment(new Point(360, -800)), new LineSegment(new Point(360, -320)), new QuadraticBezierSegment(new Point(360, -320), new Point(360, -320)), new QuadraticBezierSegment(new Point(360, -320), new Point(360, -320))], true), new PathFigure(new Point(640, -80), [new LineSegment(new Point(200, -80)), new QuadraticBezierSegment(new Point(167, -80), new Point(143.5, -103.5)), new QuadraticBezierSegment(new Point(120, -127), new Point(120, -160)), new LineSegment(new Point(120, -160)), new LineSegment(new Point(120, -720)), new LineSegment(new Point(200, -720)), new LineSegment(new Point(200, -160)), new QuadraticBezierSegment(new Point(200, -160), new Point(200, -160)), new QuadraticBezierSegment(new Point(200, -160), new Point(200, -160)), new LineSegment(new Point(200, -160)), new LineSegment(new Point(640, -160)), new LineSegment(new Point(640, -80))], true), new PathFigure(new Point(360, -320), [new LineSegment(new Point(360, -320)), new QuadraticBezierSegment(new Point(360, -320), new Point(360, -320)), new QuadraticBezierSegment(new Point(360, -320), new Point(360, -320)), new LineSegment(new Point(360, -320)), new LineSegment(new Point(360, -800)), new QuadraticBezierSegment(new Point(360, -800), new Point(360, -800)), new QuadraticBezierSegment(new Point(360, -800), new Point(360, -800)), new LineSegment(new Point(360, -800)), new LineSegment(new Point(360, -800)), new QuadraticBezierSegment(new Point(360, -800), new Point(360, -800)), new QuadraticBezierSegment(new Point(360, -800), new Point(360, -800)), new LineSegment(new Point(360, -800)), new LineSegment(new Point(360, -320)), new QuadraticBezierSegment(new Point(360, -320), new Point(360, -320)), new QuadraticBezierSegment(new Point(360, -320), new Point(360, -320)), new LineSegment(new Point(360, -320))], true)]));
        t.Set("content_paste", new PathGeometry([new PathFigure(new Point(760, -120), [new LineSegment(new Point(200, -120)), new QuadraticBezierSegment(new Point(167, -120), new Point(143.5, -143.5)), new QuadraticBezierSegment(new Point(120, -167), new Point(120, -200)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(120, -760)), new QuadraticBezierSegment(new Point(120, -793), new Point(143.5, -816.5)), new QuadraticBezierSegment(new Point(167, -840), new Point(200, -840)), new LineSegment(new Point(200, -840)), new LineSegment(new Point(367, -840)), new QuadraticBezierSegment(new Point(378, -875), new Point(410, -897.5)), new QuadraticBezierSegment(new Point(442, -920), new Point(480, -920)), new LineSegment(new Point(480, -920)), new QuadraticBezierSegment(new Point(520, -920), new Point(551.5, -897.5)), new QuadraticBezierSegment(new Point(583, -875), new Point(594, -840)), new LineSegment(new Point(594, -840)), new LineSegment(new Point(760, -840)), new QuadraticBezierSegment(new Point(793, -840), new Point(816.5, -816.5)), new QuadraticBezierSegment(new Point(840, -793), new Point(840, -760)), new LineSegment(new Point(840, -760)), new LineSegment(new Point(840, -200)), new QuadraticBezierSegment(new Point(840, -167), new Point(816.5, -143.5)), new QuadraticBezierSegment(new Point(793, -120), new Point(760, -120)), new LineSegment(new Point(760, -120))], true), new PathFigure(new Point(200, -200), [new LineSegment(new Point(200, -200)), new LineSegment(new Point(760, -200)), new QuadraticBezierSegment(new Point(760, -200), new Point(760, -200)), new QuadraticBezierSegment(new Point(760, -200), new Point(760, -200)), new LineSegment(new Point(760, -200)), new LineSegment(new Point(760, -760)), new QuadraticBezierSegment(new Point(760, -760), new Point(760, -760)), new QuadraticBezierSegment(new Point(760, -760), new Point(760, -760)), new LineSegment(new Point(760, -760)), new LineSegment(new Point(680, -760)), new LineSegment(new Point(680, -640)), new LineSegment(new Point(280, -640)), new LineSegment(new Point(280, -760)), new LineSegment(new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new LineSegment(new Point(200, -760)), new LineSegment(new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200))], true), new PathFigure(new Point(480, -760), [new QuadraticBezierSegment(new Point(497, -760), new Point(508.5, -771.5)), new QuadraticBezierSegment(new Point(520, -783), new Point(520, -800)), new QuadraticBezierSegment(new Point(520, -817), new Point(508.5, -828.5)), new QuadraticBezierSegment(new Point(497, -840), new Point(480, -840)), new QuadraticBezierSegment(new Point(463, -840), new Point(451.5, -828.5)), new QuadraticBezierSegment(new Point(440, -817), new Point(440, -800)), new QuadraticBezierSegment(new Point(440, -783), new Point(451.5, -771.5)), new QuadraticBezierSegment(new Point(463, -760), new Point(480, -760))], true)]));
        t.Set("delete", new PathGeometry([new PathFigure(new Point(680, -120), [new LineSegment(new Point(280, -120)), new QuadraticBezierSegment(new Point(247, -120), new Point(223.5, -143.5)), new QuadraticBezierSegment(new Point(200, -167), new Point(200, -200)), new LineSegment(new Point(200, -200)), new LineSegment(new Point(200, -720)), new LineSegment(new Point(160, -720)), new LineSegment(new Point(160, -800)), new LineSegment(new Point(360, -800)), new LineSegment(new Point(360, -840)), new LineSegment(new Point(600, -840)), new LineSegment(new Point(600, -800)), new LineSegment(new Point(800, -800)), new LineSegment(new Point(800, -720)), new LineSegment(new Point(760, -720)), new LineSegment(new Point(760, -200)), new QuadraticBezierSegment(new Point(760, -167), new Point(736.5, -143.5)), new QuadraticBezierSegment(new Point(713, -120), new Point(680, -120)), new LineSegment(new Point(680, -120))], true), new PathFigure(new Point(680, -200), [new LineSegment(new Point(680, -720)), new LineSegment(new Point(280, -720)), new LineSegment(new Point(280, -200)), new QuadraticBezierSegment(new Point(280, -200), new Point(280, -200)), new QuadraticBezierSegment(new Point(280, -200), new Point(280, -200)), new LineSegment(new Point(280, -200)), new LineSegment(new Point(680, -200)), new QuadraticBezierSegment(new Point(680, -200), new Point(680, -200)), new QuadraticBezierSegment(new Point(680, -200), new Point(680, -200)), new LineSegment(new Point(680, -200))], true), new PathFigure(new Point(360, -640), [new LineSegment(new Point(360, -280)), new LineSegment(new Point(440, -280)), new LineSegment(new Point(440, -640)), new LineSegment(new Point(360, -640))], true), new PathFigure(new Point(520, -640), [new LineSegment(new Point(520, -280)), new LineSegment(new Point(600, -280)), new LineSegment(new Point(600, -640)), new LineSegment(new Point(520, -640))], true), new PathFigure(new Point(280, -200), [new LineSegment(new Point(280, -720)), new LineSegment(new Point(280, -720)), new LineSegment(new Point(280, -200)), new QuadraticBezierSegment(new Point(280, -200), new Point(280, -200)), new QuadraticBezierSegment(new Point(280, -200), new Point(280, -200)), new LineSegment(new Point(280, -200)), new LineSegment(new Point(280, -200)), new QuadraticBezierSegment(new Point(280, -200), new Point(280, -200)), new QuadraticBezierSegment(new Point(280, -200), new Point(280, -200)), new LineSegment(new Point(280, -200))], true)]));
        t.Set("copy_all", new PathGeometry([new PathFigure(new Point(200, -220), [new LineSegment(new Point(120, -220)), new LineSegment(new Point(120, -300)), new LineSegment(new Point(200, -300)), new LineSegment(new Point(200, -220))], true), new PathFigure(new Point(200, -360), [new LineSegment(new Point(120, -360)), new LineSegment(new Point(120, -440)), new LineSegment(new Point(200, -440)), new LineSegment(new Point(200, -360))], true), new PathFigure(new Point(200, -500), [new LineSegment(new Point(120, -500)), new LineSegment(new Point(120, -580)), new LineSegment(new Point(200, -580)), new LineSegment(new Point(200, -500))], true), new PathFigure(new Point(340, -80), [new LineSegment(new Point(260, -80)), new LineSegment(new Point(260, -160)), new LineSegment(new Point(340, -160)), new LineSegment(new Point(340, -80))], true), new PathFigure(new Point(720, -240), [new LineSegment(new Point(360, -240)), new QuadraticBezierSegment(new Point(327, -240), new Point(303.5, -263.5)), new QuadraticBezierSegment(new Point(280, -287), new Point(280, -320)), new LineSegment(new Point(280, -320)), new LineSegment(new Point(280, -800)), new QuadraticBezierSegment(new Point(280, -833), new Point(303.5, -856.5)), new QuadraticBezierSegment(new Point(327, -880), new Point(360, -880)), new LineSegment(new Point(360, -880)), new LineSegment(new Point(720, -880)), new QuadraticBezierSegment(new Point(753, -880), new Point(776.5, -856.5)), new QuadraticBezierSegment(new Point(800, -833), new Point(800, -800)), new LineSegment(new Point(800, -800)), new LineSegment(new Point(800, -320)), new QuadraticBezierSegment(new Point(800, -287), new Point(776.5, -263.5)), new QuadraticBezierSegment(new Point(753, -240), new Point(720, -240)), new LineSegment(new Point(720, -240))], true), new PathFigure(new Point(360, -320), [new LineSegment(new Point(360, -320)), new LineSegment(new Point(720, -320)), new QuadraticBezierSegment(new Point(720, -320), new Point(720, -320)), new QuadraticBezierSegment(new Point(720, -320), new Point(720, -320)), new LineSegment(new Point(720, -320)), new LineSegment(new Point(720, -800)), new QuadraticBezierSegment(new Point(720, -800), new Point(720, -800)), new QuadraticBezierSegment(new Point(720, -800), new Point(720, -800)), new LineSegment(new Point(720, -800)), new LineSegment(new Point(360, -800)), new QuadraticBezierSegment(new Point(360, -800), new Point(360, -800)), new QuadraticBezierSegment(new Point(360, -800), new Point(360, -800)), new LineSegment(new Point(360, -800)), new LineSegment(new Point(360, -320)), new QuadraticBezierSegment(new Point(360, -320), new Point(360, -320)), new QuadraticBezierSegment(new Point(360, -320), new Point(360, -320))], true), new PathFigure(new Point(480, -80), [new LineSegment(new Point(400, -80)), new LineSegment(new Point(400, -160)), new LineSegment(new Point(480, -160)), new LineSegment(new Point(480, -80))], true), new PathFigure(new Point(200, -160), [new LineSegment(new Point(200, -80)), new QuadraticBezierSegment(new Point(167, -80), new Point(143.5, -103.5)), new QuadraticBezierSegment(new Point(120, -127), new Point(120, -160)), new LineSegment(new Point(120, -160)), new LineSegment(new Point(200, -160))], true), new PathFigure(new Point(540, -80), [new LineSegment(new Point(540, -80)), new LineSegment(new Point(540, -160)), new LineSegment(new Point(620, -160)), new QuadraticBezierSegment(new Point(620, -127), new Point(596.5, -103.5)), new QuadraticBezierSegment(new Point(573, -80), new Point(540, -80))], true), new PathFigure(new Point(200, -640), [new LineSegment(new Point(120, -640)), new QuadraticBezierSegment(new Point(120, -673), new Point(143.5, -696.5)), new QuadraticBezierSegment(new Point(167, -720), new Point(200, -720)), new LineSegment(new Point(200, -720)), new LineSegment(new Point(200, -640))], true), new PathFigure(new Point(540, -560), [new LineSegment(new Point(540, -560)), new QuadraticBezierSegment(new Point(540, -560), new Point(540, -560)), new QuadraticBezierSegment(new Point(540, -560), new Point(540, -560)), new LineSegment(new Point(540, -560)), new LineSegment(new Point(540, -560)), new QuadraticBezierSegment(new Point(540, -560), new Point(540, -560)), new QuadraticBezierSegment(new Point(540, -560), new Point(540, -560)), new LineSegment(new Point(540, -560)), new LineSegment(new Point(540, -560)), new QuadraticBezierSegment(new Point(540, -560), new Point(540, -560)), new QuadraticBezierSegment(new Point(540, -560), new Point(540, -560)), new LineSegment(new Point(540, -560)), new LineSegment(new Point(540, -560)), new QuadraticBezierSegment(new Point(540, -560), new Point(540, -560)), new QuadraticBezierSegment(new Point(540, -560), new Point(540, -560)), new LineSegment(new Point(540, -560))], true)]));
        t.Set("format_align_left", new PathGeometry([new PathFigure(new Point(840, -120), [new LineSegment(new Point(120, -120)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(840, -200)), new LineSegment(new Point(840, -120))], true), new PathFigure(new Point(600, -280), [new LineSegment(new Point(120, -280)), new LineSegment(new Point(120, -360)), new LineSegment(new Point(600, -360)), new LineSegment(new Point(600, -280))], true), new PathFigure(new Point(840, -440), [new LineSegment(new Point(120, -440)), new LineSegment(new Point(120, -520)), new LineSegment(new Point(840, -520)), new LineSegment(new Point(840, -440))], true), new PathFigure(new Point(600, -600), [new LineSegment(new Point(120, -600)), new LineSegment(new Point(120, -680)), new LineSegment(new Point(600, -680)), new LineSegment(new Point(600, -600))], true), new PathFigure(new Point(840, -760), [new LineSegment(new Point(120, -760)), new LineSegment(new Point(120, -840)), new LineSegment(new Point(840, -840)), new LineSegment(new Point(840, -760))], true)]));
        t.Set("format_align_center", new PathGeometry([new PathFigure(new Point(840, -120), [new LineSegment(new Point(120, -120)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(840, -200)), new LineSegment(new Point(840, -120))], true), new PathFigure(new Point(680, -280), [new LineSegment(new Point(280, -280)), new LineSegment(new Point(280, -360)), new LineSegment(new Point(680, -360)), new LineSegment(new Point(680, -280))], true), new PathFigure(new Point(840, -440), [new LineSegment(new Point(120, -440)), new LineSegment(new Point(120, -520)), new LineSegment(new Point(840, -520)), new LineSegment(new Point(840, -440))], true), new PathFigure(new Point(680, -600), [new LineSegment(new Point(280, -600)), new LineSegment(new Point(280, -680)), new LineSegment(new Point(680, -680)), new LineSegment(new Point(680, -600))], true), new PathFigure(new Point(840, -760), [new LineSegment(new Point(120, -760)), new LineSegment(new Point(120, -840)), new LineSegment(new Point(840, -840)), new LineSegment(new Point(840, -760))], true)]));
        t.Set("format_align_right", new PathGeometry([new PathFigure(new Point(840, -760), [new LineSegment(new Point(120, -760)), new LineSegment(new Point(120, -840)), new LineSegment(new Point(840, -840)), new LineSegment(new Point(840, -760))], true), new PathFigure(new Point(840, -600), [new LineSegment(new Point(360, -600)), new LineSegment(new Point(360, -680)), new LineSegment(new Point(840, -680)), new LineSegment(new Point(840, -600))], true), new PathFigure(new Point(840, -440), [new LineSegment(new Point(120, -440)), new LineSegment(new Point(120, -520)), new LineSegment(new Point(840, -520)), new LineSegment(new Point(840, -440))], true), new PathFigure(new Point(840, -280), [new LineSegment(new Point(360, -280)), new LineSegment(new Point(360, -360)), new LineSegment(new Point(840, -360)), new LineSegment(new Point(840, -280))], true), new PathFigure(new Point(840, -120), [new LineSegment(new Point(120, -120)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(840, -200)), new LineSegment(new Point(840, -120))], true)]));
        t.Set("vertical_align_top", new PathGeometry([new PathFigure(new Point(800, -760), [new LineSegment(new Point(160, -760)), new LineSegment(new Point(160, -840)), new LineSegment(new Point(800, -840)), new LineSegment(new Point(800, -760))], true), new PathFigure(new Point(520, -120), [new LineSegment(new Point(440, -120)), new LineSegment(new Point(440, -528)), new LineSegment(new Point(336, -424)), new LineSegment(new Point(280, -480)), new LineSegment(new Point(480, -680)), new LineSegment(new Point(680, -480)), new LineSegment(new Point(624, -424)), new LineSegment(new Point(520, -528)), new LineSegment(new Point(520, -120))], true)]));
        t.Set("vertical_align_center", new PathGeometry([new PathFigure(new Point(520, -80), [new LineSegment(new Point(440, -80)), new LineSegment(new Point(440, -248)), new LineSegment(new Point(376, -184)), new LineSegment(new Point(320, -240)), new LineSegment(new Point(480, -400)), new LineSegment(new Point(640, -240)), new LineSegment(new Point(584, -184)), new LineSegment(new Point(520, -248)), new LineSegment(new Point(520, -80))], true), new PathFigure(new Point(800, -440), [new LineSegment(new Point(160, -440)), new LineSegment(new Point(160, -520)), new LineSegment(new Point(800, -520)), new LineSegment(new Point(800, -440))], true), new PathFigure(new Point(640, -720), [new LineSegment(new Point(480, -560)), new LineSegment(new Point(320, -720)), new LineSegment(new Point(376, -776)), new LineSegment(new Point(440, -712)), new LineSegment(new Point(440, -880)), new LineSegment(new Point(520, -880)), new LineSegment(new Point(520, -712)), new LineSegment(new Point(584, -776)), new LineSegment(new Point(640, -720))], true)]));
        t.Set("vertical_align_bottom", new PathGeometry([new PathFigure(new Point(800, -120), [new LineSegment(new Point(160, -120)), new LineSegment(new Point(160, -200)), new LineSegment(new Point(800, -200)), new LineSegment(new Point(800, -120))], true), new PathFigure(new Point(680, -480), [new LineSegment(new Point(480, -280)), new LineSegment(new Point(280, -480)), new LineSegment(new Point(336, -536)), new LineSegment(new Point(440, -432)), new LineSegment(new Point(440, -840)), new LineSegment(new Point(520, -840)), new LineSegment(new Point(520, -432)), new LineSegment(new Point(624, -536)), new LineSegment(new Point(680, -480))], true)]));
        t.Set("horizontal_distribute", new PathGeometry([new PathFigure(new Point(160, -80), [new LineSegment(new Point(80, -80)), new LineSegment(new Point(80, -880)), new LineSegment(new Point(160, -880)), new LineSegment(new Point(160, -80))], true), new PathFigure(new Point(540, -280), [new LineSegment(new Point(420, -280)), new LineSegment(new Point(420, -680)), new LineSegment(new Point(540, -680)), new LineSegment(new Point(540, -280))], true), new PathFigure(new Point(880, -80), [new LineSegment(new Point(800, -80)), new LineSegment(new Point(800, -880)), new LineSegment(new Point(880, -880)), new LineSegment(new Point(880, -80))], true)]));
        t.Set("vertical_distribute", new PathGeometry([new PathFigure(new Point(880, -80), [new LineSegment(new Point(80, -80)), new LineSegment(new Point(80, -160)), new LineSegment(new Point(880, -160)), new LineSegment(new Point(880, -80))], true), new PathFigure(new Point(680, -420), [new LineSegment(new Point(280, -420)), new LineSegment(new Point(280, -540)), new LineSegment(new Point(680, -540)), new LineSegment(new Point(680, -420))], true), new PathFigure(new Point(880, -800), [new LineSegment(new Point(80, -800)), new LineSegment(new Point(80, -880)), new LineSegment(new Point(880, -880)), new LineSegment(new Point(880, -800))], true)]));
        t.Set("undo", new PathGeometry([new PathFigure(new Point(564, -200), [new LineSegment(new Point(280, -200)), new LineSegment(new Point(280, -280)), new LineSegment(new Point(564, -280)), new QuadraticBezierSegment(new Point(627, -280), new Point(673.5, -320)), new QuadraticBezierSegment(new Point(720, -360), new Point(720, -420)), new QuadraticBezierSegment(new Point(720, -480), new Point(673.5, -520)), new QuadraticBezierSegment(new Point(627, -560), new Point(564, -560)), new LineSegment(new Point(564, -560)), new LineSegment(new Point(312, -560)), new LineSegment(new Point(416, -456)), new LineSegment(new Point(360, -400)), new LineSegment(new Point(160, -600)), new LineSegment(new Point(360, -800)), new LineSegment(new Point(416, -744)), new LineSegment(new Point(312, -640)), new LineSegment(new Point(564, -640)), new QuadraticBezierSegment(new Point(661, -640), new Point(730.5, -577)), new QuadraticBezierSegment(new Point(800, -514), new Point(800, -420)), new QuadraticBezierSegment(new Point(800, -326), new Point(730.5, -263)), new QuadraticBezierSegment(new Point(661, -200), new Point(564, -200)), new LineSegment(new Point(564, -200))], true)]));
        t.Set("redo", new PathGeometry([new PathFigure(new Point(680, -200), [new LineSegment(new Point(396, -200)), new QuadraticBezierSegment(new Point(299, -200), new Point(229.5, -263)), new QuadraticBezierSegment(new Point(160, -326), new Point(160, -420)), new QuadraticBezierSegment(new Point(160, -514), new Point(229.5, -577)), new QuadraticBezierSegment(new Point(299, -640), new Point(396, -640)), new LineSegment(new Point(396, -640)), new LineSegment(new Point(648, -640)), new LineSegment(new Point(544, -744)), new LineSegment(new Point(600, -800)), new LineSegment(new Point(800, -600)), new LineSegment(new Point(600, -400)), new LineSegment(new Point(544, -456)), new LineSegment(new Point(648, -560)), new LineSegment(new Point(396, -560)), new QuadraticBezierSegment(new Point(333, -560), new Point(286.5, -520)), new QuadraticBezierSegment(new Point(240, -480), new Point(240, -420)), new QuadraticBezierSegment(new Point(240, -360), new Point(286.5, -320)), new QuadraticBezierSegment(new Point(333, -280), new Point(396, -280)), new LineSegment(new Point(396, -280)), new LineSegment(new Point(680, -280)), new LineSegment(new Point(680, -200))], true)]));
        t.Set("north_west", new PathGeometry([new PathFigure(new Point(800, -216), [new LineSegment(new Point(744, -160)), new LineSegment(new Point(280, -624)), new LineSegment(new Point(280, -360)), new LineSegment(new Point(200, -360)), new LineSegment(new Point(200, -760)), new LineSegment(new Point(600, -760)), new LineSegment(new Point(600, -680)), new LineSegment(new Point(336, -680)), new LineSegment(new Point(800, -216))], true)]));
        t.Set("north", new PathGeometry([new PathFigure(new Point(520, -80), [new LineSegment(new Point(440, -80)), new LineSegment(new Point(440, -727)), new LineSegment(new Point(256, -544)), new LineSegment(new Point(200, -600)), new LineSegment(new Point(480, -880)), new LineSegment(new Point(760, -600)), new LineSegment(new Point(704, -543)), new LineSegment(new Point(520, -727)), new LineSegment(new Point(520, -80))], true)]));
        t.Set("north_east", new PathGeometry([new PathFigure(new Point(680, -624), [new LineSegment(new Point(216, -160)), new LineSegment(new Point(160, -216)), new LineSegment(new Point(624, -680)), new LineSegment(new Point(360, -680)), new LineSegment(new Point(360, -760)), new LineSegment(new Point(760, -760)), new LineSegment(new Point(760, -360)), new LineSegment(new Point(680, -360)), new LineSegment(new Point(680, -624))], true)]));
        t.Set("west", new PathGeometry([new PathFigure(new Point(417, -256), [new LineSegment(new Point(360, -200)), new LineSegment(new Point(80, -480)), new LineSegment(new Point(360, -760)), new LineSegment(new Point(416, -704)), new LineSegment(new Point(233, -520)), new LineSegment(new Point(880, -520)), new LineSegment(new Point(880, -440)), new LineSegment(new Point(233, -440)), new LineSegment(new Point(417, -256))], true)]));
        t.Set("filter_center_focus", new PathGeometry([new PathFigure(new Point(480, -360), [new QuadraticBezierSegment(new Point(430, -360), new Point(395, -395)), new QuadraticBezierSegment(new Point(360, -430), new Point(360, -480)), new QuadraticBezierSegment(new Point(360, -530), new Point(395, -565)), new QuadraticBezierSegment(new Point(430, -600), new Point(480, -600)), new QuadraticBezierSegment(new Point(530, -600), new Point(565, -565)), new QuadraticBezierSegment(new Point(600, -530), new Point(600, -480)), new QuadraticBezierSegment(new Point(600, -430), new Point(565, -395)), new QuadraticBezierSegment(new Point(530, -360), new Point(480, -360))], true), new PathFigure(new Point(480, -440), [new QuadraticBezierSegment(new Point(497, -440), new Point(508.5, -451.5)), new QuadraticBezierSegment(new Point(520, -463), new Point(520, -480)), new QuadraticBezierSegment(new Point(520, -497), new Point(508.5, -508.5)), new QuadraticBezierSegment(new Point(497, -520), new Point(480, -520)), new QuadraticBezierSegment(new Point(463, -520), new Point(451.5, -508.5)), new QuadraticBezierSegment(new Point(440, -497), new Point(440, -480)), new QuadraticBezierSegment(new Point(440, -463), new Point(451.5, -451.5)), new QuadraticBezierSegment(new Point(463, -440), new Point(480, -440))], true), new PathFigure(new Point(360, -120), [new LineSegment(new Point(200, -120)), new QuadraticBezierSegment(new Point(167, -120), new Point(143.5, -143.5)), new QuadraticBezierSegment(new Point(120, -167), new Point(120, -200)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(120, -360)), new LineSegment(new Point(200, -360)), new LineSegment(new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new LineSegment(new Point(200, -200)), new LineSegment(new Point(360, -200)), new LineSegment(new Point(360, -120))], true), new PathFigure(new Point(760, -120), [new LineSegment(new Point(600, -120)), new LineSegment(new Point(600, -200)), new LineSegment(new Point(760, -200)), new QuadraticBezierSegment(new Point(760, -200), new Point(760, -200)), new QuadraticBezierSegment(new Point(760, -200), new Point(760, -200)), new LineSegment(new Point(760, -200)), new LineSegment(new Point(760, -360)), new LineSegment(new Point(840, -360)), new LineSegment(new Point(840, -200)), new QuadraticBezierSegment(new Point(840, -167), new Point(816.5, -143.5)), new QuadraticBezierSegment(new Point(793, -120), new Point(760, -120)), new LineSegment(new Point(760, -120))], true), new PathFigure(new Point(200, -600), [new LineSegment(new Point(120, -600)), new LineSegment(new Point(120, -760)), new QuadraticBezierSegment(new Point(120, -793), new Point(143.5, -816.5)), new QuadraticBezierSegment(new Point(167, -840), new Point(200, -840)), new LineSegment(new Point(200, -840)), new LineSegment(new Point(360, -840)), new LineSegment(new Point(360, -760)), new LineSegment(new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new LineSegment(new Point(200, -760)), new LineSegment(new Point(200, -600))], true), new PathFigure(new Point(840, -600), [new LineSegment(new Point(760, -600)), new LineSegment(new Point(760, -760)), new QuadraticBezierSegment(new Point(760, -760), new Point(760, -760)), new QuadraticBezierSegment(new Point(760, -760), new Point(760, -760)), new LineSegment(new Point(760, -760)), new LineSegment(new Point(600, -760)), new LineSegment(new Point(600, -840)), new LineSegment(new Point(760, -840)), new QuadraticBezierSegment(new Point(793, -840), new Point(816.5, -816.5)), new QuadraticBezierSegment(new Point(840, -793), new Point(840, -760)), new LineSegment(new Point(840, -760)), new LineSegment(new Point(840, -600))], true)]));
        t.Set("east", new PathGeometry([new PathFigure(new Point(880, -480), [new LineSegment(new Point(600, -200)), new LineSegment(new Point(543, -256)), new LineSegment(new Point(727, -440)), new LineSegment(new Point(80, -440)), new LineSegment(new Point(80, -520)), new LineSegment(new Point(727, -520)), new LineSegment(new Point(544, -704)), new LineSegment(new Point(600, -760)), new LineSegment(new Point(880, -480))], true)]));
        t.Set("south_west", new PathGeometry([new PathFigure(new Point(600, -200), [new LineSegment(new Point(200, -200)), new LineSegment(new Point(200, -600)), new LineSegment(new Point(280, -600)), new LineSegment(new Point(280, -336)), new LineSegment(new Point(744, -800)), new LineSegment(new Point(800, -744)), new LineSegment(new Point(336, -280)), new LineSegment(new Point(600, -280)), new LineSegment(new Point(600, -200))], true)]));
        t.Set("south", new PathGeometry([new PathFigure(new Point(760, -360), [new LineSegment(new Point(480, -80)), new LineSegment(new Point(200, -360)), new LineSegment(new Point(256, -416)), new LineSegment(new Point(440, -233)), new LineSegment(new Point(440, -880)), new LineSegment(new Point(520, -880)), new LineSegment(new Point(520, -233)), new LineSegment(new Point(704, -417)), new LineSegment(new Point(760, -360))], true)]));
        t.Set("south_east", new PathGeometry([new PathFigure(new Point(760, -200), [new LineSegment(new Point(360, -200)), new LineSegment(new Point(360, -280)), new LineSegment(new Point(624, -280)), new LineSegment(new Point(160, -744)), new LineSegment(new Point(216, -800)), new LineSegment(new Point(680, -336)), new LineSegment(new Point(680, -600)), new LineSegment(new Point(760, -600)), new LineSegment(new Point(760, -200))], true)]));
        const _stackPanel0 = new StackPanel();
        _stackPanel0.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
        _stackPanel0.set_property_value(StackPanel.VerticalAlignmentKey, VerticalAlignment.Center);
        const _shape1 = new Shape();
        _shape1.set_property_value(Shape.GeometryKey, DynamicResource(_shape1, "format_align_left"));
        _shape1.set_property_value(Shape.WidthKey, 16);
        _shape1.set_property_value(Shape.HeightKey, 16);
        _shape1.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
        _stackPanel0.AddChild(_shape1);
        const _textBlock2 = new TextBlock();
        _textBlock2.set_property_value(TextBlock.TextKey, "Align");
        _textBlock2.set_property_value(TextBlock.MarginKey, new Thickness(6, 0, 0, 0));
        _textBlock2.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
        _stackPanel0.AddChild(_textBlock2);
        t.Set("AlignSplitLabel", _stackPanel0);
        const _stackPanel3 = new StackPanel();
        _stackPanel3.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
        _stackPanel3.set_property_value(StackPanel.VerticalAlignmentKey, VerticalAlignment.Center);
        const _shape4 = new Shape();
        _shape4.set_property_value(Shape.GeometryKey, DynamicResource(_shape4, "filter_center_focus"));
        _shape4.set_property_value(Shape.WidthKey, 16);
        _shape4.set_property_value(Shape.HeightKey, 16);
        _shape4.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
        _stackPanel3.AddChild(_shape4);
        const _textBlock5 = new TextBlock();
        _textBlock5.set_property_value(TextBlock.TextKey, "Placement");
        _textBlock5.set_property_value(TextBlock.MarginKey, new Thickness(6, 0, 0, 0));
        _textBlock5.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
        _stackPanel3.AddChild(_textBlock5);
        t.Set("PlacementSplitLabel", _stackPanel3);
        const _tmpl6 = new ItemsPanelTemplate(() => {
            const _uniformGrid7 = new UniformGrid();
            _uniformGrid7.set_property_value(UniformGrid.ColumnsKey, 3);
            return _uniformGrid7;
        });
        t.Set("PlacementGrid", _tmpl6);
        const _tmpl8 = new ItemsPanelTemplate(() => {
            const _canvas9 = new Canvas();
            return _canvas9;
        });
        t.Set("CommandsCanvasPanel", _tmpl8);
        const _pen10 = new Pen();
        _pen10.set_property_value(Pen.BrushKey, new SolidColorBrush(Color.FromHex('#f97316')));
        _pen10.set_property_value(Pen.ThicknessKey, 2);
        t.Set("CommandsSelectedPen", _pen10);
        const _setter11 = new Setter(RectFigure, "Stroke", new SetterFactory((_t) => DynamicResource(_t, "CommandsSelectedPen")));
        const _sArr12 = [_setter11];
        const _trigger13 = new PropertyTrigger(RectFigure, "IsSelected", true, _sArr12);
        const _style14 = new Style(RectFigure, [], undefined, [_trigger13], []);
        t.Set(RectFigure, _style14);
        const _setter15 = new Setter(EllipseFigure, "Stroke", new SetterFactory((_t) => DynamicResource(_t, "CommandsSelectedPen")));
        const _sArr16 = [_setter15];
        const _trigger17 = new PropertyTrigger(EllipseFigure, "IsSelected", true, _sArr16);
        const _style18 = new Style(EllipseFigure, [], undefined, [_trigger17], []);
        t.Set(EllipseFigure, _style18);
        const _setter19 = new Setter(NoteFigure, "Stroke", new SetterFactory((_t) => DynamicResource(_t, "CommandsSelectedPen")));
        const _sArr20 = [_setter19];
        const _trigger21 = new PropertyTrigger(NoteFigure, "IsSelected", true, _sArr20);
        const _style22 = new Style(NoteFigure, [], undefined, [_trigger21], []);
        t.Set(NoteFigure, _style22);
        const _tmpl23 = (() => {
            const _factory = (_data) => {
                let _stackPanel24, _border25, _diagram26;
                const _border27 = new Border();
                _border27.set_property_value(Border.FillKey, DynamicResource(_border27, "Surface"));
                _border27.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
                const _dockPanel28 = new DockPanel();
                const _border29 = new Border();
                _border29.set_property_value(DockPanel.DockKey, Dock.Top);
                _border29.set_property_value(Border.FillKey, DynamicResource(_border29, "Primary"));
                _border29.set_property_value(Border.PaddingKey, new Thickness(16, 10, 16, 10));
                const _dockPanel30 = new DockPanel();
                _dockPanel30.set_property_value(DockPanel.LastChildFillKey, true);
                const _checkbox31 = new Checkbox();
                _checkbox31.set_property_value(DockPanel.DockKey, Dock.Right);
                _checkbox31.set_property_value(Checkbox.ContentKey, "Ribbon mode");
                _checkbox31.set_property_value(Checkbox.IsCheckedKey, DataContextBinding(_checkbox31, "IsRibbonMode"));
                _dockPanel30.AddChild(_checkbox31);
                const _textBlock32 = new TextBlock();
                _textBlock32.set_property_value(TextBlock.TextKey, "Menu + ToolBar + ContextMenu (Classic) or a tabbed Ribbon over one shared ICommand catalog. Select nodes to reveal the contextual Format tab.");
                _textBlock32.set_property_value(TextBlock.FontSizeKey, 14);
                _textBlock32.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
                _textBlock32.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock32, "OnPrimary"));
                _textBlock32.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
                _dockPanel30.AddChild(_textBlock32);
                _border29.SetChild(_dockPanel30);
                _dockPanel28.AddChild(_border29);
                _stackPanel24 = new StackPanel();
                _stackPanel24.Name = "ClassicChrome";
                _stackPanel24.set_property_value(DockPanel.DockKey, Dock.Top);
                _stackPanel24.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
                const _border33 = new Border();
                _border33.set_property_value(Border.FillKey, DynamicResource(_border33, "SurfaceContainerLow"));
                _border33.set_property_value(Border.PaddingKey, new Thickness(8, 6, 8, 6));
                const _dockPanel34 = new DockPanel();
                const _line35 = new Line();
                _line35.set_property_value(DockPanel.DockKey, Dock.Bottom);
                _line35.set_property_value(Line.OrientationKey, Orientation.Horizontal);
                _line35.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line35, "OutlineVariant"), 1));
                _dockPanel34.AddChild(_line35);
                const _stackPanel36 = new StackPanel();
                _stackPanel36.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
                const _menuButton37 = new MenuButton();
                _menuButton37.set_property_value(MenuButton.HeaderKey, "☰  File");
                _menuButton37.set_property_value(MenuButton.MarginKey, new Thickness(0, 0, 8, 0));
                _menuButton37.set_property_value(MenuButton.ItemsSourceKey, DataContextBinding(_menuButton37, "Roots"));
                _menuButton37.set_property_value(MenuButton.ItemTemplateKey, DynamicResource(_menuButton37, "CommandMenuItemTemplate"));
                _stackPanel36.AddChild(_menuButton37);
                const _textBlock38 = new TextBlock();
                _textBlock38.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock38, "Status"));
                _textBlock38.set_property_value(TextBlock.FontSizeKey, 12);
                _textBlock38.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock38, "OnSurface"));
                _textBlock38.set_property_value(TextBlock.MarginKey, new Thickness(12, 8, 0, 0));
                _stackPanel36.AddChild(_textBlock38);
                _dockPanel34.AddChild(_stackPanel36);
                _border33.SetChild(_dockPanel34);
                _stackPanel24.AddChild(_border33);
                const _border39 = new Border();
                _border39.set_property_value(DockPanel.DockKey, Dock.Top);
                _border39.set_property_value(Border.FillKey, DynamicResource(_border39, "Surface"));
                const _dockPanel40 = new DockPanel();
                const _line41 = new Line();
                _line41.set_property_value(DockPanel.DockKey, Dock.Bottom);
                _line41.set_property_value(Line.OrientationKey, Orientation.Horizontal);
                _line41.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line41, "OutlineVariant"), 1));
                _dockPanel40.AddChild(_line41);
                const _toolBar42 = new ToolBar();
                const _toolBarButton43 = new ToolBarButton();
                _toolBarButton43.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton43, "SaveCommand"));
                const _shape44 = new Shape();
                _shape44.set_property_value(Shape.GeometryKey, DynamicResource(_shape44, "save"));
                _shape44.set_property_value(Shape.WidthKey, 16);
                _shape44.set_property_value(Shape.HeightKey, 16);
                _shape44.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton43.Content = _shape44;
                _toolBar42.AddChild(_toolBarButton43);
                const _toolBarSeparator45 = new ToolBarSeparator();
                _toolBar42.AddChild(_toolBarSeparator45);
                const _toolBarButton46 = new ToolBarButton();
                _toolBarButton46.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton46, "CutCommand"));
                const _shape47 = new Shape();
                _shape47.set_property_value(Shape.GeometryKey, DynamicResource(_shape47, "content_cut"));
                _shape47.set_property_value(Shape.WidthKey, 16);
                _shape47.set_property_value(Shape.HeightKey, 16);
                _shape47.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton46.Content = _shape47;
                _toolBar42.AddChild(_toolBarButton46);
                const _toolBarButton48 = new ToolBarButton();
                _toolBarButton48.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton48, "CopyCommand"));
                const _shape49 = new Shape();
                _shape49.set_property_value(Shape.GeometryKey, DynamicResource(_shape49, "content_copy"));
                _shape49.set_property_value(Shape.WidthKey, 16);
                _shape49.set_property_value(Shape.HeightKey, 16);
                _shape49.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton48.Content = _shape49;
                _toolBar42.AddChild(_toolBarButton48);
                const _toolBarButton50 = new ToolBarButton();
                _toolBarButton50.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton50, "PasteCommand"));
                const _shape51 = new Shape();
                _shape51.set_property_value(Shape.GeometryKey, DynamicResource(_shape51, "content_paste"));
                _shape51.set_property_value(Shape.WidthKey, 16);
                _shape51.set_property_value(Shape.HeightKey, 16);
                _shape51.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton50.Content = _shape51;
                _toolBar42.AddChild(_toolBarButton50);
                const _toolBarButton52 = new ToolBarButton();
                _toolBarButton52.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton52, "DeleteCommand"));
                const _shape53 = new Shape();
                _shape53.set_property_value(Shape.GeometryKey, DynamicResource(_shape53, "delete"));
                _shape53.set_property_value(Shape.WidthKey, 16);
                _shape53.set_property_value(Shape.HeightKey, 16);
                _shape53.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton52.Content = _shape53;
                _toolBar42.AddChild(_toolBarButton52);
                const _toolBarButton54 = new ToolBarButton();
                _toolBarButton54.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton54, "DuplicateCommand"));
                const _shape55 = new Shape();
                _shape55.set_property_value(Shape.GeometryKey, DynamicResource(_shape55, "copy_all"));
                _shape55.set_property_value(Shape.WidthKey, 16);
                _shape55.set_property_value(Shape.HeightKey, 16);
                _shape55.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton54.Content = _shape55;
                _toolBar42.AddChild(_toolBarButton54);
                const _toolBarSeparator56 = new ToolBarSeparator();
                _toolBar42.AddChild(_toolBarSeparator56);
                const _toolBarButton57 = new ToolBarButton();
                _toolBarButton57.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton57, "AlignLeftCommand"));
                const _shape58 = new Shape();
                _shape58.set_property_value(Shape.GeometryKey, DynamicResource(_shape58, "format_align_left"));
                _shape58.set_property_value(Shape.WidthKey, 16);
                _shape58.set_property_value(Shape.HeightKey, 16);
                _shape58.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton57.Content = _shape58;
                _toolBar42.AddChild(_toolBarButton57);
                const _toolBarButton59 = new ToolBarButton();
                _toolBarButton59.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton59, "AlignCenterCommand"));
                const _shape60 = new Shape();
                _shape60.set_property_value(Shape.GeometryKey, DynamicResource(_shape60, "format_align_center"));
                _shape60.set_property_value(Shape.WidthKey, 16);
                _shape60.set_property_value(Shape.HeightKey, 16);
                _shape60.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton59.Content = _shape60;
                _toolBar42.AddChild(_toolBarButton59);
                const _toolBarButton61 = new ToolBarButton();
                _toolBarButton61.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton61, "AlignRightCommand"));
                const _shape62 = new Shape();
                _shape62.set_property_value(Shape.GeometryKey, DynamicResource(_shape62, "format_align_right"));
                _shape62.set_property_value(Shape.WidthKey, 16);
                _shape62.set_property_value(Shape.HeightKey, 16);
                _shape62.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton61.Content = _shape62;
                _toolBar42.AddChild(_toolBarButton61);
                const _toolBarSeparator63 = new ToolBarSeparator();
                _toolBar42.AddChild(_toolBarSeparator63);
                const _toolBarButton64 = new ToolBarButton();
                _toolBarButton64.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton64, "AlignTopCommand"));
                const _shape65 = new Shape();
                _shape65.set_property_value(Shape.GeometryKey, DynamicResource(_shape65, "vertical_align_top"));
                _shape65.set_property_value(Shape.WidthKey, 16);
                _shape65.set_property_value(Shape.HeightKey, 16);
                _shape65.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton64.Content = _shape65;
                _toolBar42.AddChild(_toolBarButton64);
                const _toolBarButton66 = new ToolBarButton();
                _toolBarButton66.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton66, "AlignMiddleCommand"));
                const _shape67 = new Shape();
                _shape67.set_property_value(Shape.GeometryKey, DynamicResource(_shape67, "vertical_align_center"));
                _shape67.set_property_value(Shape.WidthKey, 16);
                _shape67.set_property_value(Shape.HeightKey, 16);
                _shape67.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton66.Content = _shape67;
                _toolBar42.AddChild(_toolBarButton66);
                const _toolBarButton68 = new ToolBarButton();
                _toolBarButton68.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton68, "AlignBottomCommand"));
                const _shape69 = new Shape();
                _shape69.set_property_value(Shape.GeometryKey, DynamicResource(_shape69, "vertical_align_bottom"));
                _shape69.set_property_value(Shape.WidthKey, 16);
                _shape69.set_property_value(Shape.HeightKey, 16);
                _shape69.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton68.Content = _shape69;
                _toolBar42.AddChild(_toolBarButton68);
                const _toolBarSeparator70 = new ToolBarSeparator();
                _toolBar42.AddChild(_toolBarSeparator70);
                const _toolBarButton71 = new ToolBarButton();
                _toolBarButton71.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton71, "UndoCommand"));
                const _shape72 = new Shape();
                _shape72.set_property_value(Shape.GeometryKey, DynamicResource(_shape72, "undo"));
                _shape72.set_property_value(Shape.WidthKey, 16);
                _shape72.set_property_value(Shape.HeightKey, 16);
                _shape72.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton71.Content = _shape72;
                _toolBar42.AddChild(_toolBarButton71);
                const _toolBarButton73 = new ToolBarButton();
                _toolBarButton73.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton73, "RedoCommand"));
                const _shape74 = new Shape();
                _shape74.set_property_value(Shape.GeometryKey, DynamicResource(_shape74, "redo"));
                _shape74.set_property_value(Shape.WidthKey, 16);
                _shape74.set_property_value(Shape.HeightKey, 16);
                _shape74.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton73.Content = _shape74;
                _toolBar42.AddChild(_toolBarButton73);
                const _toolBarSeparator75 = new ToolBarSeparator();
                _toolBar42.AddChild(_toolBarSeparator75);
                const _toolBarSplitButton76 = new ToolBarSplitButton();
                _toolBarSplitButton76.set_property_value(ToolBarSplitButton.CommandKey, DataContextBinding(_toolBarSplitButton76, "AlignLeftCommand"));
                _toolBarSplitButton76.set_property_value(ToolBarSplitButton.ContentKey, DynamicResource(_toolBarSplitButton76, "AlignSplitLabel"));
                const _menuItem77 = new MenuItem();
                _menuItem77.set_property_value(MenuItem.HeaderKey, "Align Left");
                _menuItem77.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem77, "AlignLeftCommand"));
                _menuItem77.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "format_align_left"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
                _toolBarSplitButton76.AddChild(_menuItem77);
                const _menuItem78 = new MenuItem();
                _menuItem78.set_property_value(MenuItem.HeaderKey, "Align Center");
                _menuItem78.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem78, "AlignCenterCommand"));
                _menuItem78.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "format_align_center"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
                _toolBarSplitButton76.AddChild(_menuItem78);
                const _menuItem79 = new MenuItem();
                _menuItem79.set_property_value(MenuItem.HeaderKey, "Align Right");
                _menuItem79.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem79, "AlignRightCommand"));
                _menuItem79.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "format_align_right"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
                _toolBarSplitButton76.AddChild(_menuItem79);
                const _menuItem80 = new MenuItem();
                _menuItem80.set_property_value(MenuItem.HeaderKey, "Align Top");
                _menuItem80.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem80, "AlignTopCommand"));
                _menuItem80.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "vertical_align_top"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
                _toolBarSplitButton76.AddChild(_menuItem80);
                const _menuItem81 = new MenuItem();
                _menuItem81.set_property_value(MenuItem.HeaderKey, "Align Middle");
                _menuItem81.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem81, "AlignMiddleCommand"));
                _menuItem81.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "vertical_align_center"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
                _toolBarSplitButton76.AddChild(_menuItem81);
                const _menuSeparator82 = new MenuSeparator();
                _toolBarSplitButton76.AddChild(_menuSeparator82);
                const _menuItem83 = new MenuItem();
                _menuItem83.set_property_value(MenuItem.HeaderKey, "Distribute Horizontally");
                _menuItem83.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem83, "DistributeHorizontalCommand"));
                _menuItem83.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "horizontal_distribute"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
                _toolBarSplitButton76.AddChild(_menuItem83);
                const _menuItem84 = new MenuItem();
                _menuItem84.set_property_value(MenuItem.HeaderKey, "Distribute Vertically");
                _menuItem84.set_property_value(MenuItem.CommandKey, DataContextBinding(_menuItem84, "DistributeVerticalCommand"));
                _menuItem84.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "vertical_distribute"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
                _toolBarSplitButton76.AddChild(_menuItem84);
                _toolBar42.AddChild(_toolBarSplitButton76);
                const _toolBarSeparator85 = new ToolBarSeparator();
                _toolBar42.AddChild(_toolBarSeparator85);
                const _toolBarSplitButton86 = new ToolBarSplitButton();
                _toolBarSplitButton86.set_property_value(ToolBarSplitButton.ContentKey, DynamicResource(_toolBarSplitButton86, "PlacementSplitLabel"));
                _toolBarSplitButton86.set_property_value(ToolBarSplitButton.ItemsPanelKey, _tmpl6);
                const _toolBarButton87 = new ToolBarButton();
                _toolBarButton87.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram26, "SetTextPlacementTopLeftCommand"));
                const _shape88 = new Shape();
                _shape88.set_property_value(Shape.GeometryKey, DynamicResource(_shape88, "north_west"));
                _shape88.set_property_value(Shape.WidthKey, 16);
                _shape88.set_property_value(Shape.HeightKey, 16);
                _shape88.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton87.Content = _shape88;
                _toolBarSplitButton86.AddChild(_toolBarButton87);
                const _toolBarButton89 = new ToolBarButton();
                _toolBarButton89.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram26, "SetTextPlacementTopCommand"));
                const _shape90 = new Shape();
                _shape90.set_property_value(Shape.GeometryKey, DynamicResource(_shape90, "north"));
                _shape90.set_property_value(Shape.WidthKey, 16);
                _shape90.set_property_value(Shape.HeightKey, 16);
                _shape90.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton89.Content = _shape90;
                _toolBarSplitButton86.AddChild(_toolBarButton89);
                const _toolBarButton91 = new ToolBarButton();
                _toolBarButton91.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram26, "SetTextPlacementTopRightCommand"));
                const _shape92 = new Shape();
                _shape92.set_property_value(Shape.GeometryKey, DynamicResource(_shape92, "north_east"));
                _shape92.set_property_value(Shape.WidthKey, 16);
                _shape92.set_property_value(Shape.HeightKey, 16);
                _shape92.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton91.Content = _shape92;
                _toolBarSplitButton86.AddChild(_toolBarButton91);
                const _toolBarButton93 = new ToolBarButton();
                _toolBarButton93.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram26, "SetTextPlacementLeftCommand"));
                const _shape94 = new Shape();
                _shape94.set_property_value(Shape.GeometryKey, DynamicResource(_shape94, "west"));
                _shape94.set_property_value(Shape.WidthKey, 16);
                _shape94.set_property_value(Shape.HeightKey, 16);
                _shape94.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton93.Content = _shape94;
                _toolBarSplitButton86.AddChild(_toolBarButton93);
                const _toolBarButton95 = new ToolBarButton();
                _toolBarButton95.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram26, "SetTextPlacementCenterCommand"));
                const _shape96 = new Shape();
                _shape96.set_property_value(Shape.GeometryKey, DynamicResource(_shape96, "filter_center_focus"));
                _shape96.set_property_value(Shape.WidthKey, 16);
                _shape96.set_property_value(Shape.HeightKey, 16);
                _shape96.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton95.Content = _shape96;
                _toolBarSplitButton86.AddChild(_toolBarButton95);
                const _toolBarButton97 = new ToolBarButton();
                _toolBarButton97.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram26, "SetTextPlacementRightCommand"));
                const _shape98 = new Shape();
                _shape98.set_property_value(Shape.GeometryKey, DynamicResource(_shape98, "east"));
                _shape98.set_property_value(Shape.WidthKey, 16);
                _shape98.set_property_value(Shape.HeightKey, 16);
                _shape98.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton97.Content = _shape98;
                _toolBarSplitButton86.AddChild(_toolBarButton97);
                const _toolBarButton99 = new ToolBarButton();
                _toolBarButton99.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram26, "SetTextPlacementBottomLeftCommand"));
                const _shape100 = new Shape();
                _shape100.set_property_value(Shape.GeometryKey, DynamicResource(_shape100, "south_west"));
                _shape100.set_property_value(Shape.WidthKey, 16);
                _shape100.set_property_value(Shape.HeightKey, 16);
                _shape100.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton99.Content = _shape100;
                _toolBarSplitButton86.AddChild(_toolBarButton99);
                const _toolBarButton101 = new ToolBarButton();
                _toolBarButton101.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram26, "SetTextPlacementBottomCommand"));
                const _shape102 = new Shape();
                _shape102.set_property_value(Shape.GeometryKey, DynamicResource(_shape102, "south"));
                _shape102.set_property_value(Shape.WidthKey, 16);
                _shape102.set_property_value(Shape.HeightKey, 16);
                _shape102.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton101.Content = _shape102;
                _toolBarSplitButton86.AddChild(_toolBarButton101);
                const _toolBarButton103 = new ToolBarButton();
                _toolBarButton103.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram26, "SetTextPlacementBottomRightCommand"));
                const _shape104 = new Shape();
                _shape104.set_property_value(Shape.GeometryKey, DynamicResource(_shape104, "south_east"));
                _shape104.set_property_value(Shape.WidthKey, 16);
                _shape104.set_property_value(Shape.HeightKey, 16);
                _shape104.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
                _toolBarButton103.Content = _shape104;
                _toolBarSplitButton86.AddChild(_toolBarButton103);
                _toolBar42.AddChild(_toolBarSplitButton86);
                _dockPanel40.AddChild(_toolBar42);
                _border39.SetChild(_dockPanel40);
                _stackPanel24.AddChild(_border39);
                _dockPanel28.AddChild(_stackPanel24);
                _border25 = new Border();
                _border25.Name = "RibbonChrome";
                _border25.set_property_value(DockPanel.DockKey, Dock.Top);
                _border25.set_property_value(Border.VisibilityKey, Visibility.Collapsed);
                const _ribbon105 = new Ribbon();
                const _ribbonTab106 = new RibbonTab();
                _ribbonTab106.set_property_value(RibbonTab.HeaderKey, "Home");
                const _ribbonGroup107 = new RibbonGroup();
                _ribbonGroup107.set_property_value(RibbonGroup.HeaderKey, "Clipboard");
                const _ribbonButton108 = new RibbonButton();
                _ribbonButton108.set_property_value(RibbonButton.TextKey, "✂ Cut");
                _ribbonButton108.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton108, "CutCommand"));
                _ribbonGroup107.AddChild(_ribbonButton108);
                const _ribbonButton109 = new RibbonButton();
                _ribbonButton109.set_property_value(RibbonButton.TextKey, "📋 Copy");
                _ribbonButton109.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton109, "CopyCommand"));
                _ribbonGroup107.AddChild(_ribbonButton109);
                const _ribbonButton110 = new RibbonButton();
                _ribbonButton110.set_property_value(RibbonButton.TextKey, "📄 Paste");
                _ribbonButton110.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton110, "PasteCommand"));
                _ribbonGroup107.AddChild(_ribbonButton110);
                _ribbonTab106.AddChild(_ribbonGroup107);
                const _ribbonGroup111 = new RibbonGroup();
                _ribbonGroup111.set_property_value(RibbonGroup.HeaderKey, "File");
                _ribbonGroup111.set_property_value(RibbonGroup.LaunchCommandKey, DataContextBinding(_ribbonGroup111, "SaveCommand"));
                const _ribbonButton112 = new RibbonButton();
                _ribbonButton112.set_property_value(RibbonButton.TextKey, "💾 Save");
                _ribbonButton112.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton112, "SaveCommand"));
                _ribbonGroup111.AddChild(_ribbonButton112);
                const _ribbonButton113 = new RibbonButton();
                _ribbonButton113.set_property_value(RibbonButton.TextKey, "📂 Load");
                _ribbonButton113.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton113, "LoadCommand"));
                _ribbonGroup111.AddChild(_ribbonButton113);
                _ribbonTab106.AddChild(_ribbonGroup111);
                _ribbon105.AddChild(_ribbonTab106);
                const _ribbonTab114 = new RibbonTab();
                _ribbonTab114.set_property_value(RibbonTab.HeaderKey, "Insert");
                const _ribbonGroup115 = new RibbonGroup();
                _ribbonGroup115.set_property_value(RibbonGroup.HeaderKey, "Nodes");
                const _ribbonButton116 = new RibbonButton();
                _ribbonButton116.set_property_value(RibbonButton.TextKey, "⎘ Duplicate");
                _ribbonButton116.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton116, "DuplicateCommand"));
                _ribbonGroup115.AddChild(_ribbonButton116);
                const _ribbonButton117 = new RibbonButton();
                _ribbonButton117.set_property_value(RibbonButton.TextKey, "Select All");
                _ribbonButton117.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton117, "SelectAllCommand"));
                _ribbonGroup115.AddChild(_ribbonButton117);
                _ribbonTab114.AddChild(_ribbonGroup115);
                _ribbon105.AddChild(_ribbonTab114);
                const _ribbonTab118 = new RibbonTab();
                _ribbonTab118.set_property_value(RibbonTab.HeaderKey, "View");
                const _ribbonGroup119 = new RibbonGroup();
                _ribbonGroup119.set_property_value(RibbonGroup.HeaderKey, "History");
                const _ribbonButton120 = new RibbonButton();
                _ribbonButton120.set_property_value(RibbonButton.TextKey, "↶ Undo");
                _ribbonButton120.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton120, "UndoCommand"));
                _ribbonGroup119.AddChild(_ribbonButton120);
                const _ribbonButton121 = new RibbonButton();
                _ribbonButton121.set_property_value(RibbonButton.TextKey, "↷ Redo");
                _ribbonButton121.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton121, "RedoCommand"));
                _ribbonGroup119.AddChild(_ribbonButton121);
                _ribbonTab118.AddChild(_ribbonGroup119);
                _ribbon105.AddChild(_ribbonTab118);
                const _ribbonContextualGroup122 = new RibbonContextualGroup();
                _ribbonContextualGroup122.set_property_value(RibbonContextualGroup.HeaderKey, "Drawing Tools");
                _ribbonContextualGroup122.set_property_value(RibbonContextualGroup.ColorKey, new SolidColorBrush(Color.FromHex('#f97316')));
                _ribbonContextualGroup122.set_property_value(RibbonContextualGroup.IsActiveKey, DataContextBinding(_ribbonContextualGroup122, "HasSelection"));
                const _ribbonTab123 = new RibbonTab();
                _ribbonTab123.set_property_value(RibbonTab.HeaderKey, "Format");
                const _ribbonGroup124 = new RibbonGroup();
                _ribbonGroup124.set_property_value(RibbonGroup.HeaderKey, "Edit");
                const _ribbonButton125 = new RibbonButton();
                _ribbonButton125.set_property_value(RibbonButton.TextKey, "🗑 Delete");
                _ribbonButton125.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton125, "DeleteCommand"));
                _ribbonGroup124.AddChild(_ribbonButton125);
                const _ribbonButton126 = new RibbonButton();
                _ribbonButton126.set_property_value(RibbonButton.TextKey, "⎘ Duplicate");
                _ribbonButton126.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton126, "DuplicateCommand"));
                _ribbonGroup124.AddChild(_ribbonButton126);
                _ribbonTab123.AddChild(_ribbonGroup124);
                const _ribbonGroup127 = new RibbonGroup();
                _ribbonGroup127.set_property_value(RibbonGroup.HeaderKey, "Z-order");
                const _ribbonButton128 = new RibbonButton();
                _ribbonButton128.set_property_value(RibbonButton.TextKey, "Bring Front");
                _ribbonButton128.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton128, "BringFrontCommand"));
                _ribbonGroup127.AddChild(_ribbonButton128);
                const _ribbonButton129 = new RibbonButton();
                _ribbonButton129.set_property_value(RibbonButton.TextKey, "Send Back");
                _ribbonButton129.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton129, "SendBackCommand"));
                _ribbonGroup127.AddChild(_ribbonButton129);
                _ribbonTab123.AddChild(_ribbonGroup127);
                const _ribbonGroup130 = new RibbonGroup();
                _ribbonGroup130.set_property_value(RibbonGroup.HeaderKey, "Align");
                _ribbonGroup130.set_property_value(RibbonGroup.LaunchCommandKey, DataContextBinding(_ribbonGroup130, "AlignLeftCommand"));
                const _ribbonSmallButtonColumn131 = new RibbonSmallButtonColumn();
                const _ribbonButton132 = new RibbonButton();
                _ribbonButton132.set_property_value(RibbonButton.TextKey, "⬅ Left");
                _ribbonButton132.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton132, "AlignLeftCommand"));
                _ribbonSmallButtonColumn131.AddChild(_ribbonButton132);
                const _ribbonButton133 = new RibbonButton();
                _ribbonButton133.set_property_value(RibbonButton.TextKey, "⇔ Center");
                _ribbonButton133.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton133, "AlignCenterCommand"));
                _ribbonSmallButtonColumn131.AddChild(_ribbonButton133);
                const _ribbonButton134 = new RibbonButton();
                _ribbonButton134.set_property_value(RibbonButton.TextKey, "➡ Right");
                _ribbonButton134.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton134, "AlignRightCommand"));
                _ribbonSmallButtonColumn131.AddChild(_ribbonButton134);
                _ribbonGroup130.AddChild(_ribbonSmallButtonColumn131);
                const _ribbonSmallButtonColumn135 = new RibbonSmallButtonColumn();
                const _ribbonButton136 = new RibbonButton();
                _ribbonButton136.set_property_value(RibbonButton.TextKey, "⬆ Top");
                _ribbonButton136.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton136, "AlignTopCommand"));
                _ribbonSmallButtonColumn135.AddChild(_ribbonButton136);
                const _ribbonButton137 = new RibbonButton();
                _ribbonButton137.set_property_value(RibbonButton.TextKey, "↕ Middle");
                _ribbonButton137.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton137, "AlignMiddleCommand"));
                _ribbonSmallButtonColumn135.AddChild(_ribbonButton137);
                const _ribbonButton138 = new RibbonButton();
                _ribbonButton138.set_property_value(RibbonButton.TextKey, "⬇ Bottom");
                _ribbonButton138.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton138, "AlignBottomCommand"));
                _ribbonSmallButtonColumn135.AddChild(_ribbonButton138);
                _ribbonGroup130.AddChild(_ribbonSmallButtonColumn135);
                _ribbonTab123.AddChild(_ribbonGroup130);
                _ribbonContextualGroup122.AddChild(_ribbonTab123);
                _ribbon105.ContextualGroups.Add(_ribbonContextualGroup122);
                const _ribbonButton139 = new RibbonButton();
                _ribbonButton139.set_property_value(RibbonButton.TextKey, "💾");
                _ribbonButton139.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton139, "SaveCommand"));
                _ribbon105.QuickAccessItems.Add(_ribbonButton139);
                const _ribbonButton140 = new RibbonButton();
                _ribbonButton140.set_property_value(RibbonButton.TextKey, "↶");
                _ribbonButton140.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton140, "UndoCommand"));
                _ribbon105.QuickAccessItems.Add(_ribbonButton140);
                const _ribbonButton141 = new RibbonButton();
                _ribbonButton141.set_property_value(RibbonButton.TextKey, "↷");
                _ribbonButton141.set_property_value(RibbonButton.CommandKey, DataContextBinding(_ribbonButton141, "RedoCommand"));
                _ribbon105.QuickAccessItems.Add(_ribbonButton141);
                _border25.SetChild(_ribbon105);
                _dockPanel28.AddChild(_border25);
                _diagram26 = new Diagram();
                _diagram26.Name = "nodes";
                _diagram26.set_property_value(Diagram.ItemsSourceKey, DataContextBinding(_diagram26, "Nodes"));
                _diagram26.set_property_value(Diagram.ItemsPanelKey, _tmpl8);
                _diagram26.set_property_value(Diagram.SelectionModeKey, SelectionMode.Extended);
                _diagram26.set_property_value(Diagram.AllowMarqueeSelectionKey, true);
                _diagram26.set_property_value(Diagram.ReflectSelectionToItemsKey, true);
                _diagram26.set_property_value(Diagram.FocusableKey, true);
                _dockPanel28.AddChild(_diagram26);
                _border27.SetChild(_dockPanel28);
                return _border27;
            };
            const _tplSet142 = [new TargetedSetter(StackPanel, "Visibility", Visibility.Collapsed, "ClassicChrome"), new TargetedSetter(Border, "Visibility", Visibility.Visible, "RibbonChrome")];
            const _tplDataTrig143 = new TemplateDataTrigger("IsRibbonMode", true, _tplSet142);
            return new DataTemplate(_factory, CommandsVM, [], [_tplDataTrig143]);
        })();
        t.Set(CommandsVM, _tmpl23);
        return t;
    }
    get AlignSplitLabel() { return this.Resolve("AlignSplitLabel"); }
    set AlignSplitLabel(v) { this.Set("AlignSplitLabel", v); }
    get PlacementSplitLabel() { return this.Resolve("PlacementSplitLabel"); }
    set PlacementSplitLabel(v) { this.Set("PlacementSplitLabel", v); }
    get PlacementGrid() { return this.Resolve("PlacementGrid"); }
    set PlacementGrid(v) { this.Set("PlacementGrid", v); }
    get CommandsCanvasPanel() { return this.Resolve("CommandsCanvasPanel"); }
    set CommandsCanvasPanel(v) { this.Set("CommandsCanvasPanel", v); }
    get CommandsSelectedPen() { return this.Resolve("CommandsSelectedPen"); }
    set CommandsSelectedPen(v) { this.Set("CommandsSelectedPen", v); }
}
