import { NotebookNotesContributor, NotebookSectionsContributor } from "./hierarchy-tree-contributors.mjs";
import { HierarchyContext } from "@pragmatic-tech-ai/mural/framework/hierarchy/hierarchy-context.js";
import { HierarchyContributorDefinition } from "@pragmatic-tech-ai/mural/framework/hierarchy/hierarchy-contributor-definition.js";
import { CommandDefinition } from "@pragmatic-tech-ai/mural/framework/shell/commands/command-definition.js";
import { ShellModule } from "@pragmatic-tech-ai/mural/framework/shell/module.js";
import { ServiceProvider } from "@pragmatic-tech-ai/mural/runtime";

export const HierarchyTreeDemoModule = (() => {
    const _shellModule0 = new ShellModule();
    _shellModule0.set_property_value(ShellModule.NameKey, "HierarchyTreeDemo");
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(NotebookSectionsContributor), (p) => new NotebookSectionsContributor(p), 'singleton');
    _shellModule0.AddRegistration(ServiceProvider.tokenFor(NotebookNotesContributor), (p) => new NotebookNotesContributor(p), 'singleton');
    const _hierarchyContributorDefinition1 = new HierarchyContributorDefinition();
    _hierarchyContributorDefinition1.set_property_value(HierarchyContributorDefinition.ParentKeysKey, ["notebook"]);
    _hierarchyContributorDefinition1.set_property_value(HierarchyContributorDefinition.ContributorKey, NotebookSectionsContributor);
    _hierarchyContributorDefinition1.set_property_value(HierarchyContributorDefinition.OrderKey, 0);
    const _commandDefinition2 = new CommandDefinition();
    _commandDefinition2.set_property_value(CommandDefinition.IdKey, "hierarchy-tree-demo.section.star");
    _commandDefinition2.set_property_value(CommandDefinition.TitleKey, "Add Star");
    _commandDefinition2.set_property_value(CommandDefinition.ContextKey, HierarchyContext.For("section"));
    const _commandDefinition3 = new CommandDefinition();
    _commandDefinition3.set_property_value(CommandDefinition.IdKey, "hierarchy-tree-demo.section.clearStars");
    _commandDefinition3.set_property_value(CommandDefinition.TitleKey, "Clear Stars");
    _commandDefinition3.set_property_value(CommandDefinition.ContextKey, HierarchyContext.For("section"));
    _commandDefinition2.AddChild(_commandDefinition3);
    _hierarchyContributorDefinition1.set_property_value(HierarchyContributorDefinition.ActionsKey, [_commandDefinition2]);
    _shellModule0.HierarchyContributors.Add(_hierarchyContributorDefinition1);
    const _hierarchyContributorDefinition4 = new HierarchyContributorDefinition();
    _hierarchyContributorDefinition4.set_property_value(HierarchyContributorDefinition.ParentKeysKey, ["section"]);
    _hierarchyContributorDefinition4.set_property_value(HierarchyContributorDefinition.ContributorKey, NotebookNotesContributor);
    _hierarchyContributorDefinition4.set_property_value(HierarchyContributorDefinition.OrderKey, 0);
    const _commandDefinition5 = new CommandDefinition();
    _commandDefinition5.set_property_value(CommandDefinition.IdKey, "hierarchy-tree-demo.note.toggleDone");
    _commandDefinition5.set_property_value(CommandDefinition.TitleKey, "Toggle Done");
    _commandDefinition5.set_property_value(CommandDefinition.ContextKey, HierarchyContext.For("note"));
    const _commandDefinition6 = new CommandDefinition();
    _commandDefinition6.set_property_value(CommandDefinition.IdKey, "hierarchy-tree-demo.note.logToConsole");
    _commandDefinition6.set_property_value(CommandDefinition.TitleKey, "Log to Console");
    _commandDefinition6.set_property_value(CommandDefinition.ContextKey, HierarchyContext.For("note"));
    _commandDefinition5.AddChild(_commandDefinition6);
    _hierarchyContributorDefinition4.set_property_value(HierarchyContributorDefinition.ActionsKey, [_commandDefinition5]);
    _shellModule0.HierarchyContributors.Add(_hierarchyContributorDefinition4);
    return _shellModule0;
})();
