import { DrawerVM } from "./drawer-vm.mjs";
import { Border, DataTemplate, Dock, DockPanel, Line, Orientation, StackPanel, TextBlock, TextWrapping } from "@pragmatic-tech-ai/mural/basic";
import { Button } from "@pragmatic-tech-ai/mural/framework/buttons/button.js";
import { Drawer, DrawerVariant } from "@pragmatic-tech-ai/mural/framework/surfaces/drawer.js";
import { DataContextBinding, DynamicResource, ResourceDictionary, Thickness } from "@pragmatic-tech-ai/mural/runtime";
import { FontWeight, Pen } from "@pragmatic-tech-ai/mural/visual-engine";


const _gate_DrawerDemo = Symbol("DrawerDemo.ctor");
export class DrawerDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_DrawerDemo) {
            throw new Error("DrawerDemo is private — use DrawerDemo.Clone()");
        }
    }
    static Clone() {
        const t = new DrawerDemo(_gate_DrawerDemo);
        const _tmpl0 = new DataTemplate((_data) => {
            const _border1 = new Border();
            _border1.set_property_value(Border.FillKey, DynamicResource(_border1, "Surface"));
            _border1.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            const _dockPanel2 = new DockPanel();
            const _border3 = new Border();
            _border3.set_property_value(DockPanel.DockKey, Dock.Top);
            _border3.set_property_value(Border.HeightKey, 56);
            _border3.set_property_value(Border.FillKey, DynamicResource(_border3, "Primary"));
            const _stackPanel4 = new StackPanel();
            _stackPanel4.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _button5 = new Button();
            _button5.set_property_value(Button.WidthKey, 44);
            _button5.set_property_value(Button.CommandKey, DataContextBinding(_button5, "ToggleNav"));
            const _textBlock6 = new TextBlock();
            _textBlock6.set_property_value(TextBlock.TextKey, "≡");
            _textBlock6.set_property_value(TextBlock.FontSizeKey, 20);
            _button5.Content = _textBlock6;
            _stackPanel4.AddChild(_button5);
            const _textBlock7 = new TextBlock();
            _textBlock7.set_property_value(TextBlock.TextKey, "Drawer demo");
            _textBlock7.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock7.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock7.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock7, "OnPrimary"));
            _textBlock7.set_property_value(TextBlock.MarginKey, new Thickness(16, 16, 0, 0));
            _stackPanel4.AddChild(_textBlock7);
            _border3.SetChild(_stackPanel4);
            _dockPanel2.AddChild(_border3);
            const _drawer8 = new Drawer();
            _drawer8.set_property_value(DockPanel.DockKey, Dock.Left);
            _drawer8.set_property_value(Drawer.VariantKey, DrawerVariant.Persistent);
            _drawer8.set_property_value(Drawer.AnchorKey, Dock.Left);
            _drawer8.set_property_value(Drawer.DrawerSizeKey, 200);
            _drawer8.set_property_value(Drawer.RailSizeKey, 56);
            _drawer8.set_property_value(Drawer.IsOpenKey, DataContextBinding(_drawer8, "NavOpen"));
            const _border9 = new Border();
            _border9.set_property_value(Border.FillKey, DynamicResource(_border9, "SurfaceContainerLow"));
            const _dockPanel10 = new DockPanel();
            const _line11 = new Line();
            _line11.set_property_value(DockPanel.DockKey, Dock.Right);
            _line11.set_property_value(Line.OrientationKey, Orientation.Vertical);
            _line11.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line11, "OutlineVariant"), 1));
            _dockPanel10.AddChild(_line11);
            const _stackPanel12 = new StackPanel();
            const _textBlock13 = new TextBlock();
            _textBlock13.set_property_value(TextBlock.TextKey, "🏠");
            _textBlock13.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock13.set_property_value(TextBlock.MarginKey, new Thickness(20, 16, 0, 0));
            _stackPanel12.AddChild(_textBlock13);
            const _textBlock14 = new TextBlock();
            _textBlock14.set_property_value(TextBlock.TextKey, "📊");
            _textBlock14.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock14.set_property_value(TextBlock.MarginKey, new Thickness(20, 16, 0, 0));
            _stackPanel12.AddChild(_textBlock14);
            const _textBlock15 = new TextBlock();
            _textBlock15.set_property_value(TextBlock.TextKey, "⚙");
            _textBlock15.set_property_value(TextBlock.FontSizeKey, 18);
            _textBlock15.set_property_value(TextBlock.MarginKey, new Thickness(20, 16, 0, 0));
            _stackPanel12.AddChild(_textBlock15);
            _dockPanel10.AddChild(_stackPanel12);
            _border9.SetChild(_dockPanel10);
            _drawer8.Content = _border9;
            _dockPanel2.AddChild(_drawer8);
            const _drawer16 = new Drawer();
            _drawer16.set_property_value(Drawer.VariantKey, DrawerVariant.Temporary);
            _drawer16.set_property_value(Drawer.AnchorKey, Dock.Right);
            _drawer16.set_property_value(Drawer.DrawerSizeKey, 320);
            _drawer16.set_property_value(Drawer.IsOpenKey, DataContextBinding(_drawer16, "OptionsOpen"));
            const _border17 = new Border();
            _border17.set_property_value(Border.FillKey, DynamicResource(_border17, "Surface"));
            const _dockPanel18 = new DockPanel();
            const _line19 = new Line();
            _line19.set_property_value(DockPanel.DockKey, Dock.Left);
            _line19.set_property_value(Line.OrientationKey, Orientation.Vertical);
            _line19.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line19, "OutlineVariant"), 1));
            _dockPanel18.AddChild(_line19);
            const _stackPanel20 = new StackPanel();
            _stackPanel20.set_property_value(StackPanel.MarginKey, new Thickness(24));
            const _textBlock21 = new TextBlock();
            _textBlock21.set_property_value(TextBlock.TextKey, "Options");
            _textBlock21.set_property_value(TextBlock.FontSizeKey, 20);
            _textBlock21.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock21.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock21, "OnSurface"));
            _stackPanel20.AddChild(_textBlock21);
            const _textBlock22 = new TextBlock();
            _textBlock22.set_property_value(TextBlock.TextKey, "Drag the slider, flip the\n                                            toggles, pick a colour.\n                                            Click outside to dismiss.");
            _textBlock22.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock22.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock22.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock22, "OnSurfaceVariant"));
            _textBlock22.set_property_value(TextBlock.MarginKey, new Thickness(0, 8, 0, 0));
            _stackPanel20.AddChild(_textBlock22);
            const _button23 = new Button();
            _button23.set_property_value(Button.CommandKey, DataContextBinding(_button23, "CloseOptions"));
            _button23.set_property_value(Button.MarginKey, new Thickness(0, 24, 0, 0));
            _button23.set_property_value(Button.WidthKey, 120);
            const _textBlock24 = new TextBlock();
            _textBlock24.set_property_value(TextBlock.TextKey, "Close");
            _button23.Content = _textBlock24;
            _stackPanel20.AddChild(_button23);
            _dockPanel18.AddChild(_stackPanel20);
            _border17.SetChild(_dockPanel18);
            _drawer16.Content = _border17;
            _dockPanel2.AddChild(_drawer16);
            const _border25 = new Border();
            _border25.set_property_value(Border.FillKey, DynamicResource(_border25, "Surface"));
            _border25.set_property_value(Border.PaddingKey, new Thickness(24));
            const _stackPanel26 = new StackPanel();
            const _textBlock27 = new TextBlock();
            _textBlock27.set_property_value(TextBlock.TextKey, "The left drawer is Persistent —\n                                        the rail is always visible (56\n                                        DIPs); the header button toggles\n                                        the pane open / closed (200 DIPs).");
            _textBlock27.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock27.set_property_value(TextBlock.FontSizeKey, 13);
            _textBlock27.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock27, "OnSurface"));
            _stackPanel26.AddChild(_textBlock27);
            const _button28 = new Button();
            _button28.set_property_value(Button.CommandKey, DataContextBinding(_button28, "OpenOptions"));
            _button28.set_property_value(Button.WidthKey, 180);
            _button28.set_property_value(Button.MarginKey, new Thickness(0, 16, 0, 0));
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, "Open options →");
            _button28.Content = _textBlock29;
            _stackPanel26.AddChild(_button28);
            const _textBlock30 = new TextBlock();
            _textBlock30.set_property_value(TextBlock.TextKey, "The Options pane is Temporary —\n                                        it mounts onto the overlay layer\n                                        with a click-away scrim. Click\n                                        the scrim or the Close button to\n                                        dismiss.");
            _textBlock30.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock30.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock30.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock30, "OnSurfaceVariant"));
            _textBlock30.set_property_value(TextBlock.MarginKey, new Thickness(0, 16, 0, 0));
            _stackPanel26.AddChild(_textBlock30);
            _border25.SetChild(_stackPanel26);
            _dockPanel2.AddChild(_border25);
            _border1.SetChild(_dockPanel2);
            return _border1;
        }, DrawerVM);
        t.Set(DrawerVM, _tmpl0);
        return t;
    }
}
