import { DiagramTool } from "./diagram-tools.mjs";
import { Border, DataTemplate, Dock, DockPanel, ItemsPanelTemplate, Line, Orientation, PaginatedCanvas, Shape, Splitter, StackPanel, TextAlignment, TextBlock, TextWrapping, UniformGrid } from "@pragmatic-tech-ai/mural/basic";
import { ColorPicker, FontFamilyPicker, FontSizePicker, ShapeFormatControl, TextPlacement } from "@pragmatic-tech-ai/mural/framework";
import { ItemsControl } from "@pragmatic-tech-ai/mural/framework/base/items-control.js";
import { Button } from "@pragmatic-tech-ai/mural/framework/buttons/button.js";
import { DiagramDocument } from "@pragmatic-tech-ai/mural/framework/diagram/diagram-document.js";
import { Diagram } from "@pragmatic-tech-ai/mural/framework/diagram/diagram.js";
import { ToolboxItem } from "@pragmatic-tech-ai/mural/framework/diagram/toolbox/toolbox-item.js";
import { ToolboxPage } from "@pragmatic-tech-ai/mural/framework/diagram/toolbox/toolbox-page.js";
import { ToolboxRepository } from "@pragmatic-tech-ai/mural/framework/diagram/toolbox/toolbox-repository.js";
import { ToolboxVisualPresenter } from "@pragmatic-tech-ai/mural/framework/diagram/toolbox/toolbox-visual-presenter.js";
import { SelectionMode } from "@pragmatic-tech-ai/mural/framework/list/list-box.js";
import { MenuItem, MenuSeparator, ToolBar, ToolBarButton, ToolBarSplitButton, ToolBarToggleButton } from "@pragmatic-tech-ai/mural/framework/surface.js";
import { ScrollViewer } from "@pragmatic-tech-ai/mural/framework/surfaces/scroll-viewer.js";
import { DataContextBinding, DynamicResource, ElementNameBinding, HorizontalAlignment, Is, NameScope, ResourceDictionary, ServiceBinding, ServiceProvider, Thickness, VerticalAlignment } from "@pragmatic-tech-ai/mural/runtime";
import { FontWeight, LineSegment, PathFigure, PathGeometry, Pen, Point, QuadraticBezierSegment } from "@pragmatic-tech-ai/mural/visual-engine";


const _gate_DiagramDemo = Symbol("DiagramDemo.ctor");
export class DiagramDemo extends ResourceDictionary {
    constructor(_g) {
        super();
        if (_g !== _gate_DiagramDemo) {
            throw new Error("DiagramDemo is private — use DiagramDemo.Clone()");
        }
    }
    static Clone() {
        const t = new DiagramDemo(_gate_DiagramDemo);
        t.Set("join", new PathGeometry([new PathFigure(new Point(640, -280), [new LineSegment(new Point(640, -280)), new QuadraticBezierSegment(new Point(723, -280), new Point(781.5, -338.5)), new QuadraticBezierSegment(new Point(840, -397), new Point(840, -480)), new LineSegment(new Point(840, -480)), new QuadraticBezierSegment(new Point(840, -563), new Point(781.5, -621.5)), new QuadraticBezierSegment(new Point(723, -680), new Point(640, -680)), new LineSegment(new Point(640, -680)), new QuadraticBezierSegment(new Point(613, -680), new Point(587.5, -673)), new QuadraticBezierSegment(new Point(562, -666), new Point(540, -653)), new LineSegment(new Point(540, -653)), new QuadraticBezierSegment(new Point(569, -617), new Point(584.5, -573)), new QuadraticBezierSegment(new Point(600, -529), new Point(600, -480)), new LineSegment(new Point(600, -480)), new QuadraticBezierSegment(new Point(600, -431), new Point(584.5, -387)), new QuadraticBezierSegment(new Point(569, -343), new Point(540, -307)), new LineSegment(new Point(540, -307)), new QuadraticBezierSegment(new Point(562, -294), new Point(587.5, -287)), new QuadraticBezierSegment(new Point(613, -280), new Point(640, -280))], true), new PathFigure(new Point(480, -360), [new LineSegment(new Point(480, -360)), new QuadraticBezierSegment(new Point(499, -385), new Point(509.5, -415.5)), new QuadraticBezierSegment(new Point(520, -446), new Point(520, -480)), new QuadraticBezierSegment(new Point(520, -514), new Point(509.5, -544.5)), new QuadraticBezierSegment(new Point(499, -575), new Point(480, -600)), new LineSegment(new Point(480, -600)), new QuadraticBezierSegment(new Point(461, -575), new Point(450.5, -544.5)), new QuadraticBezierSegment(new Point(440, -514), new Point(440, -480)), new QuadraticBezierSegment(new Point(440, -446), new Point(450.5, -415.5)), new QuadraticBezierSegment(new Point(461, -385), new Point(480, -360))], true), new PathFigure(new Point(320, -280), [new LineSegment(new Point(320, -280)), new QuadraticBezierSegment(new Point(347, -280), new Point(372.5, -287)), new QuadraticBezierSegment(new Point(398, -294), new Point(420, -307)), new LineSegment(new Point(420, -307)), new QuadraticBezierSegment(new Point(391, -343), new Point(375.5, -387)), new QuadraticBezierSegment(new Point(360, -431), new Point(360, -480)), new LineSegment(new Point(360, -480)), new QuadraticBezierSegment(new Point(360, -529), new Point(375.5, -573)), new QuadraticBezierSegment(new Point(391, -617), new Point(420, -653)), new LineSegment(new Point(420, -653)), new QuadraticBezierSegment(new Point(398, -666), new Point(372.5, -673)), new QuadraticBezierSegment(new Point(347, -680), new Point(320, -680)), new LineSegment(new Point(320, -680)), new QuadraticBezierSegment(new Point(237, -680), new Point(178.5, -621.5)), new QuadraticBezierSegment(new Point(120, -563), new Point(120, -480)), new LineSegment(new Point(120, -480)), new QuadraticBezierSegment(new Point(120, -397), new Point(178.5, -338.5)), new QuadraticBezierSegment(new Point(237, -280), new Point(320, -280))], true), new PathFigure(new Point(320, -200), [new LineSegment(new Point(320, -200)), new QuadraticBezierSegment(new Point(203, -200), new Point(121.5, -281.5)), new QuadraticBezierSegment(new Point(40, -363), new Point(40, -480)), new QuadraticBezierSegment(new Point(40, -597), new Point(121.5, -678.5)), new QuadraticBezierSegment(new Point(203, -760), new Point(320, -760)), new LineSegment(new Point(320, -760)), new QuadraticBezierSegment(new Point(365, -760), new Point(405.5, -747)), new QuadraticBezierSegment(new Point(446, -734), new Point(480, -710)), new LineSegment(new Point(480, -710)), new QuadraticBezierSegment(new Point(514, -734), new Point(554.5, -747)), new QuadraticBezierSegment(new Point(595, -760), new Point(640, -760)), new LineSegment(new Point(640, -760)), new QuadraticBezierSegment(new Point(757, -760), new Point(838.5, -678.5)), new QuadraticBezierSegment(new Point(920, -597), new Point(920, -480)), new QuadraticBezierSegment(new Point(920, -363), new Point(838.5, -281.5)), new QuadraticBezierSegment(new Point(757, -200), new Point(640, -200)), new LineSegment(new Point(640, -200)), new QuadraticBezierSegment(new Point(595, -200), new Point(554.5, -213)), new QuadraticBezierSegment(new Point(514, -226), new Point(480, -250)), new LineSegment(new Point(480, -250)), new QuadraticBezierSegment(new Point(446, -226), new Point(405.5, -213)), new QuadraticBezierSegment(new Point(365, -200), new Point(320, -200))], true)]));
        t.Set("join_inner", new PathGeometry([new PathFigure(new Point(320, -200), [new LineSegment(new Point(320, -200)), new QuadraticBezierSegment(new Point(203, -200), new Point(121.5, -281.5)), new QuadraticBezierSegment(new Point(40, -363), new Point(40, -480)), new QuadraticBezierSegment(new Point(40, -597), new Point(121.5, -678.5)), new QuadraticBezierSegment(new Point(203, -760), new Point(320, -760)), new LineSegment(new Point(320, -760)), new QuadraticBezierSegment(new Point(347, -760), new Point(372.5, -755)), new QuadraticBezierSegment(new Point(398, -750), new Point(422, -741)), new LineSegment(new Point(422, -741)), new QuadraticBezierSegment(new Point(405, -727), new Point(390, -710.5)), new QuadraticBezierSegment(new Point(375, -694), new Point(362, -676)), new LineSegment(new Point(362, -676)), new QuadraticBezierSegment(new Point(352, -678), new Point(341.5, -679)), new QuadraticBezierSegment(new Point(331, -680), new Point(320, -680)), new LineSegment(new Point(320, -680)), new QuadraticBezierSegment(new Point(237, -680), new Point(178.5, -621.5)), new QuadraticBezierSegment(new Point(120, -563), new Point(120, -480)), new LineSegment(new Point(120, -480)), new QuadraticBezierSegment(new Point(120, -397), new Point(178.5, -338.5)), new QuadraticBezierSegment(new Point(237, -280), new Point(320, -280)), new LineSegment(new Point(320, -280)), new QuadraticBezierSegment(new Point(331, -280), new Point(341.5, -281)), new QuadraticBezierSegment(new Point(352, -282), new Point(362, -284)), new LineSegment(new Point(362, -284)), new QuadraticBezierSegment(new Point(375, -266), new Point(390, -249.5)), new QuadraticBezierSegment(new Point(405, -233), new Point(422, -219)), new LineSegment(new Point(422, -219)), new QuadraticBezierSegment(new Point(398, -210), new Point(372.5, -205)), new QuadraticBezierSegment(new Point(347, -200), new Point(320, -200))], true), new PathFigure(new Point(640, -200), [new LineSegment(new Point(640, -200)), new QuadraticBezierSegment(new Point(613, -200), new Point(587.5, -205)), new QuadraticBezierSegment(new Point(562, -210), new Point(538, -219)), new LineSegment(new Point(538, -219)), new QuadraticBezierSegment(new Point(555, -233), new Point(570, -249.5)), new QuadraticBezierSegment(new Point(585, -266), new Point(598, -284)), new LineSegment(new Point(598, -284)), new QuadraticBezierSegment(new Point(609, -282), new Point(619, -281)), new QuadraticBezierSegment(new Point(629, -280), new Point(640, -280)), new LineSegment(new Point(640, -280)), new QuadraticBezierSegment(new Point(723, -280), new Point(781.5, -338.5)), new QuadraticBezierSegment(new Point(840, -397), new Point(840, -480)), new LineSegment(new Point(840, -480)), new QuadraticBezierSegment(new Point(840, -563), new Point(781.5, -621.5)), new QuadraticBezierSegment(new Point(723, -680), new Point(640, -680)), new LineSegment(new Point(640, -680)), new QuadraticBezierSegment(new Point(629, -680), new Point(619, -679)), new QuadraticBezierSegment(new Point(609, -678), new Point(598, -676)), new LineSegment(new Point(598, -676)), new QuadraticBezierSegment(new Point(585, -694), new Point(570, -710.5)), new QuadraticBezierSegment(new Point(555, -727), new Point(538, -741)), new LineSegment(new Point(538, -741)), new QuadraticBezierSegment(new Point(562, -750), new Point(587.5, -755)), new QuadraticBezierSegment(new Point(613, -760), new Point(640, -760)), new LineSegment(new Point(640, -760)), new QuadraticBezierSegment(new Point(757, -760), new Point(838.5, -678.5)), new QuadraticBezierSegment(new Point(920, -597), new Point(920, -480)), new QuadraticBezierSegment(new Point(920, -363), new Point(838.5, -281.5)), new QuadraticBezierSegment(new Point(757, -200), new Point(640, -200))], true), new PathFigure(new Point(480, -250), [new LineSegment(new Point(480, -250)), new QuadraticBezierSegment(new Point(423, -289), new Point(391.5, -350)), new QuadraticBezierSegment(new Point(360, -411), new Point(360, -480)), new QuadraticBezierSegment(new Point(360, -549), new Point(391.5, -610)), new QuadraticBezierSegment(new Point(423, -671), new Point(480, -710)), new LineSegment(new Point(480, -710)), new QuadraticBezierSegment(new Point(537, -671), new Point(568.5, -610)), new QuadraticBezierSegment(new Point(600, -549), new Point(600, -480)), new QuadraticBezierSegment(new Point(600, -411), new Point(568.5, -350)), new QuadraticBezierSegment(new Point(537, -289), new Point(480, -250))], true)]));
        t.Set("join_left", new PathGeometry([new PathFigure(new Point(320, -200), [new LineSegment(new Point(320, -200)), new QuadraticBezierSegment(new Point(203, -200), new Point(121.5, -281.5)), new QuadraticBezierSegment(new Point(40, -363), new Point(40, -480)), new QuadraticBezierSegment(new Point(40, -597), new Point(121.5, -678.5)), new QuadraticBezierSegment(new Point(203, -760), new Point(320, -760)), new LineSegment(new Point(320, -760)), new QuadraticBezierSegment(new Point(347, -760), new Point(372.5, -755)), new QuadraticBezierSegment(new Point(398, -750), new Point(422, -741)), new LineSegment(new Point(422, -741)), new QuadraticBezierSegment(new Point(364, -692), new Point(332, -624)), new QuadraticBezierSegment(new Point(300, -556), new Point(300, -480)), new LineSegment(new Point(300, -480)), new QuadraticBezierSegment(new Point(300, -404), new Point(332, -336)), new QuadraticBezierSegment(new Point(364, -268), new Point(422, -219)), new LineSegment(new Point(422, -219)), new QuadraticBezierSegment(new Point(398, -210), new Point(372.5, -205)), new QuadraticBezierSegment(new Point(347, -200), new Point(320, -200))], true), new PathFigure(new Point(640, -200), [new LineSegment(new Point(640, -200)), new QuadraticBezierSegment(new Point(613, -200), new Point(587.5, -205)), new QuadraticBezierSegment(new Point(562, -210), new Point(538, -219)), new LineSegment(new Point(538, -219)), new QuadraticBezierSegment(new Point(555, -233), new Point(570, -249.5)), new QuadraticBezierSegment(new Point(585, -266), new Point(598, -284)), new LineSegment(new Point(598, -284)), new QuadraticBezierSegment(new Point(609, -282), new Point(619, -281)), new QuadraticBezierSegment(new Point(629, -280), new Point(640, -280)), new LineSegment(new Point(640, -280)), new QuadraticBezierSegment(new Point(723, -280), new Point(781.5, -338.5)), new QuadraticBezierSegment(new Point(840, -397), new Point(840, -480)), new LineSegment(new Point(840, -480)), new QuadraticBezierSegment(new Point(840, -563), new Point(781.5, -621.5)), new QuadraticBezierSegment(new Point(723, -680), new Point(640, -680)), new LineSegment(new Point(640, -680)), new QuadraticBezierSegment(new Point(629, -680), new Point(619, -679)), new QuadraticBezierSegment(new Point(609, -678), new Point(598, -676)), new LineSegment(new Point(598, -676)), new QuadraticBezierSegment(new Point(585, -694), new Point(570, -710.5)), new QuadraticBezierSegment(new Point(555, -727), new Point(538, -741)), new LineSegment(new Point(538, -741)), new QuadraticBezierSegment(new Point(562, -750), new Point(587.5, -755)), new QuadraticBezierSegment(new Point(613, -760), new Point(640, -760)), new LineSegment(new Point(640, -760)), new QuadraticBezierSegment(new Point(757, -760), new Point(838.5, -678.5)), new QuadraticBezierSegment(new Point(920, -597), new Point(920, -480)), new QuadraticBezierSegment(new Point(920, -363), new Point(838.5, -281.5)), new QuadraticBezierSegment(new Point(757, -200), new Point(640, -200))], true), new PathFigure(new Point(480, -250), [new LineSegment(new Point(480, -250)), new QuadraticBezierSegment(new Point(423, -289), new Point(391.5, -350)), new QuadraticBezierSegment(new Point(360, -411), new Point(360, -480)), new QuadraticBezierSegment(new Point(360, -549), new Point(391.5, -610)), new QuadraticBezierSegment(new Point(423, -671), new Point(480, -710)), new LineSegment(new Point(480, -710)), new QuadraticBezierSegment(new Point(537, -671), new Point(568.5, -610)), new QuadraticBezierSegment(new Point(600, -549), new Point(600, -480)), new QuadraticBezierSegment(new Point(600, -411), new Point(568.5, -350)), new QuadraticBezierSegment(new Point(537, -289), new Point(480, -250))], true)]));
        t.Set("difference", new PathGeometry([new PathFigure(new Point(500, -600), [new LineSegment(new Point(500, -520)), new LineSegment(new Point(580, -520)), new LineSegment(new Point(580, -600)), new LineSegment(new Point(660, -600)), new LineSegment(new Point(660, -680)), new LineSegment(new Point(580, -680)), new LineSegment(new Point(580, -760)), new LineSegment(new Point(500, -760)), new LineSegment(new Point(500, -680)), new LineSegment(new Point(420, -680)), new LineSegment(new Point(420, -600)), new LineSegment(new Point(500, -600))], true), new PathFigure(new Point(420, -440), [new LineSegment(new Point(420, -360)), new LineSegment(new Point(660, -360)), new LineSegment(new Point(660, -440)), new LineSegment(new Point(420, -440))], true), new PathFigure(new Point(760, -200), [new LineSegment(new Point(320, -200)), new QuadraticBezierSegment(new Point(287, -200), new Point(263.5, -223.5)), new QuadraticBezierSegment(new Point(240, -247), new Point(240, -280)), new LineSegment(new Point(240, -280)), new LineSegment(new Point(240, -840)), new QuadraticBezierSegment(new Point(240, -873), new Point(263.5, -896.5)), new QuadraticBezierSegment(new Point(287, -920), new Point(320, -920)), new LineSegment(new Point(320, -920)), new LineSegment(new Point(600, -920)), new LineSegment(new Point(840, -680)), new LineSegment(new Point(840, -280)), new QuadraticBezierSegment(new Point(840, -247), new Point(816.5, -223.5)), new QuadraticBezierSegment(new Point(793, -200), new Point(760, -200)), new LineSegment(new Point(760, -200))], true), new PathFigure(new Point(320, -280), [new LineSegment(new Point(320, -280)), new LineSegment(new Point(760, -280)), new QuadraticBezierSegment(new Point(760, -280), new Point(760, -280)), new QuadraticBezierSegment(new Point(760, -280), new Point(760, -280)), new LineSegment(new Point(760, -280)), new LineSegment(new Point(760, -640)), new LineSegment(new Point(560, -840)), new LineSegment(new Point(320, -840)), new QuadraticBezierSegment(new Point(320, -840), new Point(320, -840)), new QuadraticBezierSegment(new Point(320, -840), new Point(320, -840)), new LineSegment(new Point(320, -840)), new LineSegment(new Point(320, -280)), new QuadraticBezierSegment(new Point(320, -280), new Point(320, -280)), new QuadraticBezierSegment(new Point(320, -280), new Point(320, -280))], true), new PathFigure(new Point(600, -40), [new LineSegment(new Point(160, -40)), new QuadraticBezierSegment(new Point(127, -40), new Point(103.5, -63.5)), new QuadraticBezierSegment(new Point(80, -87), new Point(80, -120)), new LineSegment(new Point(80, -120)), new LineSegment(new Point(80, -680)), new LineSegment(new Point(160, -680)), new LineSegment(new Point(160, -120)), new QuadraticBezierSegment(new Point(160, -120), new Point(160, -120)), new QuadraticBezierSegment(new Point(160, -120), new Point(160, -120)), new LineSegment(new Point(160, -120)), new LineSegment(new Point(600, -120)), new LineSegment(new Point(600, -40))], true), new PathFigure(new Point(320, -280), [new LineSegment(new Point(320, -280)), new QuadraticBezierSegment(new Point(320, -280), new Point(320, -280)), new QuadraticBezierSegment(new Point(320, -280), new Point(320, -280)), new LineSegment(new Point(320, -280)), new LineSegment(new Point(320, -840)), new QuadraticBezierSegment(new Point(320, -840), new Point(320, -840)), new QuadraticBezierSegment(new Point(320, -840), new Point(320, -840)), new LineSegment(new Point(320, -840)), new LineSegment(new Point(320, -840)), new LineSegment(new Point(320, -640)), new LineSegment(new Point(320, -280)), new QuadraticBezierSegment(new Point(320, -280), new Point(320, -280)), new QuadraticBezierSegment(new Point(320, -280), new Point(320, -280)), new LineSegment(new Point(320, -280))], true)]));
        t.Set("polyline", new PathGeometry([new PathFigure(new Point(840, -80), [new LineSegment(new Point(600, -80)), new LineSegment(new Point(600, -180)), new LineSegment(new Point(320, -320)), new LineSegment(new Point(120, -320)), new LineSegment(new Point(120, -560)), new LineSegment(new Point(292, -560)), new LineSegment(new Point(400, -684)), new LineSegment(new Point(400, -880)), new LineSegment(new Point(640, -880)), new LineSegment(new Point(640, -640)), new LineSegment(new Point(468, -640)), new LineSegment(new Point(360, -516)), new LineSegment(new Point(360, -390)), new LineSegment(new Point(600, -270)), new LineSegment(new Point(600, -320)), new LineSegment(new Point(840, -320)), new LineSegment(new Point(840, -80))], true), new PathFigure(new Point(480, -800), [new LineSegment(new Point(480, -720)), new LineSegment(new Point(560, -720)), new LineSegment(new Point(560, -800)), new LineSegment(new Point(480, -800))], true), new PathFigure(new Point(200, -480), [new LineSegment(new Point(200, -400)), new LineSegment(new Point(280, -400)), new LineSegment(new Point(280, -480)), new LineSegment(new Point(200, -480))], true), new PathFigure(new Point(680, -240), [new LineSegment(new Point(680, -160)), new LineSegment(new Point(760, -160)), new LineSegment(new Point(760, -240)), new LineSegment(new Point(680, -240))], true), new PathFigure(new Point(520, -760), [new LineSegment(new Point(520, -760)), new LineSegment(new Point(520, -760)), new LineSegment(new Point(520, -760)), new LineSegment(new Point(520, -760))], true), new PathFigure(new Point(240, -440), [new LineSegment(new Point(240, -440)), new LineSegment(new Point(240, -440)), new LineSegment(new Point(240, -440)), new LineSegment(new Point(240, -440))], true), new PathFigure(new Point(720, -200), [new LineSegment(new Point(720, -200)), new LineSegment(new Point(720, -200)), new LineSegment(new Point(720, -200)), new LineSegment(new Point(720, -200))], true)]));
        t.Set("format_align_left", new PathGeometry([new PathFigure(new Point(840, -120), [new LineSegment(new Point(120, -120)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(840, -200)), new LineSegment(new Point(840, -120))], true), new PathFigure(new Point(600, -280), [new LineSegment(new Point(120, -280)), new LineSegment(new Point(120, -360)), new LineSegment(new Point(600, -360)), new LineSegment(new Point(600, -280))], true), new PathFigure(new Point(840, -440), [new LineSegment(new Point(120, -440)), new LineSegment(new Point(120, -520)), new LineSegment(new Point(840, -520)), new LineSegment(new Point(840, -440))], true), new PathFigure(new Point(600, -600), [new LineSegment(new Point(120, -600)), new LineSegment(new Point(120, -680)), new LineSegment(new Point(600, -680)), new LineSegment(new Point(600, -600))], true), new PathFigure(new Point(840, -760), [new LineSegment(new Point(120, -760)), new LineSegment(new Point(120, -840)), new LineSegment(new Point(840, -840)), new LineSegment(new Point(840, -760))], true)]));
        t.Set("format_align_center", new PathGeometry([new PathFigure(new Point(840, -120), [new LineSegment(new Point(120, -120)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(840, -200)), new LineSegment(new Point(840, -120))], true), new PathFigure(new Point(680, -280), [new LineSegment(new Point(280, -280)), new LineSegment(new Point(280, -360)), new LineSegment(new Point(680, -360)), new LineSegment(new Point(680, -280))], true), new PathFigure(new Point(840, -440), [new LineSegment(new Point(120, -440)), new LineSegment(new Point(120, -520)), new LineSegment(new Point(840, -520)), new LineSegment(new Point(840, -440))], true), new PathFigure(new Point(680, -600), [new LineSegment(new Point(280, -600)), new LineSegment(new Point(280, -680)), new LineSegment(new Point(680, -680)), new LineSegment(new Point(680, -600))], true), new PathFigure(new Point(840, -760), [new LineSegment(new Point(120, -760)), new LineSegment(new Point(120, -840)), new LineSegment(new Point(840, -840)), new LineSegment(new Point(840, -760))], true)]));
        t.Set("format_align_right", new PathGeometry([new PathFigure(new Point(840, -760), [new LineSegment(new Point(120, -760)), new LineSegment(new Point(120, -840)), new LineSegment(new Point(840, -840)), new LineSegment(new Point(840, -760))], true), new PathFigure(new Point(840, -600), [new LineSegment(new Point(360, -600)), new LineSegment(new Point(360, -680)), new LineSegment(new Point(840, -680)), new LineSegment(new Point(840, -600))], true), new PathFigure(new Point(840, -440), [new LineSegment(new Point(120, -440)), new LineSegment(new Point(120, -520)), new LineSegment(new Point(840, -520)), new LineSegment(new Point(840, -440))], true), new PathFigure(new Point(840, -280), [new LineSegment(new Point(360, -280)), new LineSegment(new Point(360, -360)), new LineSegment(new Point(840, -360)), new LineSegment(new Point(840, -280))], true), new PathFigure(new Point(840, -120), [new LineSegment(new Point(120, -120)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(840, -200)), new LineSegment(new Point(840, -120))], true)]));
        t.Set("format_align_justify", new PathGeometry([new PathFigure(new Point(840, -120), [new LineSegment(new Point(120, -120)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(840, -200)), new LineSegment(new Point(840, -120))], true), new PathFigure(new Point(840, -280), [new LineSegment(new Point(120, -280)), new LineSegment(new Point(120, -360)), new LineSegment(new Point(840, -360)), new LineSegment(new Point(840, -280))], true), new PathFigure(new Point(840, -440), [new LineSegment(new Point(120, -440)), new LineSegment(new Point(120, -520)), new LineSegment(new Point(840, -520)), new LineSegment(new Point(840, -440))], true), new PathFigure(new Point(840, -600), [new LineSegment(new Point(120, -600)), new LineSegment(new Point(120, -680)), new LineSegment(new Point(840, -680)), new LineSegment(new Point(840, -600))], true), new PathFigure(new Point(840, -760), [new LineSegment(new Point(120, -760)), new LineSegment(new Point(120, -840)), new LineSegment(new Point(840, -840)), new LineSegment(new Point(840, -760))], true)]));
        t.Set("north_west", new PathGeometry([new PathFigure(new Point(800, -216), [new LineSegment(new Point(744, -160)), new LineSegment(new Point(280, -624)), new LineSegment(new Point(280, -360)), new LineSegment(new Point(200, -360)), new LineSegment(new Point(200, -760)), new LineSegment(new Point(600, -760)), new LineSegment(new Point(600, -680)), new LineSegment(new Point(336, -680)), new LineSegment(new Point(800, -216))], true)]));
        t.Set("north", new PathGeometry([new PathFigure(new Point(520, -80), [new LineSegment(new Point(440, -80)), new LineSegment(new Point(440, -727)), new LineSegment(new Point(256, -544)), new LineSegment(new Point(200, -600)), new LineSegment(new Point(480, -880)), new LineSegment(new Point(760, -600)), new LineSegment(new Point(704, -543)), new LineSegment(new Point(520, -727)), new LineSegment(new Point(520, -80))], true)]));
        t.Set("north_east", new PathGeometry([new PathFigure(new Point(680, -624), [new LineSegment(new Point(216, -160)), new LineSegment(new Point(160, -216)), new LineSegment(new Point(624, -680)), new LineSegment(new Point(360, -680)), new LineSegment(new Point(360, -760)), new LineSegment(new Point(760, -760)), new LineSegment(new Point(760, -360)), new LineSegment(new Point(680, -360)), new LineSegment(new Point(680, -624))], true)]));
        t.Set("west", new PathGeometry([new PathFigure(new Point(417, -256), [new LineSegment(new Point(360, -200)), new LineSegment(new Point(80, -480)), new LineSegment(new Point(360, -760)), new LineSegment(new Point(416, -704)), new LineSegment(new Point(233, -520)), new LineSegment(new Point(880, -520)), new LineSegment(new Point(880, -440)), new LineSegment(new Point(233, -440)), new LineSegment(new Point(417, -256))], true)]));
        t.Set("filter_center_focus", new PathGeometry([new PathFigure(new Point(480, -360), [new QuadraticBezierSegment(new Point(430, -360), new Point(395, -395)), new QuadraticBezierSegment(new Point(360, -430), new Point(360, -480)), new QuadraticBezierSegment(new Point(360, -530), new Point(395, -565)), new QuadraticBezierSegment(new Point(430, -600), new Point(480, -600)), new QuadraticBezierSegment(new Point(530, -600), new Point(565, -565)), new QuadraticBezierSegment(new Point(600, -530), new Point(600, -480)), new QuadraticBezierSegment(new Point(600, -430), new Point(565, -395)), new QuadraticBezierSegment(new Point(530, -360), new Point(480, -360))], true), new PathFigure(new Point(480, -440), [new QuadraticBezierSegment(new Point(497, -440), new Point(508.5, -451.5)), new QuadraticBezierSegment(new Point(520, -463), new Point(520, -480)), new QuadraticBezierSegment(new Point(520, -497), new Point(508.5, -508.5)), new QuadraticBezierSegment(new Point(497, -520), new Point(480, -520)), new QuadraticBezierSegment(new Point(463, -520), new Point(451.5, -508.5)), new QuadraticBezierSegment(new Point(440, -497), new Point(440, -480)), new QuadraticBezierSegment(new Point(440, -463), new Point(451.5, -451.5)), new QuadraticBezierSegment(new Point(463, -440), new Point(480, -440))], true), new PathFigure(new Point(360, -120), [new LineSegment(new Point(200, -120)), new QuadraticBezierSegment(new Point(167, -120), new Point(143.5, -143.5)), new QuadraticBezierSegment(new Point(120, -167), new Point(120, -200)), new LineSegment(new Point(120, -200)), new LineSegment(new Point(120, -360)), new LineSegment(new Point(200, -360)), new LineSegment(new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new QuadraticBezierSegment(new Point(200, -200), new Point(200, -200)), new LineSegment(new Point(200, -200)), new LineSegment(new Point(360, -200)), new LineSegment(new Point(360, -120))], true), new PathFigure(new Point(760, -120), [new LineSegment(new Point(600, -120)), new LineSegment(new Point(600, -200)), new LineSegment(new Point(760, -200)), new QuadraticBezierSegment(new Point(760, -200), new Point(760, -200)), new QuadraticBezierSegment(new Point(760, -200), new Point(760, -200)), new LineSegment(new Point(760, -200)), new LineSegment(new Point(760, -360)), new LineSegment(new Point(840, -360)), new LineSegment(new Point(840, -200)), new QuadraticBezierSegment(new Point(840, -167), new Point(816.5, -143.5)), new QuadraticBezierSegment(new Point(793, -120), new Point(760, -120)), new LineSegment(new Point(760, -120))], true), new PathFigure(new Point(200, -600), [new LineSegment(new Point(120, -600)), new LineSegment(new Point(120, -760)), new QuadraticBezierSegment(new Point(120, -793), new Point(143.5, -816.5)), new QuadraticBezierSegment(new Point(167, -840), new Point(200, -840)), new LineSegment(new Point(200, -840)), new LineSegment(new Point(360, -840)), new LineSegment(new Point(360, -760)), new LineSegment(new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new QuadraticBezierSegment(new Point(200, -760), new Point(200, -760)), new LineSegment(new Point(200, -760)), new LineSegment(new Point(200, -600))], true), new PathFigure(new Point(840, -600), [new LineSegment(new Point(760, -600)), new LineSegment(new Point(760, -760)), new QuadraticBezierSegment(new Point(760, -760), new Point(760, -760)), new QuadraticBezierSegment(new Point(760, -760), new Point(760, -760)), new LineSegment(new Point(760, -760)), new LineSegment(new Point(600, -760)), new LineSegment(new Point(600, -840)), new LineSegment(new Point(760, -840)), new QuadraticBezierSegment(new Point(793, -840), new Point(816.5, -816.5)), new QuadraticBezierSegment(new Point(840, -793), new Point(840, -760)), new LineSegment(new Point(840, -760)), new LineSegment(new Point(840, -600))], true)]));
        t.Set("east", new PathGeometry([new PathFigure(new Point(880, -480), [new LineSegment(new Point(600, -200)), new LineSegment(new Point(543, -256)), new LineSegment(new Point(727, -440)), new LineSegment(new Point(80, -440)), new LineSegment(new Point(80, -520)), new LineSegment(new Point(727, -520)), new LineSegment(new Point(544, -704)), new LineSegment(new Point(600, -760)), new LineSegment(new Point(880, -480))], true)]));
        t.Set("south_west", new PathGeometry([new PathFigure(new Point(600, -200), [new LineSegment(new Point(200, -200)), new LineSegment(new Point(200, -600)), new LineSegment(new Point(280, -600)), new LineSegment(new Point(280, -336)), new LineSegment(new Point(744, -800)), new LineSegment(new Point(800, -744)), new LineSegment(new Point(336, -280)), new LineSegment(new Point(600, -280)), new LineSegment(new Point(600, -200))], true)]));
        t.Set("south", new PathGeometry([new PathFigure(new Point(760, -360), [new LineSegment(new Point(480, -80)), new LineSegment(new Point(200, -360)), new LineSegment(new Point(256, -416)), new LineSegment(new Point(440, -233)), new LineSegment(new Point(440, -880)), new LineSegment(new Point(520, -880)), new LineSegment(new Point(520, -233)), new LineSegment(new Point(704, -417)), new LineSegment(new Point(760, -360))], true)]));
        t.Set("south_east", new PathGeometry([new PathFigure(new Point(760, -200), [new LineSegment(new Point(360, -200)), new LineSegment(new Point(360, -280)), new LineSegment(new Point(624, -280)), new LineSegment(new Point(160, -744)), new LineSegment(new Point(216, -800)), new LineSegment(new Point(680, -336)), new LineSegment(new Point(680, -600)), new LineSegment(new Point(760, -600)), new LineSegment(new Point(760, -200))], true)]));
        t.Set("format_bold", new PathGeometry([new PathFigure(new Point(501, -200), [new LineSegment(new Point(272, -200)), new LineSegment(new Point(272, -760)), new LineSegment(new Point(493, -760)), new QuadraticBezierSegment(new Point(558, -760), new Point(613, -720)), new QuadraticBezierSegment(new Point(668, -680), new Point(668, -609)), new LineSegment(new Point(668, -609)), new QuadraticBezierSegment(new Point(668, -558), new Point(645, -530.5)), new QuadraticBezierSegment(new Point(622, -503), new Point(602, -491)), new LineSegment(new Point(602, -491)), new LineSegment(new Point(602, -491)), new QuadraticBezierSegment(new Point(627, -480), new Point(657.5, -450)), new QuadraticBezierSegment(new Point(688, -420), new Point(688, -360)), new LineSegment(new Point(688, -360)), new QuadraticBezierSegment(new Point(688, -271), new Point(623, -235.5)), new QuadraticBezierSegment(new Point(558, -200), new Point(501, -200)), new LineSegment(new Point(501, -200))], true), new PathFigure(new Point(393, -432), [new LineSegment(new Point(393, -312)), new LineSegment(new Point(497, -312)), new QuadraticBezierSegment(new Point(545, -312), new Point(555.5, -336.5)), new QuadraticBezierSegment(new Point(566, -361), new Point(566, -372)), new LineSegment(new Point(566, -372)), new QuadraticBezierSegment(new Point(566, -383), new Point(555.5, -407.5)), new QuadraticBezierSegment(new Point(545, -432), new Point(494, -432)), new LineSegment(new Point(494, -432)), new LineSegment(new Point(393, -432))], true), new PathFigure(new Point(393, -649), [new LineSegment(new Point(393, -540)), new LineSegment(new Point(486, -540)), new QuadraticBezierSegment(new Point(519, -540), new Point(534, -557)), new QuadraticBezierSegment(new Point(549, -574), new Point(549, -595)), new LineSegment(new Point(549, -595)), new QuadraticBezierSegment(new Point(549, -619), new Point(532, -634)), new QuadraticBezierSegment(new Point(515, -649), new Point(488, -649)), new LineSegment(new Point(488, -649)), new LineSegment(new Point(393, -649))], true)]));
        t.Set("format_italic", new PathGeometry([new PathFigure(new Point(600, -200), [new LineSegment(new Point(200, -200)), new LineSegment(new Point(200, -300)), new LineSegment(new Point(360, -300)), new LineSegment(new Point(480, -660)), new LineSegment(new Point(320, -660)), new LineSegment(new Point(320, -760)), new LineSegment(new Point(720, -760)), new LineSegment(new Point(720, -660)), new LineSegment(new Point(580, -660)), new LineSegment(new Point(460, -300)), new LineSegment(new Point(600, -300)), new LineSegment(new Point(600, -200))], true)]));
        t.Set("format_underlined", new PathGeometry([new PathFigure(new Point(760, -120), [new LineSegment(new Point(200, -120)), new LineSegment(new Point(200, -200)), new LineSegment(new Point(760, -200)), new LineSegment(new Point(760, -120))], true), new PathFigure(new Point(480, -280), [new QuadraticBezierSegment(new Point(379, -280), new Point(323, -343)), new QuadraticBezierSegment(new Point(267, -406), new Point(267, -510)), new LineSegment(new Point(267, -510)), new LineSegment(new Point(267, -840)), new LineSegment(new Point(370, -840)), new LineSegment(new Point(370, -504)), new QuadraticBezierSegment(new Point(370, -448), new Point(398, -413)), new QuadraticBezierSegment(new Point(426, -378), new Point(480, -378)), new QuadraticBezierSegment(new Point(534, -378), new Point(562, -413)), new QuadraticBezierSegment(new Point(590, -448), new Point(590, -504)), new LineSegment(new Point(590, -504)), new LineSegment(new Point(590, -840)), new LineSegment(new Point(693, -840)), new LineSegment(new Point(693, -510)), new QuadraticBezierSegment(new Point(693, -406), new Point(637, -343)), new QuadraticBezierSegment(new Point(581, -280), new Point(480, -280))], true)]));
        t.Set("format_strikethrough", new PathGeometry([new PathFigure(new Point(880, -400), [new LineSegment(new Point(80, -400)), new LineSegment(new Point(80, -480)), new LineSegment(new Point(880, -480)), new LineSegment(new Point(880, -400))], true), new PathFigure(new Point(540, -560), [new LineSegment(new Point(420, -560)), new LineSegment(new Point(420, -680)), new LineSegment(new Point(200, -680)), new LineSegment(new Point(200, -800)), new LineSegment(new Point(760, -800)), new LineSegment(new Point(760, -680)), new LineSegment(new Point(540, -680)), new LineSegment(new Point(540, -560))], true), new PathFigure(new Point(540, -160), [new LineSegment(new Point(420, -160)), new LineSegment(new Point(420, -320)), new LineSegment(new Point(540, -320)), new LineSegment(new Point(540, -160))], true)]));
        t.Set("text_increase", new PathGeometry([new PathFigure(new Point(136, -200), [new LineSegment(new Point(40, -200)), new LineSegment(new Point(250, -760)), new LineSegment(new Point(350, -760)), new LineSegment(new Point(560, -200)), new LineSegment(new Point(464, -200)), new LineSegment(new Point(413, -343)), new LineSegment(new Point(187, -343)), new LineSegment(new Point(136, -200))], true), new PathFigure(new Point(298, -656), [new LineSegment(new Point(216, -424)), new LineSegment(new Point(384, -424)), new LineSegment(new Point(302, -656)), new LineSegment(new Point(298, -656))], true), new PathFigure(new Point(800, -320), [new LineSegment(new Point(720, -320)), new LineSegment(new Point(720, -440)), new LineSegment(new Point(600, -440)), new LineSegment(new Point(600, -520)), new LineSegment(new Point(720, -520)), new LineSegment(new Point(720, -640)), new LineSegment(new Point(800, -640)), new LineSegment(new Point(800, -520)), new LineSegment(new Point(920, -520)), new LineSegment(new Point(920, -440)), new LineSegment(new Point(800, -440)), new LineSegment(new Point(800, -320))], true)]));
        t.Set("text_decrease", new PathGeometry([new PathFigure(new Point(136, -200), [new LineSegment(new Point(40, -200)), new LineSegment(new Point(250, -760)), new LineSegment(new Point(350, -760)), new LineSegment(new Point(560, -200)), new LineSegment(new Point(464, -200)), new LineSegment(new Point(413, -343)), new LineSegment(new Point(187, -343)), new LineSegment(new Point(136, -200))], true), new PathFigure(new Point(298, -656), [new LineSegment(new Point(216, -424)), new LineSegment(new Point(384, -424)), new LineSegment(new Point(302, -656)), new LineSegment(new Point(298, -656))], true), new PathFigure(new Point(920, -440), [new LineSegment(new Point(600, -440)), new LineSegment(new Point(600, -520)), new LineSegment(new Point(920, -520)), new LineSegment(new Point(920, -440))], true)]));
        const _tmpl0 = new ItemsPanelTemplate(() => {
            const _paginatedCanvas1 = new PaginatedCanvas();
            _paginatedCanvas1.set_property_value(PaginatedCanvas.PageWidthKey, 800);
            _paginatedCanvas1.set_property_value(PaginatedCanvas.PageHeightKey, 600);
            return _paginatedCanvas1;
        });
        t.Set("DiagramCanvasPanel", _tmpl0);
        const _tmpl2 = new ItemsPanelTemplate(() => {
            const _uniformGrid3 = new UniformGrid();
            _uniformGrid3.set_property_value(UniformGrid.ColumnsKey, 2);
            return _uniformGrid3;
        });
        t.Set("DiagramToolboxPanel", _tmpl2);
        const _tmpl4 = new DataTemplate((_data) => {
            const _border5 = new Border();
            _border5.SetNameScope(new NameScope());
            _border5.set_property_value(Border.IsDraggableKey, true);
            _border5.set_property_value(Border.OnDragStartKey, DataContextBinding(_border5, "BeginDragData"));
            _border5.set_property_value(Border.FillKey, DynamicResource(_border5, "Surface"));
            _border5.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            _border5.set_property_value(Border.CornerRadiusKey, 4);
            _border5.set_property_value(Border.PaddingKey, new Thickness(4, 8, 4, 8));
            _border5.set_property_value(Border.MarginKey, new Thickness(2, 0, 2, 4));
            const _stackPanel6 = new StackPanel();
            _stackPanel6.set_property_value(StackPanel.OrientationKey, Orientation.Vertical);
            _stackPanel6.set_property_value(StackPanel.HorizontalAlignmentKey, HorizontalAlignment.Center);
            const _toolboxVisualPresenter7 = new ToolboxVisualPresenter();
            _toolboxVisualPresenter7.set_property_value(ToolboxVisualPresenter.DescriptorKey, DataContextBinding(_toolboxVisualPresenter7, "Descriptor"));
            _toolboxVisualPresenter7.set_property_value(ToolboxVisualPresenter.WidthKey, 48);
            _toolboxVisualPresenter7.set_property_value(ToolboxVisualPresenter.HeightKey, 48);
            _toolboxVisualPresenter7.set_property_value(ToolboxVisualPresenter.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel6.AddChild(_toolboxVisualPresenter7);
            const _textBlock8 = new TextBlock();
            _textBlock8.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock8, "Label"));
            _textBlock8.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock8.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock8, "OnSurface"));
            _textBlock8.set_property_value(TextBlock.MarginKey, new Thickness(0, 4, 0, 0));
            _textBlock8.set_property_value(TextBlock.HorizontalAlignmentKey, HorizontalAlignment.Center);
            _stackPanel6.AddChild(_textBlock8);
            _border5.SetChild(_stackPanel6);
            return _border5;
        }, ToolboxItem);
        t.Set(ToolboxItem, _tmpl4);
        const _tmpl9 = new DataTemplate((_data) => {
            const _dockPanel10 = new DockPanel();
            _dockPanel10.set_property_value(DockPanel.MarginKey, new Thickness(0, 0, 0, 8));
            const _textBlock11 = new TextBlock();
            _textBlock11.set_property_value(DockPanel.DockKey, Dock.Top);
            _textBlock11.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock11, "Title"));
            _textBlock11.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock11.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock11.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock11, "OnSurfaceVariant"));
            _textBlock11.set_property_value(TextBlock.MarginKey, new Thickness(2, 0, 0, 8));
            _dockPanel10.AddChild(_textBlock11);
            const _itemsControl12 = new ItemsControl();
            _itemsControl12.set_property_value(ItemsControl.ItemsSourceKey, DataContextBinding(_itemsControl12, "Items"));
            _itemsControl12.set_property_value(ItemsControl.ItemsPanelKey, _tmpl2);
            _dockPanel10.AddChild(_itemsControl12);
            return _dockPanel10;
        }, ToolboxPage);
        t.Set(ToolboxPage, _tmpl9);
        const _tmpl13 = new DataTemplate((_data) => {
            const _toolBarButton14 = new ToolBarButton();
            _toolBarButton14.set_property_value(ToolBarButton.CommandKey, DataContextBinding(_toolBarButton14, "Command"));
            const _shape15 = new Shape();
            _shape15.set_property_value(Shape.GeometryKey, DataContextBinding(_shape15, "Icon"));
            _shape15.set_property_value(Shape.FillKey, DynamicResource(_shape15, "OnSurfaceVariant"));
            _shape15.set_property_value(Shape.WidthKey, 16);
            _shape15.set_property_value(Shape.HeightKey, 16);
            _shape15.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarButton14.Content = _shape15;
            return _toolBarButton14;
        }, DiagramTool);
        t.Set("DiagramToolTemplate", _tmpl13);
        const _stackPanel16 = new StackPanel();
        _stackPanel16.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
        _stackPanel16.set_property_value(StackPanel.VerticalAlignmentKey, VerticalAlignment.Center);
        const _shape17 = new Shape();
        _shape17.set_property_value(Shape.GeometryKey, DynamicResource(_shape17, "filter_center_focus"));
        _shape17.set_property_value(Shape.FillKey, DynamicResource(_shape17, "OnSurfaceVariant"));
        _shape17.set_property_value(Shape.WidthKey, 16);
        _shape17.set_property_value(Shape.HeightKey, 16);
        _shape17.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
        _stackPanel16.AddChild(_shape17);
        const _textBlock18 = new TextBlock();
        _textBlock18.set_property_value(TextBlock.TextKey, "Placement");
        _textBlock18.set_property_value(TextBlock.MarginKey, new Thickness(6, 0, 0, 0));
        _textBlock18.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
        _stackPanel16.AddChild(_textBlock18);
        t.Set("DiagramPlacementSplitLabel", _stackPanel16);
        const _tmpl19 = new ItemsPanelTemplate(() => {
            const _uniformGrid20 = new UniformGrid();
            _uniformGrid20.set_property_value(UniformGrid.ColumnsKey, 3);
            return _uniformGrid20;
        });
        t.Set("DiagramPlacementGrid", _tmpl19);
        const _tmpl21 = new DataTemplate((_data) => {
            let _diagram22;
            const _border23 = new Border();
            _border23.SetNameScope(new NameScope());
            _border23.set_property_value(Border.FillKey, DynamicResource(_border23, "Surface"));
            _border23.set_property_value(Border.StrokeKey, ((_e) => { _e.Brush = DynamicResource(_e, "OutlineVariant"); return _e; })(new Pen()));
            const _dockPanel24 = new DockPanel();
            const _border25 = new Border();
            _border25.set_property_value(DockPanel.DockKey, Dock.Top);
            _border25.set_property_value(Border.HeightKey, 44);
            _border25.set_property_value(Border.FillKey, DynamicResource(_border25, "Primary"));
            const _stackPanel26 = new StackPanel();
            _stackPanel26.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel26.set_property_value(StackPanel.MarginKey, new Thickness(16, 0, 0, 0));
            const _shape27 = new Shape();
            _shape27.set_property_value(Shape.GeometryKey, DynamicResource(_shape27, "home"));
            _shape27.set_property_value(Shape.FillKey, DynamicResource(_shape27, "OnPrimary"));
            _shape27.set_property_value(Shape.WidthKey, 24);
            _shape27.set_property_value(Shape.HeightKey, 24);
            _shape27.set_property_value(Shape.VerticalAlignmentKey, VerticalAlignment.Center);
            _stackPanel26.AddChild(_shape27);
            const _textBlock28 = new TextBlock();
            _textBlock28.set_property_value(TextBlock.TextKey, "Diagrammer");
            _textBlock28.set_property_value(TextBlock.FontSizeKey, 15);
            _textBlock28.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock28.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock28, "OnPrimary"));
            _textBlock28.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
            _textBlock28.set_property_value(TextBlock.MarginKey, new Thickness(8, 0, 0, 0));
            _stackPanel26.AddChild(_textBlock28);
            const _textBlock29 = new TextBlock();
            _textBlock29.set_property_value(TextBlock.TextKey, DataContextBinding(_textBlock29, "Status"));
            _textBlock29.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock29.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock29, "OnPrimary"));
            _textBlock29.set_property_value(TextBlock.VerticalAlignmentKey, VerticalAlignment.Center);
            _textBlock29.set_property_value(TextBlock.MarginKey, new Thickness(20, 0, 0, 0));
            _stackPanel26.AddChild(_textBlock29);
            _border25.SetChild(_stackPanel26);
            _dockPanel24.AddChild(_border25);
            const _border30 = new Border();
            _border30.set_property_value(DockPanel.DockKey, Dock.Top);
            _border30.set_property_value(Border.FillKey, DynamicResource(_border30, "SurfaceContainer"));
            _border30.set_property_value(Border.PaddingKey, new Thickness(8, 4, 8, 4));
            const _dockPanel31 = new DockPanel();
            const _line32 = new Line();
            _line32.set_property_value(DockPanel.DockKey, Dock.Bottom);
            _line32.set_property_value(Line.OrientationKey, Orientation.Horizontal);
            _line32.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line32, "OutlineVariant"), 1));
            _dockPanel31.AddChild(_line32);
            const _scrollViewer33 = new ScrollViewer();
            _scrollViewer33.set_property_value(ScrollViewer.HorizontalScrollEnabledKey, true);
            _scrollViewer33.set_property_value(ScrollViewer.VerticalScrollEnabledKey, false);
            _scrollViewer33.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, true);
            const _stackPanel34 = new StackPanel();
            _stackPanel34.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            const _toolBar35 = new ToolBar();
            const _toolBarToggleButton36 = new ToolBarToggleButton();
            _toolBarToggleButton36.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "ConnectorsModePinned"));
            const _shape37 = new Shape();
            _shape37.set_property_value(Shape.GeometryKey, DynamicResource(_shape37, "polyline"));
            _shape37.set_property_value(Shape.WidthKey, 16);
            _shape37.set_property_value(Shape.HeightKey, 16);
            _shape37.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton36.Content = _shape37;
            _toolBar35.AddChild(_toolBarToggleButton36);
            _stackPanel34.AddChild(_toolBar35);
            const _toolBar38 = new ToolBar();
            _toolBar38.set_property_value(ToolBar.MarginKey, new Thickness(8, 0, 0, 0));
            const _toolBarSplitButton39 = new ToolBarSplitButton();
            _toolBarSplitButton39.set_property_value(ToolBarSplitButton.ContentKey, ((_e) => { _e.Geometry = DynamicResource(_e, "alignLeft"); _e.Fill = DynamicResource(_e, "OnSurfaceVariant"); _e.Width = 16; _e.Height = 16; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
            const _menuItem40 = new MenuItem();
            _menuItem40.set_property_value(MenuItem.HeaderKey, "Align Left");
            _menuItem40.set_property_value(MenuItem.CommandKey, ElementNameBinding(() => _diagram22, "AlignLeftCommand"));
            _menuItem40.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "alignLeft"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
            _toolBarSplitButton39.AddChild(_menuItem40);
            const _menuItem41 = new MenuItem();
            _menuItem41.set_property_value(MenuItem.HeaderKey, "Align Center");
            _menuItem41.set_property_value(MenuItem.CommandKey, ElementNameBinding(() => _diagram22, "AlignCenterCommand"));
            _menuItem41.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "alignCenter"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
            _toolBarSplitButton39.AddChild(_menuItem41);
            const _menuItem42 = new MenuItem();
            _menuItem42.set_property_value(MenuItem.HeaderKey, "Align Right");
            _menuItem42.set_property_value(MenuItem.CommandKey, ElementNameBinding(() => _diagram22, "AlignRightCommand"));
            _menuItem42.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "alignRight"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
            _toolBarSplitButton39.AddChild(_menuItem42);
            const _menuItem43 = new MenuItem();
            _menuItem43.set_property_value(MenuItem.HeaderKey, "Align Top");
            _menuItem43.set_property_value(MenuItem.CommandKey, ElementNameBinding(() => _diagram22, "AlignTopCommand"));
            _menuItem43.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "alignTop"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
            _toolBarSplitButton39.AddChild(_menuItem43);
            const _menuItem44 = new MenuItem();
            _menuItem44.set_property_value(MenuItem.HeaderKey, "Align Middle");
            _menuItem44.set_property_value(MenuItem.CommandKey, ElementNameBinding(() => _diagram22, "AlignMiddleCommand"));
            _menuItem44.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "alignMiddle"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
            _toolBarSplitButton39.AddChild(_menuItem44);
            const _menuSeparator45 = new MenuSeparator();
            _toolBarSplitButton39.AddChild(_menuSeparator45);
            const _menuItem46 = new MenuItem();
            _menuItem46.set_property_value(MenuItem.HeaderKey, "Distribute Horizontally");
            _menuItem46.set_property_value(MenuItem.CommandKey, ElementNameBinding(() => _diagram22, "DistributeHorizontalCommand"));
            _menuItem46.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "distributeHorizontal"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
            _toolBarSplitButton39.AddChild(_menuItem46);
            const _menuItem47 = new MenuItem();
            _menuItem47.set_property_value(MenuItem.HeaderKey, "Distribute Vertically");
            _menuItem47.set_property_value(MenuItem.CommandKey, ElementNameBinding(() => _diagram22, "DistributeVerticalCommand"));
            _menuItem47.set_property_value(MenuItem.IconKey, ((_e) => { _e.Geometry = DynamicResource(_e, "distributeVertical"); _e.Width = 16; _e.Height = 16; _e.HorizontalAlignment = HorizontalAlignment.Center; _e.VerticalAlignment = VerticalAlignment.Center; return _e; })(new Shape()));
            _toolBarSplitButton39.AddChild(_menuItem47);
            _toolBar38.AddChild(_toolBarSplitButton39);
            _stackPanel34.AddChild(_toolBar38);
            const _toolBar48 = new ToolBar();
            _toolBar48.set_property_value(ToolBar.MarginKey, new Thickness(8, 0, 0, 0));
            _toolBar48.set_property_value(ToolBar.ItemTemplateKey, _tmpl13);
            _toolBar48.set_property_value(ToolBar.ItemsSourceKey, [((_e) => { _e.Icon = DynamicResource(_e, "group"); _e.Command = ElementNameBinding(() => _diagram22, "GroupCommand"); return _e; })(new DiagramTool()), ((_e) => { _e.Icon = DynamicResource(_e, "ungroup"); _e.Command = ElementNameBinding(() => _diagram22, "UngroupCommand"); return _e; })(new DiagramTool())]);
            _stackPanel34.AddChild(_toolBar48);
            const _toolBar49 = new ToolBar();
            _toolBar49.set_property_value(ToolBar.MarginKey, new Thickness(8, 0, 0, 0));
            _toolBar49.set_property_value(ToolBar.ItemTemplateKey, _tmpl13);
            _toolBar49.set_property_value(ToolBar.ItemsSourceKey, [((_e) => { _e.Icon = DynamicResource(_e, "join"); _e.Command = ElementNameBinding(() => _diagram22, "CombineUnionCommand"); return _e; })(new DiagramTool()), ((_e) => { _e.Icon = DynamicResource(_e, "join_inner"); _e.Command = ElementNameBinding(() => _diagram22, "CombineIntersectCommand"); return _e; })(new DiagramTool()), ((_e) => { _e.Icon = DynamicResource(_e, "join_left"); _e.Command = ElementNameBinding(() => _diagram22, "CombineSubtractCommand"); return _e; })(new DiagramTool()), ((_e) => { _e.Icon = DynamicResource(_e, "difference"); _e.Command = ElementNameBinding(() => _diagram22, "CombineExcludeCommand"); return _e; })(new DiagramTool())]);
            _stackPanel34.AddChild(_toolBar49);
            const _toolBar50 = new ToolBar();
            const _toolBarToggleButton51 = new ToolBarToggleButton();
            _toolBarToggleButton51.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextAlignLeftCommand"));
            _toolBarToggleButton51.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextAlignment", Is(TextAlignment.Left)));
            const _shape52 = new Shape();
            _shape52.set_property_value(Shape.GeometryKey, DynamicResource(_shape52, "format_align_left"));
            _shape52.set_property_value(Shape.WidthKey, 16);
            _shape52.set_property_value(Shape.HeightKey, 16);
            _shape52.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton51.Content = _shape52;
            _toolBar50.AddChild(_toolBarToggleButton51);
            const _toolBarToggleButton53 = new ToolBarToggleButton();
            _toolBarToggleButton53.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextAlignCenterCommand"));
            _toolBarToggleButton53.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextAlignment", Is(TextAlignment.Center)));
            const _shape54 = new Shape();
            _shape54.set_property_value(Shape.GeometryKey, DynamicResource(_shape54, "format_align_center"));
            _shape54.set_property_value(Shape.WidthKey, 16);
            _shape54.set_property_value(Shape.HeightKey, 16);
            _shape54.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton53.Content = _shape54;
            _toolBar50.AddChild(_toolBarToggleButton53);
            const _toolBarToggleButton55 = new ToolBarToggleButton();
            _toolBarToggleButton55.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextAlignRightCommand"));
            _toolBarToggleButton55.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextAlignment", Is(TextAlignment.Right)));
            const _shape56 = new Shape();
            _shape56.set_property_value(Shape.GeometryKey, DynamicResource(_shape56, "format_align_right"));
            _shape56.set_property_value(Shape.WidthKey, 16);
            _shape56.set_property_value(Shape.HeightKey, 16);
            _shape56.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton55.Content = _shape56;
            _toolBar50.AddChild(_toolBarToggleButton55);
            const _toolBarToggleButton57 = new ToolBarToggleButton();
            _toolBarToggleButton57.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextAlignJustifyCommand"));
            _toolBarToggleButton57.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextAlignment", Is(TextAlignment.Justify)));
            const _shape58 = new Shape();
            _shape58.set_property_value(Shape.GeometryKey, DynamicResource(_shape58, "format_align_justify"));
            _shape58.set_property_value(Shape.WidthKey, 16);
            _shape58.set_property_value(Shape.HeightKey, 16);
            _shape58.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton57.Content = _shape58;
            _toolBar50.AddChild(_toolBarToggleButton57);
            _stackPanel34.AddChild(_toolBar50);
            const _toolBar59 = new ToolBar();
            _toolBar59.set_property_value(ToolBar.MarginKey, new Thickness(8, 0, 0, 0));
            const _toolBarSplitButton60 = new ToolBarSplitButton();
            _toolBarSplitButton60.set_property_value(ToolBarSplitButton.ContentKey, DynamicResource(_toolBarSplitButton60, "DiagramPlacementSplitLabel"));
            _toolBarSplitButton60.set_property_value(ToolBarSplitButton.ItemsPanelKey, _tmpl19);
            const _toolBarToggleButton61 = new ToolBarToggleButton();
            _toolBarToggleButton61.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextPlacementTopLeftCommand"));
            _toolBarToggleButton61.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextPlacement", Is(TextPlacement.TopLeft)));
            const _shape62 = new Shape();
            _shape62.set_property_value(Shape.GeometryKey, DynamicResource(_shape62, "north_west"));
            _shape62.set_property_value(Shape.WidthKey, 16);
            _shape62.set_property_value(Shape.HeightKey, 16);
            _shape62.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton61.Content = _shape62;
            _toolBarSplitButton60.AddChild(_toolBarToggleButton61);
            const _toolBarToggleButton63 = new ToolBarToggleButton();
            _toolBarToggleButton63.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextPlacementTopCommand"));
            _toolBarToggleButton63.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextPlacement", Is(TextPlacement.Top)));
            const _shape64 = new Shape();
            _shape64.set_property_value(Shape.GeometryKey, DynamicResource(_shape64, "north"));
            _shape64.set_property_value(Shape.WidthKey, 16);
            _shape64.set_property_value(Shape.HeightKey, 16);
            _shape64.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton63.Content = _shape64;
            _toolBarSplitButton60.AddChild(_toolBarToggleButton63);
            const _toolBarToggleButton65 = new ToolBarToggleButton();
            _toolBarToggleButton65.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextPlacementTopRightCommand"));
            _toolBarToggleButton65.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextPlacement", Is(TextPlacement.TopRight)));
            const _shape66 = new Shape();
            _shape66.set_property_value(Shape.GeometryKey, DynamicResource(_shape66, "north_east"));
            _shape66.set_property_value(Shape.WidthKey, 16);
            _shape66.set_property_value(Shape.HeightKey, 16);
            _shape66.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton65.Content = _shape66;
            _toolBarSplitButton60.AddChild(_toolBarToggleButton65);
            const _toolBarToggleButton67 = new ToolBarToggleButton();
            _toolBarToggleButton67.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextPlacementLeftCommand"));
            _toolBarToggleButton67.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextPlacement", Is(TextPlacement.Left)));
            const _shape68 = new Shape();
            _shape68.set_property_value(Shape.GeometryKey, DynamicResource(_shape68, "west"));
            _shape68.set_property_value(Shape.WidthKey, 16);
            _shape68.set_property_value(Shape.HeightKey, 16);
            _shape68.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton67.Content = _shape68;
            _toolBarSplitButton60.AddChild(_toolBarToggleButton67);
            const _toolBarToggleButton69 = new ToolBarToggleButton();
            _toolBarToggleButton69.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextPlacementCenterCommand"));
            _toolBarToggleButton69.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextPlacement", Is(TextPlacement.Center)));
            const _shape70 = new Shape();
            _shape70.set_property_value(Shape.GeometryKey, DynamicResource(_shape70, "filter_center_focus"));
            _shape70.set_property_value(Shape.WidthKey, 16);
            _shape70.set_property_value(Shape.HeightKey, 16);
            _shape70.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton69.Content = _shape70;
            _toolBarSplitButton60.AddChild(_toolBarToggleButton69);
            const _toolBarToggleButton71 = new ToolBarToggleButton();
            _toolBarToggleButton71.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextPlacementRightCommand"));
            _toolBarToggleButton71.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextPlacement", Is(TextPlacement.Right)));
            const _shape72 = new Shape();
            _shape72.set_property_value(Shape.GeometryKey, DynamicResource(_shape72, "east"));
            _shape72.set_property_value(Shape.WidthKey, 16);
            _shape72.set_property_value(Shape.HeightKey, 16);
            _shape72.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton71.Content = _shape72;
            _toolBarSplitButton60.AddChild(_toolBarToggleButton71);
            const _toolBarToggleButton73 = new ToolBarToggleButton();
            _toolBarToggleButton73.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextPlacementBottomLeftCommand"));
            _toolBarToggleButton73.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextPlacement", Is(TextPlacement.BottomLeft)));
            const _shape74 = new Shape();
            _shape74.set_property_value(Shape.GeometryKey, DynamicResource(_shape74, "south_west"));
            _shape74.set_property_value(Shape.WidthKey, 16);
            _shape74.set_property_value(Shape.HeightKey, 16);
            _shape74.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton73.Content = _shape74;
            _toolBarSplitButton60.AddChild(_toolBarToggleButton73);
            const _toolBarToggleButton75 = new ToolBarToggleButton();
            _toolBarToggleButton75.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextPlacementBottomCommand"));
            _toolBarToggleButton75.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextPlacement", Is(TextPlacement.Bottom)));
            const _shape76 = new Shape();
            _shape76.set_property_value(Shape.GeometryKey, DynamicResource(_shape76, "south"));
            _shape76.set_property_value(Shape.WidthKey, 16);
            _shape76.set_property_value(Shape.HeightKey, 16);
            _shape76.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton75.Content = _shape76;
            _toolBarSplitButton60.AddChild(_toolBarToggleButton75);
            const _toolBarToggleButton77 = new ToolBarToggleButton();
            _toolBarToggleButton77.set_property_value(ToolBarToggleButton.CommandKey, ElementNameBinding(() => _diagram22, "SetTextPlacementBottomRightCommand"));
            _toolBarToggleButton77.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionTextPlacement", Is(TextPlacement.BottomRight)));
            const _shape78 = new Shape();
            _shape78.set_property_value(Shape.GeometryKey, DynamicResource(_shape78, "south_east"));
            _shape78.set_property_value(Shape.WidthKey, 16);
            _shape78.set_property_value(Shape.HeightKey, 16);
            _shape78.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton77.Content = _shape78;
            _toolBarSplitButton60.AddChild(_toolBarToggleButton77);
            _toolBar59.AddChild(_toolBarSplitButton60);
            _stackPanel34.AddChild(_toolBar59);
            const _fontFamilyPicker79 = new FontFamilyPicker();
            _fontFamilyPicker79.set_property_value(FontFamilyPicker.TextKey, ElementNameBinding(() => _diagram22, "SelectionFontFamily"));
            _fontFamilyPicker79.set_property_value(FontFamilyPicker.WidthKey, 170);
            _fontFamilyPicker79.set_property_value(FontFamilyPicker.MarginKey, new Thickness(8, 0, 0, 0));
            _fontFamilyPicker79.set_property_value(FontFamilyPicker.VerticalAlignmentKey, VerticalAlignment.Center);
            _stackPanel34.AddChild(_fontFamilyPicker79);
            const _fontSizePicker80 = new FontSizePicker();
            _fontSizePicker80.set_property_value(FontSizePicker.ValueKey, ElementNameBinding(() => _diagram22, "SelectionFontSize"));
            _fontSizePicker80.set_property_value(FontSizePicker.IsEditableKey, true);
            _fontSizePicker80.set_property_value(FontSizePicker.WidthKey, 80);
            _fontSizePicker80.set_property_value(FontSizePicker.MarginKey, new Thickness(8, 0, 0, 0));
            _fontSizePicker80.set_property_value(FontSizePicker.VerticalAlignmentKey, VerticalAlignment.Center);
            _stackPanel34.AddChild(_fontSizePicker80);
            const _toolBar81 = new ToolBar();
            _toolBar81.set_property_value(ToolBar.MarginKey, new Thickness(8, 0, 0, 0));
            const _toolBarButton82 = new ToolBarButton();
            _toolBarButton82.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram22, "IncreaseFontSizeCommand"));
            const _shape83 = new Shape();
            _shape83.set_property_value(Shape.GeometryKey, DynamicResource(_shape83, "text_increase"));
            _shape83.set_property_value(Shape.FillKey, DynamicResource(_shape83, "OnSurfaceVariant"));
            _shape83.set_property_value(Shape.WidthKey, 16);
            _shape83.set_property_value(Shape.HeightKey, 16);
            _shape83.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarButton82.Content = _shape83;
            _toolBar81.AddChild(_toolBarButton82);
            const _toolBarButton84 = new ToolBarButton();
            _toolBarButton84.set_property_value(ToolBarButton.CommandKey, ElementNameBinding(() => _diagram22, "DecreaseFontSizeCommand"));
            const _shape85 = new Shape();
            _shape85.set_property_value(Shape.GeometryKey, DynamicResource(_shape85, "text_decrease"));
            _shape85.set_property_value(Shape.FillKey, DynamicResource(_shape85, "OnSurfaceVariant"));
            _shape85.set_property_value(Shape.WidthKey, 16);
            _shape85.set_property_value(Shape.HeightKey, 16);
            _shape85.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarButton84.Content = _shape85;
            _toolBar81.AddChild(_toolBarButton84);
            _stackPanel34.AddChild(_toolBar81);
            const _colorPicker86 = new ColorPicker();
            _colorPicker86.set_property_value(ColorPicker.ColorHexKey, ElementNameBinding(() => _diagram22, "SelectionFontColorHex"));
            _colorPicker86.set_property_value(ColorPicker.MarginKey, new Thickness(8, 0, 0, 0));
            _colorPicker86.set_property_value(ColorPicker.VerticalAlignmentKey, VerticalAlignment.Center);
            _stackPanel34.AddChild(_colorPicker86);
            const _toolBar87 = new ToolBar();
            _toolBar87.set_property_value(ToolBar.MarginKey, new Thickness(8, 0, 0, 0));
            const _toolBarToggleButton88 = new ToolBarToggleButton();
            _toolBarToggleButton88.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionBold"));
            const _shape89 = new Shape();
            _shape89.set_property_value(Shape.GeometryKey, DynamicResource(_shape89, "format_bold"));
            _shape89.set_property_value(Shape.WidthKey, 16);
            _shape89.set_property_value(Shape.HeightKey, 16);
            _shape89.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton88.Content = _shape89;
            _toolBar87.AddChild(_toolBarToggleButton88);
            const _toolBarToggleButton90 = new ToolBarToggleButton();
            _toolBarToggleButton90.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionItalic"));
            const _shape91 = new Shape();
            _shape91.set_property_value(Shape.GeometryKey, DynamicResource(_shape91, "format_italic"));
            _shape91.set_property_value(Shape.WidthKey, 16);
            _shape91.set_property_value(Shape.HeightKey, 16);
            _shape91.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton90.Content = _shape91;
            _toolBar87.AddChild(_toolBarToggleButton90);
            const _toolBarToggleButton92 = new ToolBarToggleButton();
            _toolBarToggleButton92.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionUnderline"));
            const _shape93 = new Shape();
            _shape93.set_property_value(Shape.GeometryKey, DynamicResource(_shape93, "format_underlined"));
            _shape93.set_property_value(Shape.WidthKey, 16);
            _shape93.set_property_value(Shape.HeightKey, 16);
            _shape93.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton92.Content = _shape93;
            _toolBar87.AddChild(_toolBarToggleButton92);
            const _toolBarToggleButton94 = new ToolBarToggleButton();
            _toolBarToggleButton94.set_property_value(ToolBarToggleButton.IsCheckedKey, ElementNameBinding(() => _diagram22, "SelectionStrikethrough"));
            const _shape95 = new Shape();
            _shape95.set_property_value(Shape.GeometryKey, DynamicResource(_shape95, "format_strikethrough"));
            _shape95.set_property_value(Shape.WidthKey, 16);
            _shape95.set_property_value(Shape.HeightKey, 16);
            _shape95.set_property_value(Shape.MarginKey, new Thickness(2));
            _toolBarToggleButton94.Content = _shape95;
            _toolBar87.AddChild(_toolBarToggleButton94);
            _stackPanel34.AddChild(_toolBar87);
            _scrollViewer33.Content = _stackPanel34;
            _dockPanel31.AddChild(_scrollViewer33);
            _border30.SetChild(_dockPanel31);
            _dockPanel24.AddChild(_border30);
            const _border96 = new Border();
            _border96.set_property_value(DockPanel.DockKey, Dock.Left);
            _border96.set_property_value(Border.WidthKey, 200);
            _border96.set_property_value(Border.FillKey, DynamicResource(_border96, "SurfaceContainerLow"));
            _border96.set_property_value(Border.PaddingKey, new Thickness(8));
            const _dockPanel97 = new DockPanel();
            const _line98 = new Line();
            _line98.set_property_value(DockPanel.DockKey, Dock.Right);
            _line98.set_property_value(Line.OrientationKey, Orientation.Vertical);
            _line98.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line98, "OutlineVariant"), 1));
            _dockPanel97.AddChild(_line98);
            const _stackPanel99 = new StackPanel();
            _stackPanel99.set_property_value(DockPanel.DockKey, Dock.Bottom);
            const _textBlock100 = new TextBlock();
            _textBlock100.set_property_value(TextBlock.TextKey, "Document");
            _textBlock100.set_property_value(TextBlock.FontSizeKey, 11);
            _textBlock100.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock100.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock100, "OnSurfaceVariant"));
            _textBlock100.set_property_value(TextBlock.MarginKey, new Thickness(2, 12, 0, 8));
            _stackPanel99.AddChild(_textBlock100);
            const _stackPanel101 = new StackPanel();
            _stackPanel101.set_property_value(StackPanel.OrientationKey, Orientation.Horizontal);
            _stackPanel101.set_property_value(StackPanel.MarginKey, new Thickness(0, 0, 0, 8));
            const _button102 = new Button();
            _button102.set_property_value(Button.CommandKey, DataContextBinding(_button102, "SaveCommand"));
            _button102.set_property_value(Button.MarginKey, new Thickness(0, 0, 4, 0));
            const _textBlock103 = new TextBlock();
            _textBlock103.set_property_value(TextBlock.TextKey, "Save");
            _textBlock103.set_property_value(TextBlock.FontSizeKey, 11);
            _button102.Content = _textBlock103;
            _stackPanel101.AddChild(_button102);
            const _button104 = new Button();
            _button104.set_property_value(Button.CommandKey, DataContextBinding(_button104, "LoadCommand"));
            const _textBlock105 = new TextBlock();
            _textBlock105.set_property_value(TextBlock.TextKey, "Load");
            _textBlock105.set_property_value(TextBlock.FontSizeKey, 11);
            _button104.Content = _textBlock105;
            _stackPanel101.AddChild(_button104);
            _stackPanel99.AddChild(_stackPanel101);
            const _textBlock106 = new TextBlock();
            _textBlock106.set_property_value(TextBlock.TextKey, "Drag a shape onto the canvas to\n                                            place it. Click a node to\n                                            select; Ctrl-click to toggle;\n                                            Shift-click to range-extend.\n                                            Drag-rectangle on empty space\n                                            for marquee. Click empty space\n                                            to clear. Delete removes every\n                                            selected node.");
            _textBlock106.set_property_value(TextBlock.TextWrappingKey, TextWrapping.Wrap);
            _textBlock106.set_property_value(TextBlock.FontSizeKey, 10);
            _textBlock106.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock106, "OnSurfaceVariant"));
            _textBlock106.set_property_value(TextBlock.MarginKey, new Thickness(2, 4, 2, 0));
            _stackPanel99.AddChild(_textBlock106);
            _dockPanel97.AddChild(_stackPanel99);
            const _scrollViewer107 = new ScrollViewer();
            _scrollViewer107.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, false);
            const _itemsControl108 = new ItemsControl();
            _itemsControl108.set_property_value(ItemsControl.ItemsSourceKey, ServiceBinding(_itemsControl108, ServiceProvider.tokenFor(ToolboxRepository), "Pages"));
            _scrollViewer107.Content = _itemsControl108;
            _dockPanel97.AddChild(_scrollViewer107);
            _border96.SetChild(_dockPanel97);
            _dockPanel24.AddChild(_border96);
            const _border109 = new Border();
            _border109.set_property_value(DockPanel.DockKey, Dock.Right);
            _border109.set_property_value(Border.WidthKey, 320);
            _border109.set_property_value(Border.FillKey, DynamicResource(_border109, "SurfaceContainerLow"));
            _border109.set_property_value(Border.PaddingKey, new Thickness(12));
            const _dockPanel110 = new DockPanel();
            const _line111 = new Line();
            _line111.set_property_value(DockPanel.DockKey, Dock.Left);
            _line111.set_property_value(Line.OrientationKey, Orientation.Vertical);
            _line111.set_property_value(Line.StrokeKey, new Pen(DynamicResource(_line111, "OutlineVariant"), 1));
            _dockPanel110.AddChild(_line111);
            const _textBlock112 = new TextBlock();
            _textBlock112.set_property_value(DockPanel.DockKey, Dock.Top);
            _textBlock112.set_property_value(TextBlock.TextKey, "Format Shape");
            _textBlock112.set_property_value(TextBlock.FontSizeKey, 12);
            _textBlock112.set_property_value(TextBlock.FontWeightKey, FontWeight.Bold);
            _textBlock112.set_property_value(TextBlock.ForegroundKey, DynamicResource(_textBlock112, "OnSurfaceVariant"));
            _textBlock112.set_property_value(TextBlock.MarginKey, new Thickness(0, 0, 0, 8));
            _dockPanel110.AddChild(_textBlock112);
            const _scrollViewer113 = new ScrollViewer();
            _scrollViewer113.set_property_value(ScrollViewer.IsAutoHideScrollBarsKey, false);
            _scrollViewer113.set_property_value(ScrollViewer.HorizontalScrollEnabledKey, false);
            const _shapeFormatControl114 = new ShapeFormatControl();
            _shapeFormatControl114.set_property_value(ShapeFormatControl.FillKey, ElementNameBinding(() => _diagram22, "SelectionFormatFill"));
            _shapeFormatControl114.set_property_value(ShapeFormatControl.StrokeKey, ElementNameBinding(() => _diagram22, "SelectionFormatStroke"));
            _shapeFormatControl114.set_property_value(ShapeFormatControl.SourceCapTemplateKey, ElementNameBinding(() => _diagram22, "SelectionFormatSourceCap"));
            _shapeFormatControl114.set_property_value(ShapeFormatControl.TargetCapTemplateKey, ElementNameBinding(() => _diagram22, "SelectionFormatTargetCap"));
            _shapeFormatControl114.set_property_value(ShapeFormatControl.SourceCapScaleKey, ElementNameBinding(() => _diagram22, "SelectionFormatSourceCapScale"));
            _shapeFormatControl114.set_property_value(ShapeFormatControl.TargetCapScaleKey, ElementNameBinding(() => _diagram22, "SelectionFormatTargetCapScale"));
            _shapeFormatControl114.set_property_value(ShapeFormatControl.ShowCapsKey, ElementNameBinding(() => _diagram22, "SelectionIsConnector"));
            _shapeFormatControl114.set_property_value(ShapeFormatControl.CapOptionsKey, ElementNameBinding(() => _diagram22, "ConnectorCapOptions"));
            _scrollViewer113.Content = _shapeFormatControl114;
            _dockPanel110.AddChild(_scrollViewer113);
            _border109.SetChild(_dockPanel110);
            _dockPanel24.AddChild(_border109);
            const _splitter115 = new Splitter();
            _splitter115.set_property_value(DockPanel.DockKey, Dock.Right);
            _splitter115.set_property_value(Splitter.WidthKey, 6);
            _splitter115.set_property_value(Splitter.OrientationKey, Orientation.Vertical);
            _splitter115.set_property_value(Splitter.ReverseDirectionKey, true);
            _dockPanel24.AddChild(_splitter115);
            _diagram22 = new Diagram();
            _diagram22.Name = "nodes";
            _diagram22.set_property_value(Diagram.ItemsSourceKey, DataContextBinding(_diagram22, "Nodes"));
            _diagram22.set_property_value(Diagram.ConnectorsKey, DataContextBinding(_diagram22, "Connectors"));
            _diagram22.set_property_value(Diagram.ItemsPanelKey, _tmpl0);
            _diagram22.set_property_value(Diagram.SelectionModeKey, SelectionMode.Extended);
            _diagram22.set_property_value(Diagram.AllowMarqueeSelectionKey, true);
            _diagram22.set_property_value(Diagram.AlignmentGuidesEnabledKey, true);
            _diagram22.set_property_value(Diagram.SelectionResizeEnabledKey, true);
            _diagram22.set_property_value(Diagram.TextBlockAdornerEnabledKey, true);
            _diagram22.set_property_value(Diagram.ConnectorInteractionsEnabledKey, true);
            _diagram22.set_property_value(Diagram.ReflectSelectionToItemsKey, true);
            _diagram22.set_property_value(Diagram.DropReceiverKey, DataContextBinding(_diagram22, "Self"));
            _diagram22.set_property_value(Diagram.FocusableKey, true);
            _dockPanel24.AddChild(_diagram22);
            _border23.SetChild(_dockPanel24);
            return _border23;
        }, DiagramDocument);
        t.Set(DiagramDocument, _tmpl21);
        return t;
    }
    get DiagramCanvasPanel() { return this.Resolve("DiagramCanvasPanel"); }
    set DiagramCanvasPanel(v) { this.Set("DiagramCanvasPanel", v); }
    get DiagramToolboxPanel() { return this.Resolve("DiagramToolboxPanel"); }
    set DiagramToolboxPanel(v) { this.Set("DiagramToolboxPanel", v); }
    get DiagramToolTemplate() { return this.Resolve("DiagramToolTemplate"); }
    set DiagramToolTemplate(v) { this.Set("DiagramToolTemplate", v); }
    get DiagramPlacementSplitLabel() { return this.Resolve("DiagramPlacementSplitLabel"); }
    set DiagramPlacementSplitLabel(v) { this.Set("DiagramPlacementSplitLabel", v); }
    get DiagramPlacementGrid() { return this.Resolve("DiagramPlacementGrid"); }
    set DiagramPlacementGrid(v) { this.Set("DiagramPlacementGrid", v); }
}
